// An event as a channel receives it, and what a subscription selects with.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/interface/v1/events.proto

package interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One conclusion the Core reached: eight fields, the same on every event and on every surface.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Numbers the event within one life of the instance; what a snapshot's sequence, a confirmation and a
	// cause refer to.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// What happened: <subject-kind>.<object>.<verb>, and what a subscription filters on.
	Type    string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Subject *Subject `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	// The Core's clock, at the conclusion.
	Time  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	Actor *Actor                 `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	// 0 to 99, higher more serious.
	Severity uint32 `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`
	// The class a unit declared and was granted, on unit.occurrence.reported alone.
	Occurrence string `protobuf:"bytes,7,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	// The event this one follows from; zero where there is none.
	Cause uint64 `protobuf:"varint,8,opt,name=cause,proto3" json:"cause,omitempty"`
	// Typed per type, and skippable: a consumer decodes only what it knows.
	Detail        []byte `protobuf:"bytes,9,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_yoke_interface_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *Event) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Event) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Event) GetCause() uint64 {
	if x != nil {
		return x.Cause
	}
	return 0
}

func (x *Event) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

// Who caused an event, established by the Core and never claimed.
type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// core, operator, unit or host: four, closed.
	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// The person the channel established, where it established one.
	Person        string `protobuf:"bytes,2,opt,name=person,proto3" json:"person,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_yoke_interface_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *Actor) GetPerson() string {
	if x != nil {
		return x.Person
	}
	return ""
}

// What a subscription selects, on four independent axes combined by conjunction. An axis left empty
// selects everything on it, and a kind this channel does not observe matches nothing.
type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A subject kind, and an identity where one is named.
	SubjectKind     string `protobuf:"bytes,1,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	SubjectIdentity string `protobuf:"bytes,2,opt,name=subject_identity,json=subjectIdentity,proto3" json:"subject_identity,omitempty"`
	// At or above.
	Floor uint32 `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	// Exactly, or by prefix of segments.
	Type       string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	TypePrefix bool   `protobuf:"varint,5,opt,name=type_prefix,json=typePrefix,proto3" json:"type_prefix,omitempty"`
	// Exactly, or by prefix of segments; reaches only the events that carry one.
	Occurrence       string `protobuf:"bytes,6,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	OccurrencePrefix bool   `protobuf:"varint,7,opt,name=occurrence_prefix,json=occurrencePrefix,proto3" json:"occurrence_prefix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_yoke_interface_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *Filter) GetSubjectIdentity() string {
	if x != nil {
		return x.SubjectIdentity
	}
	return ""
}

func (x *Filter) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *Filter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Filter) GetTypePrefix() bool {
	if x != nil {
		return x.TypePrefix
	}
	return false
}

func (x *Filter) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Filter) GetOccurrencePrefix() bool {
	if x != nil {
		return x.OccurrencePrefix
	}
	return false
}

var File_yoke_interface_v1_events_proto protoreflect.FileDescriptor

const file_yoke_interface_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1eyoke/interface/v1/events.proto\x12\x11yoke.interface.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dyoke/interface/v1/codes.proto\"\xad\x02\n" +
	"\x05Event\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x124\n" +
	"\asubject\x18\x03 \x01(\v2\x1a.yoke.interface.v1.SubjectR\asubject\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12.\n" +
	"\x05actor\x18\x05 \x01(\v2\x18.yoke.interface.v1.ActorR\x05actor\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\rR\bseverity\x12\x1e\n" +
	"\n" +
	"occurrence\x18\a \x01(\tR\n" +
	"occurrence\x12\x14\n" +
	"\x05cause\x18\b \x01(\x04R\x05cause\x12\x16\n" +
	"\x06detail\x18\t \x01(\fR\x06detail\"5\n" +
	"\x05Actor\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x16\n" +
	"\x06person\x18\x02 \x01(\tR\x06person\"\xee\x01\n" +
	"\x06Filter\x12!\n" +
	"\fsubject_kind\x18\x01 \x01(\tR\vsubjectKind\x12)\n" +
	"\x10subject_identity\x18\x02 \x01(\tR\x0fsubjectIdentity\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\rR\x05floor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1f\n" +
	"\vtype_prefix\x18\x05 \x01(\bR\n" +
	"typePrefix\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x06 \x01(\tR\n" +
	"occurrence\x12+\n" +
	"\x11occurrence_prefix\x18\a \x01(\bR\x10occurrencePrefixBBZ@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1b\x06proto3"

var (
	file_yoke_interface_v1_events_proto_rawDescOnce sync.Once
	file_yoke_interface_v1_events_proto_rawDescData []byte
)

func file_yoke_interface_v1_events_proto_rawDescGZIP() []byte {
	file_yoke_interface_v1_events_proto_rawDescOnce.Do(func() {
		file_yoke_interface_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_events_proto_rawDesc), len(file_yoke_interface_v1_events_proto_rawDesc)))
	})
	return file_yoke_interface_v1_events_proto_rawDescData
}

var file_yoke_interface_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yoke_interface_v1_events_proto_goTypes = []any{
	(*Event)(nil),                 // 0: yoke.interface.v1.Event
	(*Actor)(nil),                 // 1: yoke.interface.v1.Actor
	(*Filter)(nil),                // 2: yoke.interface.v1.Filter
	(*Subject)(nil),               // 3: yoke.interface.v1.Subject
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_yoke_interface_v1_events_proto_depIdxs = []int32{
	3, // 0: yoke.interface.v1.Event.subject:type_name -> yoke.interface.v1.Subject
	4, // 1: yoke.interface.v1.Event.time:type_name -> google.protobuf.Timestamp
	1, // 2: yoke.interface.v1.Event.actor:type_name -> yoke.interface.v1.Actor
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yoke_interface_v1_events_proto_init() }
func file_yoke_interface_v1_events_proto_init() {
	if File_yoke_interface_v1_events_proto != nil {
		return
	}
	file_yoke_interface_v1_codes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_events_proto_rawDesc), len(file_yoke_interface_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_interface_v1_events_proto_goTypes,
		DependencyIndexes: file_yoke_interface_v1_events_proto_depIdxs,
		MessageInfos:      file_yoke_interface_v1_events_proto_msgTypes,
	}.Build()
	File_yoke_interface_v1_events_proto = out.File
	file_yoke_interface_v1_events_proto_goTypes = nil
	file_yoke_interface_v1_events_proto_depIdxs = nil
}
