// The typed projection: one service and one method, because an interface is always attached. Opening
// the stream is attaching; one stream carries many calls, each correlated by an identity the caller
// chose, and each ending with exactly one completion.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/interface/v1/interface.proto

package interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Completion_By int32

const (
	Completion_BY_UNSPECIFIED Completion_By = 0
	// The caller cancelled it.
	Completion_BY_CALLER Completion_By = 1
	// The Core ended it.
	Completion_BY_CORE Completion_By = 2
)

// Enum value maps for Completion_By.
var (
	Completion_By_name = map[int32]string{
		0: "BY_UNSPECIFIED",
		1: "BY_CALLER",
		2: "BY_CORE",
	}
	Completion_By_value = map[string]int32{
		"BY_UNSPECIFIED": 0,
		"BY_CALLER":      1,
		"BY_CORE":        2,
	}
)

func (x Completion_By) Enum() *Completion_By {
	p := new(Completion_By)
	*p = x
	return p
}

func (x Completion_By) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Completion_By) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_interface_v1_interface_proto_enumTypes[0].Descriptor()
}

func (Completion_By) Type() protoreflect.EnumType {
	return &file_yoke_interface_v1_interface_proto_enumTypes[0]
}

func (x Completion_By) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Completion_By.Descriptor instead.
func (Completion_By) EnumDescriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{5, 0}
}

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chosen by the caller, unique within this attachment.
	Call string `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	// Types that are valid to be assigned to Carries:
	//
	//	*ClientFrame_Request
	//	*ClientFrame_Cancel
	Carries       isClientFrame_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetCall() string {
	if x != nil {
		return x.Call
	}
	return ""
}

func (x *ClientFrame) GetCarries() isClientFrame_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *ClientFrame) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Carries.(*ClientFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ClientFrame) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Carries.(*ClientFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isClientFrame_Carries interface {
	isClientFrame_Carries()
}

type ClientFrame_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type ClientFrame_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*ClientFrame_Request) isClientFrame_Carries() {}

func (*ClientFrame_Cancel) isClientFrame_Carries() {}

// Ends a call in flight.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{1}
}

type CoreFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call this frame belongs to; empty on the opening.
	Call string `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	// Types that are valid to be assigned to Carries:
	//
	//	*CoreFrame_Opening
	//	*CoreFrame_Answer
	//	*CoreFrame_Event
	//	*CoreFrame_Delivery
	//	*CoreFrame_Refusal
	//	*CoreFrame_Completion
	Carries       isCoreFrame_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreFrame) Reset() {
	*x = CoreFrame{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrame) ProtoMessage() {}

func (x *CoreFrame) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrame.ProtoReflect.Descriptor instead.
func (*CoreFrame) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{2}
}

func (x *CoreFrame) GetCall() string {
	if x != nil {
		return x.Call
	}
	return ""
}

func (x *CoreFrame) GetCarries() isCoreFrame_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *CoreFrame) GetOpening() *Opening {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Opening); ok {
			return x.Opening
		}
	}
	return nil
}

func (x *CoreFrame) GetAnswer() *Response {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *CoreFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *CoreFrame) GetDelivery() *StreamDelivery {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Delivery); ok {
			return x.Delivery
		}
	}
	return nil
}

func (x *CoreFrame) GetRefusal() *Refusal {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Refusal); ok {
			return x.Refusal
		}
	}
	return nil
}

func (x *CoreFrame) GetCompletion() *Completion {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isCoreFrame_Carries interface {
	isCoreFrame_Carries()
}

type CoreFrame_Opening struct {
	Opening *Opening `protobuf:"bytes,2,opt,name=opening,proto3,oneof"`
}

type CoreFrame_Answer struct {
	Answer *Response `protobuf:"bytes,3,opt,name=answer,proto3,oneof"`
}

type CoreFrame_Event struct {
	Event *Event `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type CoreFrame_Delivery struct {
	// A stream's data, where the client cannot reach a path in the instance's tree.
	Delivery *StreamDelivery `protobuf:"bytes,5,opt,name=delivery,proto3,oneof"`
}

type CoreFrame_Refusal struct {
	// A refusal belongs to one call and does not end the attachment.
	Refusal *Refusal `protobuf:"bytes,6,opt,name=refusal,proto3,oneof"`
}

type CoreFrame_Completion struct {
	Completion *Completion `protobuf:"bytes,7,opt,name=completion,proto3,oneof"`
}

func (*CoreFrame_Opening) isCoreFrame_Carries() {}

func (*CoreFrame_Answer) isCoreFrame_Carries() {}

func (*CoreFrame_Event) isCoreFrame_Carries() {}

func (*CoreFrame_Delivery) isCoreFrame_Carries() {}

func (*CoreFrame_Refusal) isCoreFrame_Carries() {}

func (*CoreFrame_Completion) isCoreFrame_Carries() {}

// The Core's first frame: the opening picture, before anything the client asked for.
type Opening struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What this channel may address and observe, the state of each, and the channel's own state.
	Picture *Snapshot `protobuf:"bytes,1,opt,name=picture,proto3" json:"picture,omitempty"`
	// The call identity of the standing subscription, which the client may replace or cancel.
	Subscription string `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// The contract version this Core speaks.
	Version       uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opening) Reset() {
	*x = Opening{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{3}
}

func (x *Opening) GetPicture() *Snapshot {
	if x != nil {
		return x.Picture
	}
	return nil
}

func (x *Opening) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Opening) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// A stream's data on the connection: the delivery, and the frame's header and payload unchanged.
type StreamDelivery struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Delivery string                 `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	// Per stream, from 1, never reused within an activation.
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// The sender's clock at emission, in nanoseconds.
	SentAt        uint64 `protobuf:"varint,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDelivery) Reset() {
	*x = StreamDelivery{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDelivery) ProtoMessage() {}

func (x *StreamDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDelivery.ProtoReflect.Descriptor instead.
func (*StreamDelivery) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{4}
}

func (x *StreamDelivery) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

func (x *StreamDelivery) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *StreamDelivery) GetSentAt() uint64 {
	if x != nil {
		return x.SentAt
	}
	return 0
}

func (x *StreamDelivery) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// The end of a call; never inferred from silence.
type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	By            Completion_By          `protobuf:"varint,1,opt,name=by,proto3,enum=yoke.interface.v1.Completion_By" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_interface_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_interface_proto_rawDescGZIP(), []int{5}
}

func (x *Completion) GetBy() Completion_By {
	if x != nil {
		return x.By
	}
	return Completion_BY_UNSPECIFIED
}

var File_yoke_interface_v1_interface_proto protoreflect.FileDescriptor

const file_yoke_interface_v1_interface_proto_rawDesc = "" +
	"\n" +
	"!yoke/interface/v1/interface.proto\x12\x11yoke.interface.v1\x1a\x1dyoke/interface/v1/codes.proto\x1a\x1eyoke/interface/v1/events.proto\x1a\"yoke/interface/v1/operations.proto\x1a\x1fyoke/interface/v1/records.proto\"\x99\x01\n" +
	"\vClientFrame\x12\x12\n" +
	"\x04call\x18\x01 \x01(\tR\x04call\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1a.yoke.interface.v1.RequestH\x00R\arequest\x123\n" +
	"\x06cancel\x18\x03 \x01(\v2\x19.yoke.interface.v1.CancelH\x00R\x06cancelB\t\n" +
	"\acarries\"\b\n" +
	"\x06Cancel\"\x85\x03\n" +
	"\tCoreFrame\x12\x12\n" +
	"\x04call\x18\x01 \x01(\tR\x04call\x126\n" +
	"\aopening\x18\x02 \x01(\v2\x1a.yoke.interface.v1.OpeningH\x00R\aopening\x125\n" +
	"\x06answer\x18\x03 \x01(\v2\x1b.yoke.interface.v1.ResponseH\x00R\x06answer\x120\n" +
	"\x05event\x18\x04 \x01(\v2\x18.yoke.interface.v1.EventH\x00R\x05event\x12?\n" +
	"\bdelivery\x18\x05 \x01(\v2!.yoke.interface.v1.StreamDeliveryH\x00R\bdelivery\x126\n" +
	"\arefusal\x18\x06 \x01(\v2\x1a.yoke.interface.v1.RefusalH\x00R\arefusal\x12?\n" +
	"\n" +
	"completion\x18\a \x01(\v2\x1d.yoke.interface.v1.CompletionH\x00R\n" +
	"completionB\t\n" +
	"\acarries\"~\n" +
	"\aOpening\x125\n" +
	"\apicture\x18\x01 \x01(\v2\x1b.yoke.interface.v1.SnapshotR\apicture\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\"{\n" +
	"\x0eStreamDelivery\x12\x1a\n" +
	"\bdelivery\x18\x01 \x01(\tR\bdelivery\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\x04R\x06sentAt\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"t\n" +
	"\n" +
	"Completion\x120\n" +
	"\x02by\x18\x01 \x01(\x0e2 .yoke.interface.v1.Completion.ByR\x02by\"4\n" +
	"\x02By\x12\x12\n" +
	"\x0eBY_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tBY_CALLER\x10\x01\x12\v\n" +
	"\aBY_CORE\x10\x022W\n" +
	"\tInterface\x12J\n" +
	"\x06Attach\x12\x1e.yoke.interface.v1.ClientFrame\x1a\x1c.yoke.interface.v1.CoreFrame(\x010\x01BBZ@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1b\x06proto3"

var (
	file_yoke_interface_v1_interface_proto_rawDescOnce sync.Once
	file_yoke_interface_v1_interface_proto_rawDescData []byte
)

func file_yoke_interface_v1_interface_proto_rawDescGZIP() []byte {
	file_yoke_interface_v1_interface_proto_rawDescOnce.Do(func() {
		file_yoke_interface_v1_interface_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_interface_proto_rawDesc), len(file_yoke_interface_v1_interface_proto_rawDesc)))
	})
	return file_yoke_interface_v1_interface_proto_rawDescData
}

var file_yoke_interface_v1_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_interface_v1_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_yoke_interface_v1_interface_proto_goTypes = []any{
	(Completion_By)(0),     // 0: yoke.interface.v1.Completion.By
	(*ClientFrame)(nil),    // 1: yoke.interface.v1.ClientFrame
	(*Cancel)(nil),         // 2: yoke.interface.v1.Cancel
	(*CoreFrame)(nil),      // 3: yoke.interface.v1.CoreFrame
	(*Opening)(nil),        // 4: yoke.interface.v1.Opening
	(*StreamDelivery)(nil), // 5: yoke.interface.v1.StreamDelivery
	(*Completion)(nil),     // 6: yoke.interface.v1.Completion
	(*Request)(nil),        // 7: yoke.interface.v1.Request
	(*Response)(nil),       // 8: yoke.interface.v1.Response
	(*Event)(nil),          // 9: yoke.interface.v1.Event
	(*Refusal)(nil),        // 10: yoke.interface.v1.Refusal
	(*Snapshot)(nil),       // 11: yoke.interface.v1.Snapshot
}
var file_yoke_interface_v1_interface_proto_depIdxs = []int32{
	7,  // 0: yoke.interface.v1.ClientFrame.request:type_name -> yoke.interface.v1.Request
	2,  // 1: yoke.interface.v1.ClientFrame.cancel:type_name -> yoke.interface.v1.Cancel
	4,  // 2: yoke.interface.v1.CoreFrame.opening:type_name -> yoke.interface.v1.Opening
	8,  // 3: yoke.interface.v1.CoreFrame.answer:type_name -> yoke.interface.v1.Response
	9,  // 4: yoke.interface.v1.CoreFrame.event:type_name -> yoke.interface.v1.Event
	5,  // 5: yoke.interface.v1.CoreFrame.delivery:type_name -> yoke.interface.v1.StreamDelivery
	10, // 6: yoke.interface.v1.CoreFrame.refusal:type_name -> yoke.interface.v1.Refusal
	6,  // 7: yoke.interface.v1.CoreFrame.completion:type_name -> yoke.interface.v1.Completion
	11, // 8: yoke.interface.v1.Opening.picture:type_name -> yoke.interface.v1.Snapshot
	0,  // 9: yoke.interface.v1.Completion.by:type_name -> yoke.interface.v1.Completion.By
	1,  // 10: yoke.interface.v1.Interface.Attach:input_type -> yoke.interface.v1.ClientFrame
	3,  // 11: yoke.interface.v1.Interface.Attach:output_type -> yoke.interface.v1.CoreFrame
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_yoke_interface_v1_interface_proto_init() }
func file_yoke_interface_v1_interface_proto_init() {
	if File_yoke_interface_v1_interface_proto != nil {
		return
	}
	file_yoke_interface_v1_codes_proto_init()
	file_yoke_interface_v1_events_proto_init()
	file_yoke_interface_v1_operations_proto_init()
	file_yoke_interface_v1_records_proto_init()
	file_yoke_interface_v1_interface_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Request)(nil),
		(*ClientFrame_Cancel)(nil),
	}
	file_yoke_interface_v1_interface_proto_msgTypes[2].OneofWrappers = []any{
		(*CoreFrame_Opening)(nil),
		(*CoreFrame_Answer)(nil),
		(*CoreFrame_Event)(nil),
		(*CoreFrame_Delivery)(nil),
		(*CoreFrame_Refusal)(nil),
		(*CoreFrame_Completion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_interface_proto_rawDesc), len(file_yoke_interface_v1_interface_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yoke_interface_v1_interface_proto_goTypes,
		DependencyIndexes: file_yoke_interface_v1_interface_proto_depIdxs,
		EnumInfos:         file_yoke_interface_v1_interface_proto_enumTypes,
		MessageInfos:      file_yoke_interface_v1_interface_proto_msgTypes,
	}.Build()
	File_yoke_interface_v1_interface_proto = out.File
	file_yoke_interface_v1_interface_proto_goTypes = nil
	file_yoke_interface_v1_interface_proto_depIdxs = nil
}
