// The one operation union: an operation is a member of Request and never of a projection, so it is on
// both projections or on neither. Response has one answer per operation, in the same order. Nothing here
// names a plugin, an incarnation or a client: what a client may do is decided by the channel it reached.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/interface/v1/operations.proto

package interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Acknowledged_Outcome int32

const (
	Acknowledged_OUTCOME_UNSPECIFIED Acknowledged_Outcome = 0
	Acknowledged_OUTCOME_ACCEPTED    Acknowledged_Outcome = 1
	Acknowledged_OUTCOME_DONE        Acknowledged_Outcome = 2
	Acknowledged_OUTCOME_FAILED      Acknowledged_Outcome = 3
)

// Enum value maps for Acknowledged_Outcome.
var (
	Acknowledged_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_DONE",
		3: "OUTCOME_FAILED",
	}
	Acknowledged_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_ACCEPTED":    1,
		"OUTCOME_DONE":        2,
		"OUTCOME_FAILED":      3,
	}
)

func (x Acknowledged_Outcome) Enum() *Acknowledged_Outcome {
	p := new(Acknowledged_Outcome)
	*p = x
	return p
}

func (x Acknowledged_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Acknowledged_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_interface_v1_operations_proto_enumTypes[0].Descriptor()
}

func (Acknowledged_Outcome) Type() protoreflect.EnumType {
	return &file_yoke_interface_v1_operations_proto_enumTypes[0]
}

func (x Acknowledged_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Acknowledged_Outcome.Descriptor instead.
func (Acknowledged_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{14, 0}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The contract's version, checked on every request.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Request_Authenticate
	//	*Request_Read
	//	*Request_Subscribe
	//	*Request_Confirm
	//	*Request_Command
	//	*Request_Query
	//	*Request_StreamStart
	//	*Request_StreamStop
	//	*Request_StreamSubscribe
	//	*Request_StreamUnsubscribe
	//	*Request_Reclaim
	Operation     isRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Request) GetOperation() isRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Request) GetAuthenticate() *Authenticate {
	if x != nil {
		if x, ok := x.Operation.(*Request_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *Request) GetRead() *Read {
	if x != nil {
		if x, ok := x.Operation.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Operation.(*Request_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Request) GetConfirm() *Confirm {
	if x != nil {
		if x, ok := x.Operation.(*Request_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *Request) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Operation.(*Request_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Request) GetQuery() *Question {
	if x != nil {
		if x, ok := x.Operation.(*Request_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Request) GetStreamStart() *UnitStream {
	if x != nil {
		if x, ok := x.Operation.(*Request_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *Request) GetStreamStop() *UnitStream {
	if x != nil {
		if x, ok := x.Operation.(*Request_StreamStop); ok {
			return x.StreamStop
		}
	}
	return nil
}

func (x *Request) GetStreamSubscribe() *UnitStream {
	if x != nil {
		if x, ok := x.Operation.(*Request_StreamSubscribe); ok {
			return x.StreamSubscribe
		}
	}
	return nil
}

func (x *Request) GetStreamUnsubscribe() *StreamRelease {
	if x != nil {
		if x, ok := x.Operation.(*Request_StreamUnsubscribe); ok {
			return x.StreamUnsubscribe
		}
	}
	return nil
}

func (x *Request) GetReclaim() *Reclaim {
	if x != nil {
		if x, ok := x.Operation.(*Request_Reclaim); ok {
			return x.Reclaim
		}
	}
	return nil
}

type isRequest_Operation interface {
	isRequest_Operation()
}

type Request_Authenticate struct {
	Authenticate *Authenticate `protobuf:"bytes,2,opt,name=authenticate,proto3,oneof"`
}

type Request_Read struct {
	Read *Read `protobuf:"bytes,3,opt,name=read,proto3,oneof"`
}

type Request_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,4,opt,name=subscribe,proto3,oneof"`
}

type Request_Confirm struct {
	Confirm *Confirm `protobuf:"bytes,5,opt,name=confirm,proto3,oneof"`
}

type Request_Command struct {
	Command *Command `protobuf:"bytes,6,opt,name=command,proto3,oneof"`
}

type Request_Query struct {
	Query *Question `protobuf:"bytes,7,opt,name=query,proto3,oneof"`
}

type Request_StreamStart struct {
	StreamStart *UnitStream `protobuf:"bytes,8,opt,name=stream_start,json=streamStart,proto3,oneof"`
}

type Request_StreamStop struct {
	StreamStop *UnitStream `protobuf:"bytes,9,opt,name=stream_stop,json=streamStop,proto3,oneof"`
}

type Request_StreamSubscribe struct {
	StreamSubscribe *UnitStream `protobuf:"bytes,10,opt,name=stream_subscribe,json=streamSubscribe,proto3,oneof"`
}

type Request_StreamUnsubscribe struct {
	StreamUnsubscribe *StreamRelease `protobuf:"bytes,11,opt,name=stream_unsubscribe,json=streamUnsubscribe,proto3,oneof"`
}

type Request_Reclaim struct {
	Reclaim *Reclaim `protobuf:"bytes,12,opt,name=reclaim,proto3,oneof"`
}

func (*Request_Authenticate) isRequest_Operation() {}

func (*Request_Read) isRequest_Operation() {}

func (*Request_Subscribe) isRequest_Operation() {}

func (*Request_Confirm) isRequest_Operation() {}

func (*Request_Command) isRequest_Operation() {}

func (*Request_Query) isRequest_Operation() {}

func (*Request_StreamStart) isRequest_Operation() {}

func (*Request_StreamStop) isRequest_Operation() {}

func (*Request_StreamSubscribe) isRequest_Operation() {}

func (*Request_StreamUnsubscribe) isRequest_Operation() {}

func (*Request_Reclaim) isRequest_Operation() {}

// What establishes the caller on a channel whose class requires it: an account and its secret, asked of
// the host, or a session token already issued on this channel.
type Authenticate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Credential:
	//
	//	*Authenticate_Password_
	//	*Authenticate_Token
	Credential    isAuthenticate_Credential `protobuf_oneof:"credential"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticate) Reset() {
	*x = Authenticate{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticate) ProtoMessage() {}

func (x *Authenticate) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticate.ProtoReflect.Descriptor instead.
func (*Authenticate) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{1}
}

func (x *Authenticate) GetCredential() isAuthenticate_Credential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *Authenticate) GetPassword() *Authenticate_Password {
	if x != nil {
		if x, ok := x.Credential.(*Authenticate_Password_); ok {
			return x.Password
		}
	}
	return nil
}

func (x *Authenticate) GetToken() string {
	if x != nil {
		if x, ok := x.Credential.(*Authenticate_Token); ok {
			return x.Token
		}
	}
	return ""
}

type isAuthenticate_Credential interface {
	isAuthenticate_Credential()
}

type Authenticate_Password_ struct {
	Password *Authenticate_Password `protobuf:"bytes,1,opt,name=password,proto3,oneof"`
}

type Authenticate_Token struct {
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

func (*Authenticate_Password_) isAuthenticate_Credential() {}

func (*Authenticate_Token) isAuthenticate_Credential() {}

// A subject kind, and an identity where one is named: with none, every subject of that kind this
// channel observes.
type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{2}
}

func (x *Read) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Read) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{3}
}

func (x *Subscribe) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// I am current as of this sequence, on this subscription.
type Confirm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call identity of the subscription confirmed.
	Subscription  string `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Sequence      uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirm) Reset() {
	*x = Confirm{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirm) ProtoMessage() {}

func (x *Confirm) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirm.ProtoReflect.Descriptor instead.
func (*Confirm) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{4}
}

func (x *Confirm) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Confirm) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// An instruction for a unit, opaque to the Core and bounded at 1 MiB.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// A question for a unit, opaque to the Core and bounded at 1 MiB.
type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{6}
}

func (x *Question) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Question) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type UnitStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitStream) Reset() {
	*x = UnitStream{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitStream) ProtoMessage() {}

func (x *UnitStream) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitStream.ProtoReflect.Descriptor instead.
func (*UnitStream) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{7}
}

func (x *UnitStream) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitStream) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type StreamRelease struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The delivery stream.subscribe answered with.
	Delivery      string `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRelease) Reset() {
	*x = StreamRelease{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRelease) ProtoMessage() {}

func (x *StreamRelease) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRelease.ProtoReflect.Descriptor instead.
func (*StreamRelease) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{8}
}

func (x *StreamRelease) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

// Take control back, on a channel bound as a local socket.
type Reclaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reclaim) Reset() {
	*x = Reclaim{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reclaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reclaim) ProtoMessage() {}

func (x *Reclaim) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reclaim.ProtoReflect.Descriptor instead.
func (*Reclaim) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{9}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Answer:
	//
	//	*Response_Authenticate
	//	*Response_Read
	//	*Response_Subscribe
	//	*Response_Confirm
	//	*Response_Command
	//	*Response_Query
	//	*Response_StreamStart
	//	*Response_StreamStop
	//	*Response_StreamSubscribe
	//	*Response_StreamUnsubscribe
	//	*Response_Reclaim
	Answer        isResponse_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{10}
}

func (x *Response) GetAnswer() isResponse_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *Response) GetAuthenticate() *Authenticated {
	if x != nil {
		if x, ok := x.Answer.(*Response_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *Response) GetRead() *Records {
	if x != nil {
		if x, ok := x.Answer.(*Response_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Response) GetSubscribe() *Subscribed {
	if x != nil {
		if x, ok := x.Answer.(*Response_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *Response) GetConfirm() *Confirmed {
	if x != nil {
		if x, ok := x.Answer.(*Response_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *Response) GetCommand() *Acknowledged {
	if x != nil {
		if x, ok := x.Answer.(*Response_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Response) GetQuery() *Answered {
	if x != nil {
		if x, ok := x.Answer.(*Response_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Response) GetStreamStart() *Acknowledged {
	if x != nil {
		if x, ok := x.Answer.(*Response_StreamStart); ok {
			return x.StreamStart
		}
	}
	return nil
}

func (x *Response) GetStreamStop() *Acknowledged {
	if x != nil {
		if x, ok := x.Answer.(*Response_StreamStop); ok {
			return x.StreamStop
		}
	}
	return nil
}

func (x *Response) GetStreamSubscribe() *Delivering {
	if x != nil {
		if x, ok := x.Answer.(*Response_StreamSubscribe); ok {
			return x.StreamSubscribe
		}
	}
	return nil
}

func (x *Response) GetStreamUnsubscribe() *Released {
	if x != nil {
		if x, ok := x.Answer.(*Response_StreamUnsubscribe); ok {
			return x.StreamUnsubscribe
		}
	}
	return nil
}

func (x *Response) GetReclaim() *Reclaimed {
	if x != nil {
		if x, ok := x.Answer.(*Response_Reclaim); ok {
			return x.Reclaim
		}
	}
	return nil
}

type isResponse_Answer interface {
	isResponse_Answer()
}

type Response_Authenticate struct {
	Authenticate *Authenticated `protobuf:"bytes,1,opt,name=authenticate,proto3,oneof"`
}

type Response_Read struct {
	Read *Records `protobuf:"bytes,2,opt,name=read,proto3,oneof"`
}

type Response_Subscribe struct {
	Subscribe *Subscribed `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type Response_Confirm struct {
	Confirm *Confirmed `protobuf:"bytes,4,opt,name=confirm,proto3,oneof"`
}

type Response_Command struct {
	Command *Acknowledged `protobuf:"bytes,5,opt,name=command,proto3,oneof"`
}

type Response_Query struct {
	Query *Answered `protobuf:"bytes,6,opt,name=query,proto3,oneof"`
}

type Response_StreamStart struct {
	StreamStart *Acknowledged `protobuf:"bytes,7,opt,name=stream_start,json=streamStart,proto3,oneof"`
}

type Response_StreamStop struct {
	StreamStop *Acknowledged `protobuf:"bytes,8,opt,name=stream_stop,json=streamStop,proto3,oneof"`
}

type Response_StreamSubscribe struct {
	StreamSubscribe *Delivering `protobuf:"bytes,9,opt,name=stream_subscribe,json=streamSubscribe,proto3,oneof"`
}

type Response_StreamUnsubscribe struct {
	StreamUnsubscribe *Released `protobuf:"bytes,10,opt,name=stream_unsubscribe,json=streamUnsubscribe,proto3,oneof"`
}

type Response_Reclaim struct {
	Reclaim *Reclaimed `protobuf:"bytes,11,opt,name=reclaim,proto3,oneof"`
}

func (*Response_Authenticate) isResponse_Answer() {}

func (*Response_Read) isResponse_Answer() {}

func (*Response_Subscribe) isResponse_Answer() {}

func (*Response_Confirm) isResponse_Answer() {}

func (*Response_Command) isResponse_Answer() {}

func (*Response_Query) isResponse_Answer() {}

func (*Response_StreamStart) isResponse_Answer() {}

func (*Response_StreamStop) isResponse_Answer() {}

func (*Response_StreamSubscribe) isResponse_Answer() {}

func (*Response_StreamUnsubscribe) isResponse_Answer() {}

func (*Response_Reclaim) isResponse_Answer() {}

// The caller established: the account, and the session token that carries the answer through a session.
type Authenticated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Expires       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticated) Reset() {
	*x = Authenticated{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticated) ProtoMessage() {}

func (x *Authenticated) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticated.ProtoReflect.Descriptor instead.
func (*Authenticated) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{11}
}

func (x *Authenticated) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Authenticated) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Authenticated) GetExpires() *timestamppb.Timestamp {
	if x != nil {
		return x.Expires
	}
	return nil
}

// What a subscription carries: the snapshot it opens with, an event, or an overflow and the fresh
// snapshot that follows it.
type Subscribed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Carries:
	//
	//	*Subscribed_Snapshot
	//	*Subscribed_Event
	//	*Subscribed_Overflow
	Carries       isSubscribed_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribed) Reset() {
	*x = Subscribed{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribed) ProtoMessage() {}

func (x *Subscribed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribed.ProtoReflect.Descriptor instead.
func (*Subscribed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{12}
}

func (x *Subscribed) GetCarries() isSubscribed_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *Subscribed) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Subscribed) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Subscribed) GetOverflow() *Snapshot {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Overflow); ok {
			return x.Overflow
		}
	}
	return nil
}

type isSubscribed_Carries interface {
	isSubscribed_Carries()
}

type Subscribed_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type Subscribed_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type Subscribed_Overflow struct {
	Overflow *Snapshot `protobuf:"bytes,3,opt,name=overflow,proto3,oneof"`
}

func (*Subscribed_Snapshot) isSubscribed_Carries() {}

func (*Subscribed_Event) isSubscribed_Carries() {}

func (*Subscribed_Overflow) isSubscribed_Carries() {}

type Confirmed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmed) Reset() {
	*x = Confirmed{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmed) ProtoMessage() {}

func (x *Confirmed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmed.ProtoReflect.Descriptor instead.
func (*Confirmed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{13}
}

// A unit's acknowledgement, correlated to what it answers.
type Acknowledged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       Acknowledged_Outcome   `protobuf:"varint,1,opt,name=outcome,proto3,enum=yoke.interface.v1.Acknowledged_Outcome" json:"outcome,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Acknowledged) Reset() {
	*x = Acknowledged{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledged) ProtoMessage() {}

func (x *Acknowledged) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledged.ProtoReflect.Descriptor instead.
func (*Acknowledged) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{14}
}

func (x *Acknowledged) GetOutcome() Acknowledged_Outcome {
	if x != nil {
		return x.Outcome
	}
	return Acknowledged_OUTCOME_UNSPECIFIED
}

func (x *Acknowledged) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// A unit's answer, opaque to the Core and bounded at 1 MiB.
type Answered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answered) Reset() {
	*x = Answered{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answered) ProtoMessage() {}

func (x *Answered) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answered.ProtoReflect.Descriptor instead.
func (*Answered) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{15}
}

func (x *Answered) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Where a stream's data will arrive, which a client never derives, and whether the stream is flowing.
type Delivering struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The delivery: the subscriber's counter, zero-padded to eight digits.
	Delivery string `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	// Types that are valid to be assigned to Arrives:
	//
	//	*Delivering_Socket
	//	*Delivering_Connection
	//	*Delivering_Path
	Arrives       isDelivering_Arrives `protobuf_oneof:"arrives"`
	Flowing       bool                 `protobuf:"varint,5,opt,name=flowing,proto3" json:"flowing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivering) Reset() {
	*x = Delivering{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivering) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivering) ProtoMessage() {}

func (x *Delivering) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivering.ProtoReflect.Descriptor instead.
func (*Delivering) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{16}
}

func (x *Delivering) GetDelivery() string {
	if x != nil {
		return x.Delivery
	}
	return ""
}

func (x *Delivering) GetArrives() isDelivering_Arrives {
	if x != nil {
		return x.Arrives
	}
	return nil
}

func (x *Delivering) GetSocket() string {
	if x != nil {
		if x, ok := x.Arrives.(*Delivering_Socket); ok {
			return x.Socket
		}
	}
	return ""
}

func (x *Delivering) GetConnection() bool {
	if x != nil {
		if x, ok := x.Arrives.(*Delivering_Connection); ok {
			return x.Connection
		}
	}
	return false
}

func (x *Delivering) GetPath() string {
	if x != nil {
		if x, ok := x.Arrives.(*Delivering_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *Delivering) GetFlowing() bool {
	if x != nil {
		return x.Flowing
	}
	return false
}

type isDelivering_Arrives interface {
	isDelivering_Arrives()
}

type Delivering_Socket struct {
	// A per-subscriber socket in the instance's tree, which the client connects to.
	Socket string `protobuf:"bytes,2,opt,name=socket,proto3,oneof"`
}

type Delivering_Connection struct {
	// On this connection, as stream deliveries carrying the delivery.
	Connection bool `protobuf:"varint,3,opt,name=connection,proto3,oneof"`
}

type Delivering_Path struct {
	// The browser projection's path, upgraded to a binary WebSocket.
	Path string `protobuf:"bytes,4,opt,name=path,proto3,oneof"`
}

func (*Delivering_Socket) isDelivering_Arrives() {}

func (*Delivering_Connection) isDelivering_Arrives() {}

func (*Delivering_Path) isDelivering_Arrives() {}

type Released struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Released) Reset() {
	*x = Released{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Released) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Released) ProtoMessage() {}

func (x *Released) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Released.ProtoReflect.Descriptor instead.
func (*Released) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{17}
}

// The channel's state after the recomputation; a reclaim that changed nothing says so.
type Reclaimed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       *ChannelRecord         `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reclaimed) Reset() {
	*x = Reclaimed{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reclaimed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reclaimed) ProtoMessage() {}

func (x *Reclaimed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reclaimed.ProtoReflect.Descriptor instead.
func (*Reclaimed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{18}
}

func (x *Reclaimed) GetChannel() *ChannelRecord {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *Reclaimed) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

type Authenticate_Password struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticate_Password) Reset() {
	*x = Authenticate_Password{}
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticate_Password) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticate_Password) ProtoMessage() {}

func (x *Authenticate_Password) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_operations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticate_Password.ProtoReflect.Descriptor instead.
func (*Authenticate_Password) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_operations_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Authenticate_Password) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Authenticate_Password) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_yoke_interface_v1_operations_proto protoreflect.FileDescriptor

const file_yoke_interface_v1_operations_proto_rawDesc = "" +
	"\n" +
	"\"yoke/interface/v1/operations.proto\x12\x11yoke.interface.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eyoke/interface/v1/events.proto\x1a\x1fyoke/interface/v1/records.proto\"\xe6\x05\n" +
	"\aRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12E\n" +
	"\fauthenticate\x18\x02 \x01(\v2\x1f.yoke.interface.v1.AuthenticateH\x00R\fauthenticate\x12-\n" +
	"\x04read\x18\x03 \x01(\v2\x17.yoke.interface.v1.ReadH\x00R\x04read\x12<\n" +
	"\tsubscribe\x18\x04 \x01(\v2\x1c.yoke.interface.v1.SubscribeH\x00R\tsubscribe\x126\n" +
	"\aconfirm\x18\x05 \x01(\v2\x1a.yoke.interface.v1.ConfirmH\x00R\aconfirm\x126\n" +
	"\acommand\x18\x06 \x01(\v2\x1a.yoke.interface.v1.CommandH\x00R\acommand\x123\n" +
	"\x05query\x18\a \x01(\v2\x1b.yoke.interface.v1.QuestionH\x00R\x05query\x12B\n" +
	"\fstream_start\x18\b \x01(\v2\x1d.yoke.interface.v1.UnitStreamH\x00R\vstreamStart\x12@\n" +
	"\vstream_stop\x18\t \x01(\v2\x1d.yoke.interface.v1.UnitStreamH\x00R\n" +
	"streamStop\x12J\n" +
	"\x10stream_subscribe\x18\n" +
	" \x01(\v2\x1d.yoke.interface.v1.UnitStreamH\x00R\x0fstreamSubscribe\x12Q\n" +
	"\x12stream_unsubscribe\x18\v \x01(\v2 .yoke.interface.v1.StreamReleaseH\x00R\x11streamUnsubscribe\x126\n" +
	"\areclaim\x18\f \x01(\v2\x1a.yoke.interface.v1.ReclaimH\x00R\areclaimB\v\n" +
	"\toperation\"\xba\x01\n" +
	"\fAuthenticate\x12F\n" +
	"\bpassword\x18\x01 \x01(\v2(.yoke.interface.v1.Authenticate.PasswordH\x00R\bpassword\x12\x16\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x1a<\n" +
	"\bPassword\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secretB\f\n" +
	"\n" +
	"credential\"6\n" +
	"\x04Read\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\">\n" +
	"\tSubscribe\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.yoke.interface.v1.FilterR\x06filter\"I\n" +
	"\aConfirm\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"K\n" +
	"\aCommand\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"L\n" +
	"\bQuestion\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"8\n" +
	"\n" +
	"UnitStream\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\"+\n" +
	"\rStreamRelease\x12\x1a\n" +
	"\bdelivery\x18\x01 \x01(\tR\bdelivery\"\t\n" +
	"\aReclaim\"\xd7\x05\n" +
	"\bResponse\x12F\n" +
	"\fauthenticate\x18\x01 \x01(\v2 .yoke.interface.v1.AuthenticatedH\x00R\fauthenticate\x120\n" +
	"\x04read\x18\x02 \x01(\v2\x1a.yoke.interface.v1.RecordsH\x00R\x04read\x12=\n" +
	"\tsubscribe\x18\x03 \x01(\v2\x1d.yoke.interface.v1.SubscribedH\x00R\tsubscribe\x128\n" +
	"\aconfirm\x18\x04 \x01(\v2\x1c.yoke.interface.v1.ConfirmedH\x00R\aconfirm\x12;\n" +
	"\acommand\x18\x05 \x01(\v2\x1f.yoke.interface.v1.AcknowledgedH\x00R\acommand\x123\n" +
	"\x05query\x18\x06 \x01(\v2\x1b.yoke.interface.v1.AnsweredH\x00R\x05query\x12D\n" +
	"\fstream_start\x18\a \x01(\v2\x1f.yoke.interface.v1.AcknowledgedH\x00R\vstreamStart\x12B\n" +
	"\vstream_stop\x18\b \x01(\v2\x1f.yoke.interface.v1.AcknowledgedH\x00R\n" +
	"streamStop\x12J\n" +
	"\x10stream_subscribe\x18\t \x01(\v2\x1d.yoke.interface.v1.DeliveringH\x00R\x0fstreamSubscribe\x12L\n" +
	"\x12stream_unsubscribe\x18\n" +
	" \x01(\v2\x1b.yoke.interface.v1.ReleasedH\x00R\x11streamUnsubscribe\x128\n" +
	"\areclaim\x18\v \x01(\v2\x1c.yoke.interface.v1.ReclaimedH\x00R\areclaimB\b\n" +
	"\x06answer\"u\n" +
	"\rAuthenticated\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x124\n" +
	"\aexpires\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aexpires\"\xbf\x01\n" +
	"\n" +
	"Subscribed\x129\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1b.yoke.interface.v1.SnapshotH\x00R\bsnapshot\x120\n" +
	"\x05event\x18\x02 \x01(\v2\x18.yoke.interface.v1.EventH\x00R\x05event\x129\n" +
	"\boverflow\x18\x03 \x01(\v2\x1b.yoke.interface.v1.SnapshotH\x00R\boverflowB\t\n" +
	"\acarries\"\v\n" +
	"\tConfirmed\"\xc5\x01\n" +
	"\fAcknowledged\x12A\n" +
	"\aoutcome\x18\x01 \x01(\x0e2'.yoke.interface.v1.Acknowledged.OutcomeR\aoutcome\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"^\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12\x10\n" +
	"\fOUTCOME_DONE\x10\x02\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x03\"$\n" +
	"\bAnswered\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x9f\x01\n" +
	"\n" +
	"Delivering\x12\x1a\n" +
	"\bdelivery\x18\x01 \x01(\tR\bdelivery\x12\x18\n" +
	"\x06socket\x18\x02 \x01(\tH\x00R\x06socket\x12 \n" +
	"\n" +
	"connection\x18\x03 \x01(\bH\x00R\n" +
	"connection\x12\x14\n" +
	"\x04path\x18\x04 \x01(\tH\x00R\x04path\x12\x18\n" +
	"\aflowing\x18\x05 \x01(\bR\aflowingB\t\n" +
	"\aarrives\"\n" +
	"\n" +
	"\bReleased\"a\n" +
	"\tReclaimed\x12:\n" +
	"\achannel\x18\x01 \x01(\v2 .yoke.interface.v1.ChannelRecordR\achannel\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achangedBBZ@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1b\x06proto3"

var (
	file_yoke_interface_v1_operations_proto_rawDescOnce sync.Once
	file_yoke_interface_v1_operations_proto_rawDescData []byte
)

func file_yoke_interface_v1_operations_proto_rawDescGZIP() []byte {
	file_yoke_interface_v1_operations_proto_rawDescOnce.Do(func() {
		file_yoke_interface_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_operations_proto_rawDesc), len(file_yoke_interface_v1_operations_proto_rawDesc)))
	})
	return file_yoke_interface_v1_operations_proto_rawDescData
}

var file_yoke_interface_v1_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_interface_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_yoke_interface_v1_operations_proto_goTypes = []any{
	(Acknowledged_Outcome)(0),     // 0: yoke.interface.v1.Acknowledged.Outcome
	(*Request)(nil),               // 1: yoke.interface.v1.Request
	(*Authenticate)(nil),          // 2: yoke.interface.v1.Authenticate
	(*Read)(nil),                  // 3: yoke.interface.v1.Read
	(*Subscribe)(nil),             // 4: yoke.interface.v1.Subscribe
	(*Confirm)(nil),               // 5: yoke.interface.v1.Confirm
	(*Command)(nil),               // 6: yoke.interface.v1.Command
	(*Question)(nil),              // 7: yoke.interface.v1.Question
	(*UnitStream)(nil),            // 8: yoke.interface.v1.UnitStream
	(*StreamRelease)(nil),         // 9: yoke.interface.v1.StreamRelease
	(*Reclaim)(nil),               // 10: yoke.interface.v1.Reclaim
	(*Response)(nil),              // 11: yoke.interface.v1.Response
	(*Authenticated)(nil),         // 12: yoke.interface.v1.Authenticated
	(*Subscribed)(nil),            // 13: yoke.interface.v1.Subscribed
	(*Confirmed)(nil),             // 14: yoke.interface.v1.Confirmed
	(*Acknowledged)(nil),          // 15: yoke.interface.v1.Acknowledged
	(*Answered)(nil),              // 16: yoke.interface.v1.Answered
	(*Delivering)(nil),            // 17: yoke.interface.v1.Delivering
	(*Released)(nil),              // 18: yoke.interface.v1.Released
	(*Reclaimed)(nil),             // 19: yoke.interface.v1.Reclaimed
	(*Authenticate_Password)(nil), // 20: yoke.interface.v1.Authenticate.Password
	(*Filter)(nil),                // 21: yoke.interface.v1.Filter
	(*Records)(nil),               // 22: yoke.interface.v1.Records
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
	(*Snapshot)(nil),              // 24: yoke.interface.v1.Snapshot
	(*Event)(nil),                 // 25: yoke.interface.v1.Event
	(*ChannelRecord)(nil),         // 26: yoke.interface.v1.ChannelRecord
}
var file_yoke_interface_v1_operations_proto_depIdxs = []int32{
	2,  // 0: yoke.interface.v1.Request.authenticate:type_name -> yoke.interface.v1.Authenticate
	3,  // 1: yoke.interface.v1.Request.read:type_name -> yoke.interface.v1.Read
	4,  // 2: yoke.interface.v1.Request.subscribe:type_name -> yoke.interface.v1.Subscribe
	5,  // 3: yoke.interface.v1.Request.confirm:type_name -> yoke.interface.v1.Confirm
	6,  // 4: yoke.interface.v1.Request.command:type_name -> yoke.interface.v1.Command
	7,  // 5: yoke.interface.v1.Request.query:type_name -> yoke.interface.v1.Question
	8,  // 6: yoke.interface.v1.Request.stream_start:type_name -> yoke.interface.v1.UnitStream
	8,  // 7: yoke.interface.v1.Request.stream_stop:type_name -> yoke.interface.v1.UnitStream
	8,  // 8: yoke.interface.v1.Request.stream_subscribe:type_name -> yoke.interface.v1.UnitStream
	9,  // 9: yoke.interface.v1.Request.stream_unsubscribe:type_name -> yoke.interface.v1.StreamRelease
	10, // 10: yoke.interface.v1.Request.reclaim:type_name -> yoke.interface.v1.Reclaim
	20, // 11: yoke.interface.v1.Authenticate.password:type_name -> yoke.interface.v1.Authenticate.Password
	21, // 12: yoke.interface.v1.Subscribe.filter:type_name -> yoke.interface.v1.Filter
	12, // 13: yoke.interface.v1.Response.authenticate:type_name -> yoke.interface.v1.Authenticated
	22, // 14: yoke.interface.v1.Response.read:type_name -> yoke.interface.v1.Records
	13, // 15: yoke.interface.v1.Response.subscribe:type_name -> yoke.interface.v1.Subscribed
	14, // 16: yoke.interface.v1.Response.confirm:type_name -> yoke.interface.v1.Confirmed
	15, // 17: yoke.interface.v1.Response.command:type_name -> yoke.interface.v1.Acknowledged
	16, // 18: yoke.interface.v1.Response.query:type_name -> yoke.interface.v1.Answered
	15, // 19: yoke.interface.v1.Response.stream_start:type_name -> yoke.interface.v1.Acknowledged
	15, // 20: yoke.interface.v1.Response.stream_stop:type_name -> yoke.interface.v1.Acknowledged
	17, // 21: yoke.interface.v1.Response.stream_subscribe:type_name -> yoke.interface.v1.Delivering
	18, // 22: yoke.interface.v1.Response.stream_unsubscribe:type_name -> yoke.interface.v1.Released
	19, // 23: yoke.interface.v1.Response.reclaim:type_name -> yoke.interface.v1.Reclaimed
	23, // 24: yoke.interface.v1.Authenticated.expires:type_name -> google.protobuf.Timestamp
	24, // 25: yoke.interface.v1.Subscribed.snapshot:type_name -> yoke.interface.v1.Snapshot
	25, // 26: yoke.interface.v1.Subscribed.event:type_name -> yoke.interface.v1.Event
	24, // 27: yoke.interface.v1.Subscribed.overflow:type_name -> yoke.interface.v1.Snapshot
	0,  // 28: yoke.interface.v1.Acknowledged.outcome:type_name -> yoke.interface.v1.Acknowledged.Outcome
	26, // 29: yoke.interface.v1.Reclaimed.channel:type_name -> yoke.interface.v1.ChannelRecord
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_yoke_interface_v1_operations_proto_init() }
func file_yoke_interface_v1_operations_proto_init() {
	if File_yoke_interface_v1_operations_proto != nil {
		return
	}
	file_yoke_interface_v1_events_proto_init()
	file_yoke_interface_v1_records_proto_init()
	file_yoke_interface_v1_operations_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_Authenticate)(nil),
		(*Request_Read)(nil),
		(*Request_Subscribe)(nil),
		(*Request_Confirm)(nil),
		(*Request_Command)(nil),
		(*Request_Query)(nil),
		(*Request_StreamStart)(nil),
		(*Request_StreamStop)(nil),
		(*Request_StreamSubscribe)(nil),
		(*Request_StreamUnsubscribe)(nil),
		(*Request_Reclaim)(nil),
	}
	file_yoke_interface_v1_operations_proto_msgTypes[1].OneofWrappers = []any{
		(*Authenticate_Password_)(nil),
		(*Authenticate_Token)(nil),
	}
	file_yoke_interface_v1_operations_proto_msgTypes[10].OneofWrappers = []any{
		(*Response_Authenticate)(nil),
		(*Response_Read)(nil),
		(*Response_Subscribe)(nil),
		(*Response_Confirm)(nil),
		(*Response_Command)(nil),
		(*Response_Query)(nil),
		(*Response_StreamStart)(nil),
		(*Response_StreamStop)(nil),
		(*Response_StreamSubscribe)(nil),
		(*Response_StreamUnsubscribe)(nil),
		(*Response_Reclaim)(nil),
	}
	file_yoke_interface_v1_operations_proto_msgTypes[12].OneofWrappers = []any{
		(*Subscribed_Snapshot)(nil),
		(*Subscribed_Event)(nil),
		(*Subscribed_Overflow)(nil),
	}
	file_yoke_interface_v1_operations_proto_msgTypes[16].OneofWrappers = []any{
		(*Delivering_Socket)(nil),
		(*Delivering_Connection)(nil),
		(*Delivering_Path)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_operations_proto_rawDesc), len(file_yoke_interface_v1_operations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_interface_v1_operations_proto_goTypes,
		DependencyIndexes: file_yoke_interface_v1_operations_proto_depIdxs,
		EnumInfos:         file_yoke_interface_v1_operations_proto_enumTypes,
		MessageInfos:      file_yoke_interface_v1_operations_proto_msgTypes,
	}.Build()
	File_yoke_interface_v1_operations_proto = out.File
	file_yoke_interface_v1_operations_proto_goTypes = nil
	file_yoke_interface_v1_operations_proto_depIdxs = nil
}
