// The one record the opening picture, a read and a subscription's snapshot are all made of, over the
// three subject kinds a channel observes. Every field is fixed for the life of the instance or maintained
// by a level.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/interface/v1/records.proto

package interfacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Subject:
	//
	//	*Record_Instance
	//	*Record_Unit
	//	*Record_Channel
	Subject       isRecord_Subject `protobuf_oneof:"subject"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetSubject() isRecord_Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *Record) GetInstance() *InstanceRecord {
	if x != nil {
		if x, ok := x.Subject.(*Record_Instance); ok {
			return x.Instance
		}
	}
	return nil
}

func (x *Record) GetUnit() *UnitRecord {
	if x != nil {
		if x, ok := x.Subject.(*Record_Unit); ok {
			return x.Unit
		}
	}
	return nil
}

func (x *Record) GetChannel() *ChannelRecord {
	if x != nil {
		if x, ok := x.Subject.(*Record_Channel); ok {
			return x.Channel
		}
	}
	return nil
}

type isRecord_Subject interface {
	isRecord_Subject()
}

type Record_Instance struct {
	Instance *InstanceRecord `protobuf:"bytes,1,opt,name=instance,proto3,oneof"`
}

type Record_Unit struct {
	Unit *UnitRecord `protobuf:"bytes,2,opt,name=unit,proto3,oneof"`
}

type Record_Channel struct {
	Channel *ChannelRecord `protobuf:"bytes,3,opt,name=channel,proto3,oneof"`
}

func (*Record_Instance) isRecord_Subject() {}

func (*Record_Unit) isRecord_Subject() {}

func (*Record_Channel) isRecord_Subject() {}

type InstanceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Stopping      bool                   `protobuf:"varint,2,opt,name=stopping,proto3" json:"stopping,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceRecord) Reset() {
	*x = InstanceRecord{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceRecord) ProtoMessage() {}

func (x *InstanceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceRecord.ProtoReflect.Descriptor instead.
func (*InstanceRecord) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{1}
}

func (x *InstanceRecord) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *InstanceRecord) GetStopping() bool {
	if x != nil {
		return x.Stopping
	}
	return false
}

func (x *InstanceRecord) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

type UnitRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Declared      *UnitRecord_Declared   `protobuf:"bytes,1,opt,name=declared,proto3" json:"declared,omitempty"`
	Observed      *UnitRecord_Observed   `protobuf:"bytes,2,opt,name=observed,proto3" json:"observed,omitempty"`
	Addressed     *UnitRecord_Addressed  `protobuf:"bytes,3,opt,name=addressed,proto3" json:"addressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitRecord) Reset() {
	*x = UnitRecord{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitRecord) ProtoMessage() {}

func (x *UnitRecord) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitRecord.ProtoReflect.Descriptor instead.
func (*UnitRecord) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{2}
}

func (x *UnitRecord) GetDeclared() *UnitRecord_Declared {
	if x != nil {
		return x.Declared
	}
	return nil
}

func (x *UnitRecord) GetObserved() *UnitRecord_Observed {
	if x != nil {
		return x.Observed
	}
	return nil
}

func (x *UnitRecord) GetAddressed() *UnitRecord_Addressed {
	if x != nil {
		return x.Addressed
	}
	return nil
}

// A unit's own account of how well it is.
type Condition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         uint32                 `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Condition) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Condition) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// The channel the record is read on: a channel observes only its own.
type ChannelRecord struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Declared      *ChannelRecord_Declared `protobuf:"bytes,1,opt,name=declared,proto3" json:"declared,omitempty"`
	Observed      *ChannelRecord_Observed `protobuf:"bytes,2,opt,name=observed,proto3" json:"observed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRecord) Reset() {
	*x = ChannelRecord{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRecord) ProtoMessage() {}

func (x *ChannelRecord) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRecord.ProtoReflect.Descriptor instead.
func (*ChannelRecord) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{4}
}

func (x *ChannelRecord) GetDeclared() *ChannelRecord_Declared {
	if x != nil {
		return x.Declared
	}
	return nil
}

func (x *ChannelRecord) GetObserved() *ChannelRecord_Observed {
	if x != nil {
		return x.Observed
	}
	return nil
}

// The current value of every level a filter selects, taken at a sequence: the stream that follows
// begins at the next.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            uint64                 `protobuf:"varint,1,opt,name=at,proto3" json:"at,omitempty"`
	Records       []*Record              `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetAt() uint64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *Snapshot) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// A read's answer: the snapshot's records, and nothing follows.
type Records struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Records) Reset() {
	*x = Records{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Records) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Records) ProtoMessage() {}

func (x *Records) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Records.ProtoReflect.Descriptor instead.
func (*Records) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{6}
}

func (x *Records) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type UnitRecord_Declared struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Identity string                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// plugin, oneshot or interface.
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitRecord_Declared) Reset() {
	*x = UnitRecord_Declared{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitRecord_Declared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitRecord_Declared) ProtoMessage() {}

func (x *UnitRecord_Declared) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitRecord_Declared.ProtoReflect.Descriptor instead.
func (*UnitRecord_Declared) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{2, 0}
}

func (x *UnitRecord_Declared) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *UnitRecord_Declared) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type UnitRecord_Observed struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	State       string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Incarnation uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// The moment of the last transition.
	Since *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`
	// None where the unit has never reported.
	Condition *Condition `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	// The streams currently activated.
	Streams       []string `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitRecord_Observed) Reset() {
	*x = UnitRecord_Observed{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitRecord_Observed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitRecord_Observed) ProtoMessage() {}

func (x *UnitRecord_Observed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitRecord_Observed.ProtoReflect.Descriptor instead.
func (*UnitRecord_Observed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{2, 1}
}

func (x *UnitRecord_Observed) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *UnitRecord_Observed) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *UnitRecord_Observed) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *UnitRecord_Observed) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *UnitRecord_Observed) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

// What a channel may address on a Plugin unit: the objects its plugin was granted. Empty on any other.
type UnitRecord_Addressed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []string               `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	Commands      []string               `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Queries       []string               `protobuf:"bytes,3,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitRecord_Addressed) Reset() {
	*x = UnitRecord_Addressed{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitRecord_Addressed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitRecord_Addressed) ProtoMessage() {}

func (x *UnitRecord_Addressed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitRecord_Addressed.ProtoReflect.Descriptor instead.
func (*UnitRecord_Addressed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{2, 2}
}

func (x *UnitRecord_Addressed) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *UnitRecord_Addressed) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *UnitRecord_Addressed) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type ChannelRecord_Declared struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// local or http+ws.
	Projection string `protobuf:"bytes,2,opt,name=projection,proto3" json:"projection,omitempty"`
	// local-socket, loopback or routable.
	AddressClass string `protobuf:"bytes,3,opt,name=address_class,json=addressClass,proto3" json:"address_class,omitempty"`
	// single or multiple.
	Clients       string `protobuf:"bytes,4,opt,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRecord_Declared) Reset() {
	*x = ChannelRecord_Declared{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRecord_Declared) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRecord_Declared) ProtoMessage() {}

func (x *ChannelRecord_Declared) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRecord_Declared.ProtoReflect.Descriptor instead.
func (*ChannelRecord_Declared) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ChannelRecord_Declared) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelRecord_Declared) GetProjection() string {
	if x != nil {
		return x.Projection
	}
	return ""
}

func (x *ChannelRecord_Declared) GetAddressClass() string {
	if x != nil {
		return x.AddressClass
	}
	return ""
}

func (x *ChannelRecord_Declared) GetClients() string {
	if x != nil {
		return x.Clients
	}
	return ""
}

type ChannelRecord_Observed struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Attached bool                   `protobuf:"varint,1,opt,name=attached,proto3" json:"attached,omitempty"`
	// The client the channel established; unestablished where its class establishes none.
	Client    string `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
	Suspended bool   `protobuf:"varint,3,opt,name=suspended,proto3" json:"suspended,omitempty"`
	// read-only or dark, while suspended.
	Grade string `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"`
	// The channel that prevails, while suspended.
	By string `protobuf:"bytes,5,opt,name=by,proto3" json:"by,omitempty"`
	// Why it was suspended.
	Reason        string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelRecord_Observed) Reset() {
	*x = ChannelRecord_Observed{}
	mi := &file_yoke_interface_v1_records_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelRecord_Observed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelRecord_Observed) ProtoMessage() {}

func (x *ChannelRecord_Observed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_interface_v1_records_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelRecord_Observed.ProtoReflect.Descriptor instead.
func (*ChannelRecord_Observed) Descriptor() ([]byte, []int) {
	return file_yoke_interface_v1_records_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ChannelRecord_Observed) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *ChannelRecord_Observed) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *ChannelRecord_Observed) GetSuspended() bool {
	if x != nil {
		return x.Suspended
	}
	return false
}

func (x *ChannelRecord_Observed) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *ChannelRecord_Observed) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *ChannelRecord_Observed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_yoke_interface_v1_records_proto protoreflect.FileDescriptor

const file_yoke_interface_v1_records_proto_rawDesc = "" +
	"\n" +
	"\x1fyoke/interface/v1/records.proto\x12\x11yoke.interface.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n" +
	"\x06Record\x12?\n" +
	"\binstance\x18\x01 \x01(\v2!.yoke.interface.v1.InstanceRecordH\x00R\binstance\x123\n" +
	"\x04unit\x18\x02 \x01(\v2\x1d.yoke.interface.v1.UnitRecordH\x00R\x04unit\x12<\n" +
	"\achannel\x18\x03 \x01(\v2 .yoke.interface.v1.ChannelRecordH\x00R\achannelB\t\n" +
	"\asubject\"t\n" +
	"\x0eInstanceRecord\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x1a\n" +
	"\bstopping\x18\x02 \x01(\bR\bstopping\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xc1\x04\n" +
	"\n" +
	"UnitRecord\x12B\n" +
	"\bdeclared\x18\x01 \x01(\v2&.yoke.interface.v1.UnitRecord.DeclaredR\bdeclared\x12B\n" +
	"\bobserved\x18\x02 \x01(\v2&.yoke.interface.v1.UnitRecord.ObservedR\bobserved\x12E\n" +
	"\taddressed\x18\x03 \x01(\v2'.yoke.interface.v1.UnitRecord.AddressedR\taddressed\x1a:\n" +
	"\bDeclared\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\tR\bidentity\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x1a\xca\x01\n" +
	"\bObserved\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x12:\n" +
	"\tcondition\x18\x04 \x01(\v2\x1c.yoke.interface.v1.ConditionR\tcondition\x12\x18\n" +
	"\astreams\x18\x05 \x03(\tR\astreams\x1a[\n" +
	"\tAddressed\x12\x18\n" +
	"\astreams\x18\x01 \x03(\tR\astreams\x12\x1a\n" +
	"\bcommands\x18\x02 \x03(\tR\bcommands\x12\x18\n" +
	"\aqueries\x18\x03 \x03(\tR\aqueries\"g\n" +
	"\tCondition\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\rR\x05grade\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x120\n" +
	"\x05since\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\"\xb9\x03\n" +
	"\rChannelRecord\x12E\n" +
	"\bdeclared\x18\x01 \x01(\v2).yoke.interface.v1.ChannelRecord.DeclaredR\bdeclared\x12E\n" +
	"\bobserved\x18\x02 \x01(\v2).yoke.interface.v1.ChannelRecord.ObservedR\bobserved\x1a}\n" +
	"\bDeclared\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"projection\x18\x02 \x01(\tR\n" +
	"projection\x12#\n" +
	"\raddress_class\x18\x03 \x01(\tR\faddressClass\x12\x18\n" +
	"\aclients\x18\x04 \x01(\tR\aclients\x1a\x9a\x01\n" +
	"\bObserved\x12\x1a\n" +
	"\battached\x18\x01 \x01(\bR\battached\x12\x16\n" +
	"\x06client\x18\x02 \x01(\tR\x06client\x12\x1c\n" +
	"\tsuspended\x18\x03 \x01(\bR\tsuspended\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\tR\x05grade\x12\x0e\n" +
	"\x02by\x18\x05 \x01(\tR\x02by\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"O\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02at\x18\x01 \x01(\x04R\x02at\x123\n" +
	"\arecords\x18\x02 \x03(\v2\x19.yoke.interface.v1.RecordR\arecords\">\n" +
	"\aRecords\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.yoke.interface.v1.RecordR\arecordsBBZ@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1b\x06proto3"

var (
	file_yoke_interface_v1_records_proto_rawDescOnce sync.Once
	file_yoke_interface_v1_records_proto_rawDescData []byte
)

func file_yoke_interface_v1_records_proto_rawDescGZIP() []byte {
	file_yoke_interface_v1_records_proto_rawDescOnce.Do(func() {
		file_yoke_interface_v1_records_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_records_proto_rawDesc), len(file_yoke_interface_v1_records_proto_rawDesc)))
	})
	return file_yoke_interface_v1_records_proto_rawDescData
}

var file_yoke_interface_v1_records_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_yoke_interface_v1_records_proto_goTypes = []any{
	(*Record)(nil),                 // 0: yoke.interface.v1.Record
	(*InstanceRecord)(nil),         // 1: yoke.interface.v1.InstanceRecord
	(*UnitRecord)(nil),             // 2: yoke.interface.v1.UnitRecord
	(*Condition)(nil),              // 3: yoke.interface.v1.Condition
	(*ChannelRecord)(nil),          // 4: yoke.interface.v1.ChannelRecord
	(*Snapshot)(nil),               // 5: yoke.interface.v1.Snapshot
	(*Records)(nil),                // 6: yoke.interface.v1.Records
	(*UnitRecord_Declared)(nil),    // 7: yoke.interface.v1.UnitRecord.Declared
	(*UnitRecord_Observed)(nil),    // 8: yoke.interface.v1.UnitRecord.Observed
	(*UnitRecord_Addressed)(nil),   // 9: yoke.interface.v1.UnitRecord.Addressed
	(*ChannelRecord_Declared)(nil), // 10: yoke.interface.v1.ChannelRecord.Declared
	(*ChannelRecord_Observed)(nil), // 11: yoke.interface.v1.ChannelRecord.Observed
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_yoke_interface_v1_records_proto_depIdxs = []int32{
	1,  // 0: yoke.interface.v1.Record.instance:type_name -> yoke.interface.v1.InstanceRecord
	2,  // 1: yoke.interface.v1.Record.unit:type_name -> yoke.interface.v1.UnitRecord
	4,  // 2: yoke.interface.v1.Record.channel:type_name -> yoke.interface.v1.ChannelRecord
	12, // 3: yoke.interface.v1.InstanceRecord.since:type_name -> google.protobuf.Timestamp
	7,  // 4: yoke.interface.v1.UnitRecord.declared:type_name -> yoke.interface.v1.UnitRecord.Declared
	8,  // 5: yoke.interface.v1.UnitRecord.observed:type_name -> yoke.interface.v1.UnitRecord.Observed
	9,  // 6: yoke.interface.v1.UnitRecord.addressed:type_name -> yoke.interface.v1.UnitRecord.Addressed
	12, // 7: yoke.interface.v1.Condition.since:type_name -> google.protobuf.Timestamp
	10, // 8: yoke.interface.v1.ChannelRecord.declared:type_name -> yoke.interface.v1.ChannelRecord.Declared
	11, // 9: yoke.interface.v1.ChannelRecord.observed:type_name -> yoke.interface.v1.ChannelRecord.Observed
	0,  // 10: yoke.interface.v1.Snapshot.records:type_name -> yoke.interface.v1.Record
	0,  // 11: yoke.interface.v1.Records.records:type_name -> yoke.interface.v1.Record
	12, // 12: yoke.interface.v1.UnitRecord.Observed.since:type_name -> google.protobuf.Timestamp
	3,  // 13: yoke.interface.v1.UnitRecord.Observed.condition:type_name -> yoke.interface.v1.Condition
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_yoke_interface_v1_records_proto_init() }
func file_yoke_interface_v1_records_proto_init() {
	if File_yoke_interface_v1_records_proto != nil {
		return
	}
	file_yoke_interface_v1_records_proto_msgTypes[0].OneofWrappers = []any{
		(*Record_Instance)(nil),
		(*Record_Unit)(nil),
		(*Record_Channel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_interface_v1_records_proto_rawDesc), len(file_yoke_interface_v1_records_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_interface_v1_records_proto_goTypes,
		DependencyIndexes: file_yoke_interface_v1_records_proto_depIdxs,
		MessageInfos:      file_yoke_interface_v1_records_proto_msgTypes,
	}.Build()
	File_yoke_interface_v1_records_proto = out.File
	file_yoke_interface_v1_records_proto_goTypes = nil
	file_yoke_interface_v1_records_proto_depIdxs = nil
}
