# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/interface/v1/interface.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/interface/v1/interface.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yoke.interface.v1 import codes_pb2 as yoke_dot_interface_dot_v1_dot_codes__pb2
from yoke.interface.v1 import events_pb2 as yoke_dot_interface_dot_v1_dot_events__pb2
from yoke.interface.v1 import operations_pb2 as yoke_dot_interface_dot_v1_dot_operations__pb2
from yoke.interface.v1 import records_pb2 as yoke_dot_interface_dot_v1_dot_records__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!yoke/interface/v1/interface.proto\x12\x11yoke.interface.v1\x1a\x1dyoke/interface/v1/codes.proto\x1a\x1eyoke/interface/v1/events.proto\x1a\"yoke/interface/v1/operations.proto\x1a\x1fyoke/interface/v1/records.proto\"\x82\x01\n\x0b\x43lientFrame\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12-\n\x07request\x18\x02 \x01(\x0b\x32\x1a.yoke.interface.v1.RequestH\x00\x12+\n\x06\x63\x61ncel\x18\x03 \x01(\x0b\x32\x19.yoke.interface.v1.CancelH\x00\x42\t\n\x07\x63\x61rries\"\x08\n\x06\x43\x61ncel\"\xc8\x02\n\tCoreFrame\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12-\n\x07opening\x18\x02 \x01(\x0b\x32\x1a.yoke.interface.v1.OpeningH\x00\x12-\n\x06\x61nswer\x18\x03 \x01(\x0b\x32\x1b.yoke.interface.v1.ResponseH\x00\x12)\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x18.yoke.interface.v1.EventH\x00\x12\x35\n\x08\x64\x65livery\x18\x05 \x01(\x0b\x32!.yoke.interface.v1.StreamDeliveryH\x00\x12-\n\x07refusal\x18\x06 \x01(\x0b\x32\x1a.yoke.interface.v1.RefusalH\x00\x12\x33\n\ncompletion\x18\x07 \x01(\x0b\x32\x1d.yoke.interface.v1.CompletionH\x00\x42\t\n\x07\x63\x61rries\"^\n\x07Opening\x12,\n\x07picture\x18\x01 \x01(\x0b\x32\x1b.yoke.interface.v1.Snapshot\x12\x14\n\x0csubscription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\"V\n\x0eStreamDelivery\x12\x10\n\x08\x64\x65livery\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x04\x12\x0f\n\x07sent_at\x18\x03 \x01(\x04\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\"p\n\nCompletion\x12,\n\x02\x62y\x18\x01 \x01(\x0e\x32 .yoke.interface.v1.Completion.By\"4\n\x02\x42y\x12\x12\n\x0e\x42Y_UNSPECIFIED\x10\x00\x12\r\n\tBY_CALLER\x10\x01\x12\x0b\n\x07\x42Y_CORE\x10\x02\x32W\n\tInterface\x12J\n\x06\x41ttach\x12\x1e.yoke.interface.v1.ClientFrame\x1a\x1c.yoke.interface.v1.CoreFrame(\x01\x30\x01\x42\x42Z@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.interface.v1.interface_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/yoke-project/yoke/proto/yoke/interface/v1;interfacev1'
  _globals['_CLIENTFRAME']._serialized_start=189
  _globals['_CLIENTFRAME']._serialized_end=319
  _globals['_CANCEL']._serialized_start=321
  _globals['_CANCEL']._serialized_end=329
  _globals['_COREFRAME']._serialized_start=332
  _globals['_COREFRAME']._serialized_end=660
  _globals['_OPENING']._serialized_start=662
  _globals['_OPENING']._serialized_end=756
  _globals['_STREAMDELIVERY']._serialized_start=758
  _globals['_STREAMDELIVERY']._serialized_end=844
  _globals['_COMPLETION']._serialized_start=846
  _globals['_COMPLETION']._serialized_end=958
  _globals['_COMPLETION_BY']._serialized_start=906
  _globals['_COMPLETION_BY']._serialized_end=958
  _globals['_INTERFACE']._serialized_start=960
  _globals['_INTERFACE']._serialized_end=1047
# @@protoc_insertion_point(module_scope)
