// This surface's error codes. On the wire a code is its dotted name, which grows under one grammar across
// every surface; this enum is where every party reads the names from, each stated in its `code` option,
// and a code's meaning never changes under its name.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/administrative/v1/codes.proto

package administrativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_UNSPECIFIED Code = 0
	// The request does not decode, or a required field is absent.
	Code_CODE_OPERATION_MALFORMED Code = 1
	// It names an operation this Core does not implement.
	Code_CODE_OPERATION_UNKNOWN Code = 2
	// The contract version is absent, or this Core does not support it.
	Code_CODE_COMPAT_UNSUPPORTED Code = 3
	// Nothing of that kind bears that identity.
	Code_CODE_SUBJECT_UNKNOWN Code = 4
	// The operation does not take a subject of that kind.
	Code_CODE_SUBJECT_WRONG_KIND Code = 5
	// A grant names a capability the plugin's Manifest does not declare.
	Code_CODE_CAPABILITY_UNDECLARED Code = 6
	// The stream is not one that unit's Plugin declared.
	Code_CODE_STREAM_UNDECLARED Code = 7
	// It names something declared but not authorised.
	Code_CODE_SCOPE_WITHHELD Code = 8
	// The operation needs a running unit and this one is not.
	Code_CODE_UNIT_NOT_RUNNING Code = 9
	// The unit holds no Session, so nothing can be issued on one.
	Code_CODE_UNIT_NO_SESSION Code = 10
	// The wait elapsed with no acknowledgement or answer.
	Code_CODE_UNIT_UNANSWERED Code = 11
	// A limit is not a positive integer.
	Code_CODE_RETENTION_INVALID Code = 12
	// An orderly stop is in progress and the operation would change something.
	Code_CODE_INSTANCE_STOPPING Code = 13
	// The container engine is not currently observable: a fault, not a denial.
	Code_CODE_BACKEND_UNAVAILABLE Code = 14
	// A write to the Registry or the log store did not succeed: a fault, not a denial.
	Code_CODE_STORE_UNAVAILABLE Code = 15
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "CODE_UNSPECIFIED",
		1:  "CODE_OPERATION_MALFORMED",
		2:  "CODE_OPERATION_UNKNOWN",
		3:  "CODE_COMPAT_UNSUPPORTED",
		4:  "CODE_SUBJECT_UNKNOWN",
		5:  "CODE_SUBJECT_WRONG_KIND",
		6:  "CODE_CAPABILITY_UNDECLARED",
		7:  "CODE_STREAM_UNDECLARED",
		8:  "CODE_SCOPE_WITHHELD",
		9:  "CODE_UNIT_NOT_RUNNING",
		10: "CODE_UNIT_NO_SESSION",
		11: "CODE_UNIT_UNANSWERED",
		12: "CODE_RETENTION_INVALID",
		13: "CODE_INSTANCE_STOPPING",
		14: "CODE_BACKEND_UNAVAILABLE",
		15: "CODE_STORE_UNAVAILABLE",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED":           0,
		"CODE_OPERATION_MALFORMED":   1,
		"CODE_OPERATION_UNKNOWN":     2,
		"CODE_COMPAT_UNSUPPORTED":    3,
		"CODE_SUBJECT_UNKNOWN":       4,
		"CODE_SUBJECT_WRONG_KIND":    5,
		"CODE_CAPABILITY_UNDECLARED": 6,
		"CODE_STREAM_UNDECLARED":     7,
		"CODE_SCOPE_WITHHELD":        8,
		"CODE_UNIT_NOT_RUNNING":      9,
		"CODE_UNIT_NO_SESSION":       10,
		"CODE_UNIT_UNANSWERED":       11,
		"CODE_RETENTION_INVALID":     12,
		"CODE_INSTANCE_STOPPING":     13,
		"CODE_BACKEND_UNAVAILABLE":   14,
		"CODE_STORE_UNAVAILABLE":     15,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_administrative_v1_codes_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_yoke_administrative_v1_codes_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_codes_proto_rawDescGZIP(), []int{0}
}

// A refusal: a code, a message for a person, and what it names in a detail typed per code.
type Refusal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One of Code's names.
	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Detail:
	//
	//	*Refusal_Subject
	//	*Refusal_Item
	Detail        isRefusal_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Refusal) Reset() {
	*x = Refusal{}
	mi := &file_yoke_administrative_v1_codes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Refusal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Refusal) ProtoMessage() {}

func (x *Refusal) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_codes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Refusal.ProtoReflect.Descriptor instead.
func (*Refusal) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_codes_proto_rawDescGZIP(), []int{0}
}

func (x *Refusal) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Refusal) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Refusal) GetDetail() isRefusal_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Refusal) GetSubject() *Subject {
	if x != nil {
		if x, ok := x.Detail.(*Refusal_Subject); ok {
			return x.Subject
		}
	}
	return nil
}

func (x *Refusal) GetItem() string {
	if x != nil {
		if x, ok := x.Detail.(*Refusal_Item); ok {
			return x.Item
		}
	}
	return ""
}

type isRefusal_Detail interface {
	isRefusal_Detail()
}

type Refusal_Subject struct {
	// The subject named: for subject.unknown and subject.wrong_kind, and for the refusals about a unit.
	Subject *Subject `protobuf:"bytes,3,opt,name=subject,proto3,oneof"`
}

type Refusal_Item struct {
	// The item withheld or undeclared: a capability, or a stream.
	Item string `protobuf:"bytes,4,opt,name=item,proto3,oneof"`
}

func (*Refusal_Subject) isRefusal_Detail() {}

func (*Refusal_Item) isRefusal_Detail() {}

// What an operation, a record or an event is about: a kind and an identity, and a unit's life where
// one is named.
type Subject struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance, unit, plugin, channel, document or connection.
	Kind     string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// A unit's life; zero where none is named.
	Incarnation   uint64 `protobuf:"varint,3,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_yoke_administrative_v1_codes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_codes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_codes_proto_rawDescGZIP(), []int{1}
}

func (x *Subject) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Subject) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Subject) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

var file_yoke_administrative_v1_codes_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "yoke.administrative.v1.code",
		Tag:           "bytes,50001,opt,name=code",
		Filename:      "yoke/administrative/v1/codes.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// The code's dotted name, as it travels.
	//
	// optional string code = 50001;
	E_Code = &file_yoke_administrative_v1_codes_proto_extTypes[0]
)

var File_yoke_administrative_v1_codes_proto protoreflect.FileDescriptor

const file_yoke_administrative_v1_codes_proto_rawDesc = "" +
	"\n" +
	"\"yoke/administrative/v1/codes.proto\x12\x16yoke.administrative.v1\x1a google/protobuf/descriptor.proto\"\x94\x01\n" +
	"\aRefusal\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\asubject\x18\x03 \x01(\v2\x1f.yoke.administrative.v1.SubjectH\x00R\asubject\x12\x14\n" +
	"\x04item\x18\x04 \x01(\tH\x00R\x04itemB\b\n" +
	"\x06detail\"[\n" +
	"\aSubject\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\x12 \n" +
	"\vincarnation\x18\x03 \x01(\x04R\vincarnation*\x99\x06\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x125\n" +
	"\x18CODE_OPERATION_MALFORMED\x10\x01\x1a\x17\x8a\xb5\x18\x13operation.malformed\x121\n" +
	"\x16CODE_OPERATION_UNKNOWN\x10\x02\x1a\x15\x8a\xb5\x18\x11operation.unknown\x123\n" +
	"\x17CODE_COMPAT_UNSUPPORTED\x10\x03\x1a\x16\x8a\xb5\x18\x12compat.unsupported\x12-\n" +
	"\x14CODE_SUBJECT_UNKNOWN\x10\x04\x1a\x13\x8a\xb5\x18\x0fsubject.unknown\x123\n" +
	"\x17CODE_SUBJECT_WRONG_KIND\x10\x05\x1a\x16\x8a\xb5\x18\x12subject.wrong_kind\x129\n" +
	"\x1aCODE_CAPABILITY_UNDECLARED\x10\x06\x1a\x19\x8a\xb5\x18\x15capability.undeclared\x121\n" +
	"\x16CODE_STREAM_UNDECLARED\x10\a\x1a\x15\x8a\xb5\x18\x11stream.undeclared\x12+\n" +
	"\x13CODE_SCOPE_WITHHELD\x10\b\x1a\x12\x8a\xb5\x18\x0escope.withheld\x12/\n" +
	"\x15CODE_UNIT_NOT_RUNNING\x10\t\x1a\x14\x8a\xb5\x18\x10unit.not_running\x12-\n" +
	"\x14CODE_UNIT_NO_SESSION\x10\n" +
	"\x1a\x13\x8a\xb5\x18\x0funit.no_session\x12-\n" +
	"\x14CODE_UNIT_UNANSWERED\x10\v\x1a\x13\x8a\xb5\x18\x0funit.unanswered\x121\n" +
	"\x16CODE_RETENTION_INVALID\x10\f\x1a\x15\x8a\xb5\x18\x11retention.invalid\x121\n" +
	"\x16CODE_INSTANCE_STOPPING\x10\r\x1a\x15\x8a\xb5\x18\x11instance.stopping\x125\n" +
	"\x18CODE_BACKEND_UNAVAILABLE\x10\x0e\x1a\x17\x8a\xb5\x18\x13backend.unavailable\x121\n" +
	"\x16CODE_STORE_UNAVAILABLE\x10\x0f\x1a\x15\x8a\xb5\x18\x11store.unavailable:7\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18ц\x03 \x01(\tR\x04codeBLZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3"

var (
	file_yoke_administrative_v1_codes_proto_rawDescOnce sync.Once
	file_yoke_administrative_v1_codes_proto_rawDescData []byte
)

func file_yoke_administrative_v1_codes_proto_rawDescGZIP() []byte {
	file_yoke_administrative_v1_codes_proto_rawDescOnce.Do(func() {
		file_yoke_administrative_v1_codes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_codes_proto_rawDesc), len(file_yoke_administrative_v1_codes_proto_rawDesc)))
	})
	return file_yoke_administrative_v1_codes_proto_rawDescData
}

var file_yoke_administrative_v1_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_administrative_v1_codes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yoke_administrative_v1_codes_proto_goTypes = []any{
	(Code)(0),                             // 0: yoke.administrative.v1.Code
	(*Refusal)(nil),                       // 1: yoke.administrative.v1.Refusal
	(*Subject)(nil),                       // 2: yoke.administrative.v1.Subject
	(*descriptorpb.EnumValueOptions)(nil), // 3: google.protobuf.EnumValueOptions
}
var file_yoke_administrative_v1_codes_proto_depIdxs = []int32{
	2, // 0: yoke.administrative.v1.Refusal.subject:type_name -> yoke.administrative.v1.Subject
	3, // 1: yoke.administrative.v1.code:extendee -> google.protobuf.EnumValueOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_yoke_administrative_v1_codes_proto_init() }
func file_yoke_administrative_v1_codes_proto_init() {
	if File_yoke_administrative_v1_codes_proto != nil {
		return
	}
	file_yoke_administrative_v1_codes_proto_msgTypes[0].OneofWrappers = []any{
		(*Refusal_Subject)(nil),
		(*Refusal_Item)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_codes_proto_rawDesc), len(file_yoke_administrative_v1_codes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_yoke_administrative_v1_codes_proto_goTypes,
		DependencyIndexes: file_yoke_administrative_v1_codes_proto_depIdxs,
		EnumInfos:         file_yoke_administrative_v1_codes_proto_enumTypes,
		MessageInfos:      file_yoke_administrative_v1_codes_proto_msgTypes,
		ExtensionInfos:    file_yoke_administrative_v1_codes_proto_extTypes,
	}.Build()
	File_yoke_administrative_v1_codes_proto = out.File
	file_yoke_administrative_v1_codes_proto_goTypes = nil
	file_yoke_administrative_v1_codes_proto_depIdxs = nil
}
