// The one operation union: an operation is a member of Request and never of a service, so it is on
// both projections or on neither. Response has one answer per operation, in the same order.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/administrative/v1/operations.proto

package administrativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Changed_Effective int32

const (
	Changed_EFFECTIVE_UNSPECIFIED       Changed_Effective = 0
	Changed_EFFECTIVE_IMMEDIATELY       Changed_Effective = 1
	Changed_EFFECTIVE_AT_NEXT_ADMISSION Changed_Effective = 2
)

// Enum value maps for Changed_Effective.
var (
	Changed_Effective_name = map[int32]string{
		0: "EFFECTIVE_UNSPECIFIED",
		1: "EFFECTIVE_IMMEDIATELY",
		2: "EFFECTIVE_AT_NEXT_ADMISSION",
	}
	Changed_Effective_value = map[string]int32{
		"EFFECTIVE_UNSPECIFIED":       0,
		"EFFECTIVE_IMMEDIATELY":       1,
		"EFFECTIVE_AT_NEXT_ADMISSION": 2,
	}
)

func (x Changed_Effective) Enum() *Changed_Effective {
	p := new(Changed_Effective)
	*p = x
	return p
}

func (x Changed_Effective) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Changed_Effective) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_administrative_v1_operations_proto_enumTypes[0].Descriptor()
}

func (Changed_Effective) Type() protoreflect.EnumType {
	return &file_yoke_administrative_v1_operations_proto_enumTypes[0]
}

func (x Changed_Effective) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Changed_Effective.Descriptor instead.
func (Changed_Effective) EnumDescriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{12, 0}
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The contract's version, checked on every call and on the first frame of a connection.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*Request_PluginEnable
	//	*Request_PluginDisable
	//	*Request_PluginGrant
	//	*Request_PluginWithdraw
	//	*Request_UnitStart
	//	*Request_UnitStop
	//	*Request_UnitRestart
	//	*Request_UnitStreamStart
	//	*Request_UnitStreamStop
	//	*Request_UnitRetentionSet
	//	*Request_UnitRetentionClear
	//	*Request_UnitAsk
	//	*Request_Read
	//	*Request_LogQuery
	//	*Request_LogFollow
	//	*Request_Subscribe
	Operation     isRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Request) GetOperation() isRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *Request) GetPluginEnable() *PluginPolicy {
	if x != nil {
		if x, ok := x.Operation.(*Request_PluginEnable); ok {
			return x.PluginEnable
		}
	}
	return nil
}

func (x *Request) GetPluginDisable() *PluginPolicy {
	if x != nil {
		if x, ok := x.Operation.(*Request_PluginDisable); ok {
			return x.PluginDisable
		}
	}
	return nil
}

func (x *Request) GetPluginGrant() *PluginGrant {
	if x != nil {
		if x, ok := x.Operation.(*Request_PluginGrant); ok {
			return x.PluginGrant
		}
	}
	return nil
}

func (x *Request) GetPluginWithdraw() *PluginGrant {
	if x != nil {
		if x, ok := x.Operation.(*Request_PluginWithdraw); ok {
			return x.PluginWithdraw
		}
	}
	return nil
}

func (x *Request) GetUnitStart() *UnitAct {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitStart); ok {
			return x.UnitStart
		}
	}
	return nil
}

func (x *Request) GetUnitStop() *UnitAct {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitStop); ok {
			return x.UnitStop
		}
	}
	return nil
}

func (x *Request) GetUnitRestart() *UnitAct {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitRestart); ok {
			return x.UnitRestart
		}
	}
	return nil
}

func (x *Request) GetUnitStreamStart() *UnitStream {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitStreamStart); ok {
			return x.UnitStreamStart
		}
	}
	return nil
}

func (x *Request) GetUnitStreamStop() *UnitStream {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitStreamStop); ok {
			return x.UnitStreamStop
		}
	}
	return nil
}

func (x *Request) GetUnitRetentionSet() *UnitRetention {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitRetentionSet); ok {
			return x.UnitRetentionSet
		}
	}
	return nil
}

func (x *Request) GetUnitRetentionClear() *UnitAct {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitRetentionClear); ok {
			return x.UnitRetentionClear
		}
	}
	return nil
}

func (x *Request) GetUnitAsk() *UnitAsk {
	if x != nil {
		if x, ok := x.Operation.(*Request_UnitAsk); ok {
			return x.UnitAsk
		}
	}
	return nil
}

func (x *Request) GetRead() *Read {
	if x != nil {
		if x, ok := x.Operation.(*Request_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Request) GetLogQuery() *LogQuery {
	if x != nil {
		if x, ok := x.Operation.(*Request_LogQuery); ok {
			return x.LogQuery
		}
	}
	return nil
}

func (x *Request) GetLogFollow() *LogFollow {
	if x != nil {
		if x, ok := x.Operation.(*Request_LogFollow); ok {
			return x.LogFollow
		}
	}
	return nil
}

func (x *Request) GetSubscribe() *Subscribe {
	if x != nil {
		if x, ok := x.Operation.(*Request_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

type isRequest_Operation interface {
	isRequest_Operation()
}

type Request_PluginEnable struct {
	// Policy is per plugin.
	PluginEnable *PluginPolicy `protobuf:"bytes,2,opt,name=plugin_enable,json=pluginEnable,proto3,oneof"`
}

type Request_PluginDisable struct {
	PluginDisable *PluginPolicy `protobuf:"bytes,3,opt,name=plugin_disable,json=pluginDisable,proto3,oneof"`
}

type Request_PluginGrant struct {
	PluginGrant *PluginGrant `protobuf:"bytes,4,opt,name=plugin_grant,json=pluginGrant,proto3,oneof"`
}

type Request_PluginWithdraw struct {
	PluginWithdraw *PluginGrant `protobuf:"bytes,5,opt,name=plugin_withdraw,json=pluginWithdraw,proto3,oneof"`
}

type Request_UnitStart struct {
	// Execution is per unit.
	UnitStart *UnitAct `protobuf:"bytes,6,opt,name=unit_start,json=unitStart,proto3,oneof"`
}

type Request_UnitStop struct {
	UnitStop *UnitAct `protobuf:"bytes,7,opt,name=unit_stop,json=unitStop,proto3,oneof"`
}

type Request_UnitRestart struct {
	UnitRestart *UnitAct `protobuf:"bytes,8,opt,name=unit_restart,json=unitRestart,proto3,oneof"`
}

type Request_UnitStreamStart struct {
	UnitStreamStart *UnitStream `protobuf:"bytes,9,opt,name=unit_stream_start,json=unitStreamStart,proto3,oneof"`
}

type Request_UnitStreamStop struct {
	UnitStreamStop *UnitStream `protobuf:"bytes,10,opt,name=unit_stream_stop,json=unitStreamStop,proto3,oneof"`
}

type Request_UnitRetentionSet struct {
	UnitRetentionSet *UnitRetention `protobuf:"bytes,11,opt,name=unit_retention_set,json=unitRetentionSet,proto3,oneof"`
}

type Request_UnitRetentionClear struct {
	UnitRetentionClear *UnitAct `protobuf:"bytes,12,opt,name=unit_retention_clear,json=unitRetentionClear,proto3,oneof"`
}

type Request_UnitAsk struct {
	UnitAsk *UnitAsk `protobuf:"bytes,13,opt,name=unit_ask,json=unitAsk,proto3,oneof"`
}

type Request_Read struct {
	// The rest is per instance.
	Read *Read `protobuf:"bytes,14,opt,name=read,proto3,oneof"`
}

type Request_LogQuery struct {
	LogQuery *LogQuery `protobuf:"bytes,15,opt,name=log_query,json=logQuery,proto3,oneof"`
}

type Request_LogFollow struct {
	LogFollow *LogFollow `protobuf:"bytes,16,opt,name=log_follow,json=logFollow,proto3,oneof"`
}

type Request_Subscribe struct {
	Subscribe *Subscribe `protobuf:"bytes,17,opt,name=subscribe,proto3,oneof"`
}

func (*Request_PluginEnable) isRequest_Operation() {}

func (*Request_PluginDisable) isRequest_Operation() {}

func (*Request_PluginGrant) isRequest_Operation() {}

func (*Request_PluginWithdraw) isRequest_Operation() {}

func (*Request_UnitStart) isRequest_Operation() {}

func (*Request_UnitStop) isRequest_Operation() {}

func (*Request_UnitRestart) isRequest_Operation() {}

func (*Request_UnitStreamStart) isRequest_Operation() {}

func (*Request_UnitStreamStop) isRequest_Operation() {}

func (*Request_UnitRetentionSet) isRequest_Operation() {}

func (*Request_UnitRetentionClear) isRequest_Operation() {}

func (*Request_UnitAsk) isRequest_Operation() {}

func (*Request_Read) isRequest_Operation() {}

func (*Request_LogQuery) isRequest_Operation() {}

func (*Request_LogFollow) isRequest_Operation() {}

func (*Request_Subscribe) isRequest_Operation() {}

type PluginPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginPolicy) Reset() {
	*x = PluginPolicy{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginPolicy) ProtoMessage() {}

func (x *PluginPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginPolicy.ProtoReflect.Descriptor instead.
func (*PluginPolicy) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{1}
}

func (x *PluginPolicy) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type PluginGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugin        string                 `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginGrant) Reset() {
	*x = PluginGrant{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginGrant) ProtoMessage() {}

func (x *PluginGrant) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginGrant.ProtoReflect.Descriptor instead.
func (*PluginGrant) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{2}
}

func (x *PluginGrant) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *PluginGrant) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type UnitAct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitAct) Reset() {
	*x = UnitAct{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitAct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitAct) ProtoMessage() {}

func (x *UnitAct) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitAct.ProtoReflect.Descriptor instead.
func (*UnitAct) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{3}
}

func (x *UnitAct) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type UnitStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Stream        string                 `protobuf:"bytes,2,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitStream) Reset() {
	*x = UnitStream{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitStream) ProtoMessage() {}

func (x *UnitStream) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitStream.ProtoReflect.Descriptor instead.
func (*UnitStream) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{4}
}

func (x *UnitStream) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitStream) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

// A retention override: each limit absent is unconstrained, and none at all is legal.
type UnitRetention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Age           *durationpb.Duration   `protobuf:"bytes,2,opt,name=age,proto3" json:"age,omitempty"`
	Bytes         *uint64                `protobuf:"varint,3,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	Entries       *uint64                `protobuf:"varint,4,opt,name=entries,proto3,oneof" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitRetention) Reset() {
	*x = UnitRetention{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitRetention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitRetention) ProtoMessage() {}

func (x *UnitRetention) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitRetention.ProtoReflect.Descriptor instead.
func (*UnitRetention) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{5}
}

func (x *UnitRetention) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitRetention) GetAge() *durationpb.Duration {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *UnitRetention) GetBytes() uint64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *UnitRetention) GetEntries() uint64 {
	if x != nil && x.Entries != nil {
		return *x.Entries
	}
	return 0
}

// A question for a unit, opaque to the Core and bounded at 1 MiB.
type UnitAsk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unit          string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Question      []byte                 `protobuf:"bytes,3,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnitAsk) Reset() {
	*x = UnitAsk{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnitAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitAsk) ProtoMessage() {}

func (x *UnitAsk) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitAsk.ProtoReflect.Descriptor instead.
func (*UnitAsk) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{6}
}

func (x *UnitAsk) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UnitAsk) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UnitAsk) GetQuestion() []byte {
	if x != nil {
		return x.Question
	}
	return nil
}

// A subject kind, and an identity where one is named: with none, every subject of that kind.
type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{7}
}

func (x *Read) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Read) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type LogQuery struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Unit        string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Incarnation uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	From        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Until       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`
	Floor       uint32                 `protobuf:"varint,5,opt,name=floor,proto3" json:"floor,omitempty"`
	// The entry's seq to continue after; zero is the beginning of what survives.
	Cursor        uint64 `protobuf:"varint,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogQuery) Reset() {
	*x = LogQuery{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogQuery) ProtoMessage() {}

func (x *LogQuery) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogQuery.ProtoReflect.Descriptor instead.
func (*LogQuery) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{8}
}

func (x *LogQuery) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogQuery) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *LogQuery) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *LogQuery) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *LogQuery) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *LogQuery) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type LogFollow struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Unit        string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Incarnation uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Floor       uint32                 `protobuf:"varint,3,opt,name=floor,proto3" json:"floor,omitempty"`
	// The entry's seq to continue after; zero is the next entry to be written.
	Cursor        uint64 `protobuf:"varint,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogFollow) Reset() {
	*x = LogFollow{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogFollow) ProtoMessage() {}

func (x *LogFollow) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogFollow.ProtoReflect.Descriptor instead.
func (*LogFollow) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{9}
}

func (x *LogFollow) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogFollow) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *LogFollow) GetFloor() uint32 {
	if x != nil {
		return x.Floor
	}
	return 0
}

func (x *LogFollow) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

type Subscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{10}
}

func (x *Subscribe) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Answer:
	//
	//	*Response_PluginEnable
	//	*Response_PluginDisable
	//	*Response_PluginGrant
	//	*Response_PluginWithdraw
	//	*Response_UnitStart
	//	*Response_UnitStop
	//	*Response_UnitRestart
	//	*Response_UnitStreamStart
	//	*Response_UnitStreamStop
	//	*Response_UnitRetentionSet
	//	*Response_UnitRetentionClear
	//	*Response_UnitAsk
	//	*Response_Read
	//	*Response_LogQuery
	//	*Response_LogFollow
	//	*Response_Subscribe
	Answer        isResponse_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{11}
}

func (x *Response) GetAnswer() isResponse_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *Response) GetPluginEnable() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_PluginEnable); ok {
			return x.PluginEnable
		}
	}
	return nil
}

func (x *Response) GetPluginDisable() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_PluginDisable); ok {
			return x.PluginDisable
		}
	}
	return nil
}

func (x *Response) GetPluginGrant() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_PluginGrant); ok {
			return x.PluginGrant
		}
	}
	return nil
}

func (x *Response) GetPluginWithdraw() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_PluginWithdraw); ok {
			return x.PluginWithdraw
		}
	}
	return nil
}

func (x *Response) GetUnitStart() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitStart); ok {
			return x.UnitStart
		}
	}
	return nil
}

func (x *Response) GetUnitStop() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitStop); ok {
			return x.UnitStop
		}
	}
	return nil
}

func (x *Response) GetUnitRestart() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitRestart); ok {
			return x.UnitRestart
		}
	}
	return nil
}

func (x *Response) GetUnitStreamStart() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitStreamStart); ok {
			return x.UnitStreamStart
		}
	}
	return nil
}

func (x *Response) GetUnitStreamStop() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitStreamStop); ok {
			return x.UnitStreamStop
		}
	}
	return nil
}

func (x *Response) GetUnitRetentionSet() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitRetentionSet); ok {
			return x.UnitRetentionSet
		}
	}
	return nil
}

func (x *Response) GetUnitRetentionClear() *Changed {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitRetentionClear); ok {
			return x.UnitRetentionClear
		}
	}
	return nil
}

func (x *Response) GetUnitAsk() *Asked {
	if x != nil {
		if x, ok := x.Answer.(*Response_UnitAsk); ok {
			return x.UnitAsk
		}
	}
	return nil
}

func (x *Response) GetRead() *Records {
	if x != nil {
		if x, ok := x.Answer.(*Response_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *Response) GetLogQuery() *LogPage {
	if x != nil {
		if x, ok := x.Answer.(*Response_LogQuery); ok {
			return x.LogQuery
		}
	}
	return nil
}

func (x *Response) GetLogFollow() *Followed {
	if x != nil {
		if x, ok := x.Answer.(*Response_LogFollow); ok {
			return x.LogFollow
		}
	}
	return nil
}

func (x *Response) GetSubscribe() *Subscribed {
	if x != nil {
		if x, ok := x.Answer.(*Response_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

type isResponse_Answer interface {
	isResponse_Answer()
}

type Response_PluginEnable struct {
	PluginEnable *Changed `protobuf:"bytes,1,opt,name=plugin_enable,json=pluginEnable,proto3,oneof"`
}

type Response_PluginDisable struct {
	PluginDisable *Changed `protobuf:"bytes,2,opt,name=plugin_disable,json=pluginDisable,proto3,oneof"`
}

type Response_PluginGrant struct {
	PluginGrant *Changed `protobuf:"bytes,3,opt,name=plugin_grant,json=pluginGrant,proto3,oneof"`
}

type Response_PluginWithdraw struct {
	PluginWithdraw *Changed `protobuf:"bytes,4,opt,name=plugin_withdraw,json=pluginWithdraw,proto3,oneof"`
}

type Response_UnitStart struct {
	UnitStart *Changed `protobuf:"bytes,5,opt,name=unit_start,json=unitStart,proto3,oneof"`
}

type Response_UnitStop struct {
	UnitStop *Changed `protobuf:"bytes,6,opt,name=unit_stop,json=unitStop,proto3,oneof"`
}

type Response_UnitRestart struct {
	UnitRestart *Changed `protobuf:"bytes,7,opt,name=unit_restart,json=unitRestart,proto3,oneof"`
}

type Response_UnitStreamStart struct {
	UnitStreamStart *Changed `protobuf:"bytes,8,opt,name=unit_stream_start,json=unitStreamStart,proto3,oneof"`
}

type Response_UnitStreamStop struct {
	UnitStreamStop *Changed `protobuf:"bytes,9,opt,name=unit_stream_stop,json=unitStreamStop,proto3,oneof"`
}

type Response_UnitRetentionSet struct {
	UnitRetentionSet *Changed `protobuf:"bytes,10,opt,name=unit_retention_set,json=unitRetentionSet,proto3,oneof"`
}

type Response_UnitRetentionClear struct {
	UnitRetentionClear *Changed `protobuf:"bytes,11,opt,name=unit_retention_clear,json=unitRetentionClear,proto3,oneof"`
}

type Response_UnitAsk struct {
	UnitAsk *Asked `protobuf:"bytes,12,opt,name=unit_ask,json=unitAsk,proto3,oneof"`
}

type Response_Read struct {
	Read *Records `protobuf:"bytes,13,opt,name=read,proto3,oneof"`
}

type Response_LogQuery struct {
	LogQuery *LogPage `protobuf:"bytes,14,opt,name=log_query,json=logQuery,proto3,oneof"`
}

type Response_LogFollow struct {
	LogFollow *Followed `protobuf:"bytes,15,opt,name=log_follow,json=logFollow,proto3,oneof"`
}

type Response_Subscribe struct {
	Subscribe *Subscribed `protobuf:"bytes,16,opt,name=subscribe,proto3,oneof"`
}

func (*Response_PluginEnable) isResponse_Answer() {}

func (*Response_PluginDisable) isResponse_Answer() {}

func (*Response_PluginGrant) isResponse_Answer() {}

func (*Response_PluginWithdraw) isResponse_Answer() {}

func (*Response_UnitStart) isResponse_Answer() {}

func (*Response_UnitStop) isResponse_Answer() {}

func (*Response_UnitRestart) isResponse_Answer() {}

func (*Response_UnitStreamStart) isResponse_Answer() {}

func (*Response_UnitStreamStop) isResponse_Answer() {}

func (*Response_UnitRetentionSet) isResponse_Answer() {}

func (*Response_UnitRetentionClear) isResponse_Answer() {}

func (*Response_UnitAsk) isResponse_Answer() {}

func (*Response_Read) isResponse_Answer() {}

func (*Response_LogQuery) isResponse_Answer() {}

func (*Response_LogFollow) isResponse_Answer() {}

func (*Response_Subscribe) isResponse_Answer() {}

// What every change answers, which is what lets a caller converge without reading first.
type Changed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The value the operation replaced; an effect already true says nothing changed.
	Previously *Previously       `protobuf:"bytes,1,opt,name=previously,proto3" json:"previously,omitempty"`
	Effective  Changed_Effective `protobuf:"varint,2,opt,name=effective,proto3,enum=yoke.administrative.v1.Changed_Effective" json:"effective,omitempty"`
	// One per unit affected.
	Consequences  []*Consequence `protobuf:"bytes,3,rep,name=consequences,proto3" json:"consequences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Changed) Reset() {
	*x = Changed{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changed) ProtoMessage() {}

func (x *Changed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changed.ProtoReflect.Descriptor instead.
func (*Changed) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{12}
}

func (x *Changed) GetPreviously() *Previously {
	if x != nil {
		return x.Previously
	}
	return nil
}

func (x *Changed) GetEffective() Changed_Effective {
	if x != nil {
		return x.Effective
	}
	return Changed_EFFECTIVE_UNSPECIFIED
}

func (x *Changed) GetConsequences() []*Consequence {
	if x != nil {
		return x.Consequences
	}
	return nil
}

type Previously struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Previously_Enabled
	//	*Previously_Granted
	//	*Previously_State
	//	*Previously_Retention
	Value         isPreviously_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Previously) Reset() {
	*x = Previously{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Previously) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Previously) ProtoMessage() {}

func (x *Previously) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Previously.ProtoReflect.Descriptor instead.
func (*Previously) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{13}
}

func (x *Previously) GetValue() isPreviously_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Previously) GetEnabled() bool {
	if x != nil {
		if x, ok := x.Value.(*Previously_Enabled); ok {
			return x.Enabled
		}
	}
	return false
}

func (x *Previously) GetGranted() bool {
	if x != nil {
		if x, ok := x.Value.(*Previously_Granted); ok {
			return x.Granted
		}
	}
	return false
}

func (x *Previously) GetState() string {
	if x != nil {
		if x, ok := x.Value.(*Previously_State); ok {
			return x.State
		}
	}
	return ""
}

func (x *Previously) GetRetention() *Retention {
	if x != nil {
		if x, ok := x.Value.(*Previously_Retention); ok {
			return x.Retention
		}
	}
	return nil
}

type isPreviously_Value interface {
	isPreviously_Value()
}

type Previously_Enabled struct {
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3,oneof"`
}

type Previously_Granted struct {
	Granted bool `protobuf:"varint,2,opt,name=granted,proto3,oneof"`
}

type Previously_State struct {
	State string `protobuf:"bytes,3,opt,name=state,proto3,oneof"`
}

type Previously_Retention struct {
	Retention *Retention `protobuf:"bytes,4,opt,name=retention,proto3,oneof"`
}

func (*Previously_Enabled) isPreviously_Value() {}

func (*Previously_Granted) isPreviously_Value() {}

func (*Previously_State) isPreviously_Value() {}

func (*Previously_Retention) isPreviously_Value() {}

// A retention policy as it resolved; an absent limit is unconstrained.
type Retention struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Age           *durationpb.Duration   `protobuf:"bytes,1,opt,name=age,proto3" json:"age,omitempty"`
	Bytes         *uint64                `protobuf:"varint,2,opt,name=bytes,proto3,oneof" json:"bytes,omitempty"`
	Entries       *uint64                `protobuf:"varint,3,opt,name=entries,proto3,oneof" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retention) Reset() {
	*x = Retention{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retention) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retention) ProtoMessage() {}

func (x *Retention) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retention.ProtoReflect.Descriptor instead.
func (*Retention) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{14}
}

func (x *Retention) GetAge() *durationpb.Duration {
	if x != nil {
		return x.Age
	}
	return nil
}

func (x *Retention) GetBytes() uint64 {
	if x != nil && x.Bytes != nil {
		return *x.Bytes
	}
	return 0
}

func (x *Retention) GetEntries() uint64 {
	if x != nil && x.Entries != nil {
		return *x.Entries
	}
	return 0
}

type Consequence struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Unit        string                 `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Incarnation uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// What happened to it, for a person.
	What          string `protobuf:"bytes,3,opt,name=what,proto3" json:"what,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consequence) Reset() {
	*x = Consequence{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consequence) ProtoMessage() {}

func (x *Consequence) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consequence.ProtoReflect.Descriptor instead.
func (*Consequence) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{15}
}

func (x *Consequence) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Consequence) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Consequence) GetWhat() string {
	if x != nil {
		return x.What
	}
	return ""
}

// A unit's answer, opaque to the Core and bounded at 1 MiB.
type Asked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        []byte                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asked) Reset() {
	*x = Asked{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asked) ProtoMessage() {}

func (x *Asked) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asked.ProtoReflect.Descriptor instead.
func (*Asked) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{16}
}

func (x *Asked) GetAnswer() []byte {
	if x != nil {
		return x.Answer
	}
	return nil
}

// A page of the log store, in the order it keeps, and the cursor to continue from.
type LogPage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Next    uint64                 `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	// The cursor named an entry retention had removed, and the page resumed at the next surviving one.
	Resumed       bool `protobuf:"varint,3,opt,name=resumed,proto3" json:"resumed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogPage) Reset() {
	*x = LogPage{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogPage) ProtoMessage() {}

func (x *LogPage) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogPage.ProtoReflect.Descriptor instead.
func (*LogPage) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{17}
}

func (x *LogPage) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *LogPage) GetNext() uint64 {
	if x != nil {
		return x.Next
	}
	return 0
}

func (x *LogPage) GetResumed() bool {
	if x != nil {
		return x.Resumed
	}
	return false
}

type LogEntry struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Seq         uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	At          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	Unit        string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Incarnation uint64                 `protobuf:"varint,4,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	// stdout, stderr, core or reported.
	Source        string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Severity      uint32 `protobuf:"varint,6,opt,name=severity,proto3" json:"severity,omitempty"`
	Type          string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	SubjectKind   string `protobuf:"bytes,8,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	SubjectId     string `protobuf:"bytes,9,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	Actor         string `protobuf:"bytes,10,opt,name=actor,proto3" json:"actor,omitempty"`
	Cause         uint64 `protobuf:"varint,11,opt,name=cause,proto3" json:"cause,omitempty"`
	Message       string `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	Detail        []byte `protobuf:"bytes,13,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{18}
}

func (x *LogEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LogEntry) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *LogEntry) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *LogEntry) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *LogEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LogEntry) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *LogEntry) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *LogEntry) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *LogEntry) GetCause() uint64 {
	if x != nil {
		return x.Cause
	}
	return 0
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

// What a follow carries: an entry, or that the follower fell behind at a sequence, from which it queries.
type Followed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Carries:
	//
	//	*Followed_Entry
	//	*Followed_BehindAt
	Carries       isFollowed_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Followed) Reset() {
	*x = Followed{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Followed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Followed) ProtoMessage() {}

func (x *Followed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Followed.ProtoReflect.Descriptor instead.
func (*Followed) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{19}
}

func (x *Followed) GetCarries() isFollowed_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *Followed) GetEntry() *LogEntry {
	if x != nil {
		if x, ok := x.Carries.(*Followed_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *Followed) GetBehindAt() uint64 {
	if x != nil {
		if x, ok := x.Carries.(*Followed_BehindAt); ok {
			return x.BehindAt
		}
	}
	return 0
}

type isFollowed_Carries interface {
	isFollowed_Carries()
}

type Followed_Entry struct {
	Entry *LogEntry `protobuf:"bytes,1,opt,name=entry,proto3,oneof"`
}

type Followed_BehindAt struct {
	BehindAt uint64 `protobuf:"varint,2,opt,name=behind_at,json=behindAt,proto3,oneof"`
}

func (*Followed_Entry) isFollowed_Carries() {}

func (*Followed_BehindAt) isFollowed_Carries() {}

// What a subscription carries: the snapshot it opens with, an event, or an overflow and the fresh
// snapshot that follows it.
type Subscribed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Carries:
	//
	//	*Subscribed_Snapshot
	//	*Subscribed_Event
	//	*Subscribed_Overflow
	Carries       isSubscribed_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribed) Reset() {
	*x = Subscribed{}
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribed) ProtoMessage() {}

func (x *Subscribed) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_operations_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribed.ProtoReflect.Descriptor instead.
func (*Subscribed) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_operations_proto_rawDescGZIP(), []int{20}
}

func (x *Subscribed) GetCarries() isSubscribed_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *Subscribed) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Subscribed) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Subscribed) GetOverflow() *Snapshot {
	if x != nil {
		if x, ok := x.Carries.(*Subscribed_Overflow); ok {
			return x.Overflow
		}
	}
	return nil
}

type isSubscribed_Carries interface {
	isSubscribed_Carries()
}

type Subscribed_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type Subscribed_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

type Subscribed_Overflow struct {
	Overflow *Snapshot `protobuf:"bytes,3,opt,name=overflow,proto3,oneof"`
}

func (*Subscribed_Snapshot) isSubscribed_Carries() {}

func (*Subscribed_Event) isSubscribed_Carries() {}

func (*Subscribed_Overflow) isSubscribed_Carries() {}

var File_yoke_administrative_v1_operations_proto protoreflect.FileDescriptor

const file_yoke_administrative_v1_operations_proto_rawDesc = "" +
	"\n" +
	"'yoke/administrative/v1/operations.proto\x12\x16yoke.administrative.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#yoke/administrative/v1/events.proto\x1a$yoke/administrative/v1/records.proto\"\xb6\t\n" +
	"\aRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12K\n" +
	"\rplugin_enable\x18\x02 \x01(\v2$.yoke.administrative.v1.PluginPolicyH\x00R\fpluginEnable\x12M\n" +
	"\x0eplugin_disable\x18\x03 \x01(\v2$.yoke.administrative.v1.PluginPolicyH\x00R\rpluginDisable\x12H\n" +
	"\fplugin_grant\x18\x04 \x01(\v2#.yoke.administrative.v1.PluginGrantH\x00R\vpluginGrant\x12N\n" +
	"\x0fplugin_withdraw\x18\x05 \x01(\v2#.yoke.administrative.v1.PluginGrantH\x00R\x0epluginWithdraw\x12@\n" +
	"\n" +
	"unit_start\x18\x06 \x01(\v2\x1f.yoke.administrative.v1.UnitActH\x00R\tunitStart\x12>\n" +
	"\tunit_stop\x18\a \x01(\v2\x1f.yoke.administrative.v1.UnitActH\x00R\bunitStop\x12D\n" +
	"\funit_restart\x18\b \x01(\v2\x1f.yoke.administrative.v1.UnitActH\x00R\vunitRestart\x12P\n" +
	"\x11unit_stream_start\x18\t \x01(\v2\".yoke.administrative.v1.UnitStreamH\x00R\x0funitStreamStart\x12N\n" +
	"\x10unit_stream_stop\x18\n" +
	" \x01(\v2\".yoke.administrative.v1.UnitStreamH\x00R\x0eunitStreamStop\x12U\n" +
	"\x12unit_retention_set\x18\v \x01(\v2%.yoke.administrative.v1.UnitRetentionH\x00R\x10unitRetentionSet\x12S\n" +
	"\x14unit_retention_clear\x18\f \x01(\v2\x1f.yoke.administrative.v1.UnitActH\x00R\x12unitRetentionClear\x12<\n" +
	"\bunit_ask\x18\r \x01(\v2\x1f.yoke.administrative.v1.UnitAskH\x00R\aunitAsk\x122\n" +
	"\x04read\x18\x0e \x01(\v2\x1c.yoke.administrative.v1.ReadH\x00R\x04read\x12?\n" +
	"\tlog_query\x18\x0f \x01(\v2 .yoke.administrative.v1.LogQueryH\x00R\blogQuery\x12B\n" +
	"\n" +
	"log_follow\x18\x10 \x01(\v2!.yoke.administrative.v1.LogFollowH\x00R\tlogFollow\x12A\n" +
	"\tsubscribe\x18\x11 \x01(\v2!.yoke.administrative.v1.SubscribeH\x00R\tsubscribeB\v\n" +
	"\toperation\"&\n" +
	"\fPluginPolicy\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\"E\n" +
	"\vPluginGrant\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\"\x1d\n" +
	"\aUnitAct\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\"8\n" +
	"\n" +
	"UnitStream\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x16\n" +
	"\x06stream\x18\x02 \x01(\tR\x06stream\"\xa0\x01\n" +
	"\rUnitRetention\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12+\n" +
	"\x03age\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03age\x12\x19\n" +
	"\x05bytes\x18\x03 \x01(\x04H\x00R\x05bytes\x88\x01\x01\x12\x1d\n" +
	"\aentries\x18\x04 \x01(\x04H\x01R\aentries\x88\x01\x01B\b\n" +
	"\x06_bytesB\n" +
	"\n" +
	"\b_entries\"M\n" +
	"\aUnitAsk\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bquestion\x18\x03 \x01(\fR\bquestion\"6\n" +
	"\x04Read\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity\"\xd0\x01\n" +
	"\bLogQuery\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12.\n" +
	"\x04from\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x120\n" +
	"\x05until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x14\n" +
	"\x05floor\x18\x05 \x01(\rR\x05floor\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\x04R\x06cursor\"o\n" +
	"\tLogFollow\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12\x14\n" +
	"\x05floor\x18\x03 \x01(\rR\x05floor\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\x04R\x06cursor\"C\n" +
	"\tSubscribe\x126\n" +
	"\x06filter\x18\x01 \x01(\v2\x1e.yoke.administrative.v1.FilterR\x06filter\"\xfc\b\n" +
	"\bResponse\x12F\n" +
	"\rplugin_enable\x18\x01 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\fpluginEnable\x12H\n" +
	"\x0eplugin_disable\x18\x02 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\rpluginDisable\x12D\n" +
	"\fplugin_grant\x18\x03 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\vpluginGrant\x12J\n" +
	"\x0fplugin_withdraw\x18\x04 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\x0epluginWithdraw\x12@\n" +
	"\n" +
	"unit_start\x18\x05 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\tunitStart\x12>\n" +
	"\tunit_stop\x18\x06 \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\bunitStop\x12D\n" +
	"\funit_restart\x18\a \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\vunitRestart\x12M\n" +
	"\x11unit_stream_start\x18\b \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\x0funitStreamStart\x12K\n" +
	"\x10unit_stream_stop\x18\t \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\x0eunitStreamStop\x12O\n" +
	"\x12unit_retention_set\x18\n" +
	" \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\x10unitRetentionSet\x12S\n" +
	"\x14unit_retention_clear\x18\v \x01(\v2\x1f.yoke.administrative.v1.ChangedH\x00R\x12unitRetentionClear\x12:\n" +
	"\bunit_ask\x18\f \x01(\v2\x1d.yoke.administrative.v1.AskedH\x00R\aunitAsk\x125\n" +
	"\x04read\x18\r \x01(\v2\x1f.yoke.administrative.v1.RecordsH\x00R\x04read\x12>\n" +
	"\tlog_query\x18\x0e \x01(\v2\x1f.yoke.administrative.v1.LogPageH\x00R\blogQuery\x12A\n" +
	"\n" +
	"log_follow\x18\x0f \x01(\v2 .yoke.administrative.v1.FollowedH\x00R\tlogFollow\x12B\n" +
	"\tsubscribe\x18\x10 \x01(\v2\".yoke.administrative.v1.SubscribedH\x00R\tsubscribeB\b\n" +
	"\x06answer\"\xc3\x02\n" +
	"\aChanged\x12B\n" +
	"\n" +
	"previously\x18\x01 \x01(\v2\".yoke.administrative.v1.PreviouslyR\n" +
	"previously\x12G\n" +
	"\teffective\x18\x02 \x01(\x0e2).yoke.administrative.v1.Changed.EffectiveR\teffective\x12G\n" +
	"\fconsequences\x18\x03 \x03(\v2#.yoke.administrative.v1.ConsequenceR\fconsequences\"b\n" +
	"\tEffective\x12\x19\n" +
	"\x15EFFECTIVE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EFFECTIVE_IMMEDIATELY\x10\x01\x12\x1f\n" +
	"\x1bEFFECTIVE_AT_NEXT_ADMISSION\x10\x02\"\xa8\x01\n" +
	"\n" +
	"Previously\x12\x1a\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x12\x1a\n" +
	"\agranted\x18\x02 \x01(\bH\x00R\agranted\x12\x16\n" +
	"\x05state\x18\x03 \x01(\tH\x00R\x05state\x12A\n" +
	"\tretention\x18\x04 \x01(\v2!.yoke.administrative.v1.RetentionH\x00R\tretentionB\a\n" +
	"\x05value\"\x88\x01\n" +
	"\tRetention\x12+\n" +
	"\x03age\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x03age\x12\x19\n" +
	"\x05bytes\x18\x02 \x01(\x04H\x00R\x05bytes\x88\x01\x01\x12\x1d\n" +
	"\aentries\x18\x03 \x01(\x04H\x01R\aentries\x88\x01\x01B\b\n" +
	"\x06_bytesB\n" +
	"\n" +
	"\b_entries\"W\n" +
	"\vConsequence\x12\x12\n" +
	"\x04unit\x18\x01 \x01(\tR\x04unit\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12\x12\n" +
	"\x04what\x18\x03 \x01(\tR\x04what\"\x1f\n" +
	"\x05Asked\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\fR\x06answer\"s\n" +
	"\aLogPage\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .yoke.administrative.v1.LogEntryR\aentries\x12\x12\n" +
	"\x04next\x18\x02 \x01(\x04R\x04next\x12\x18\n" +
	"\aresumed\x18\x03 \x01(\bR\aresumed\"\xe6\x02\n" +
	"\bLogEntry\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12 \n" +
	"\vincarnation\x18\x04 \x01(\x04R\vincarnation\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x06 \x01(\rR\bseverity\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12!\n" +
	"\fsubject_kind\x18\b \x01(\tR\vsubjectKind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\t \x01(\tR\tsubjectId\x12\x14\n" +
	"\x05actor\x18\n" +
	" \x01(\tR\x05actor\x12\x14\n" +
	"\x05cause\x18\v \x01(\x04R\x05cause\x12\x18\n" +
	"\amessage\x18\f \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\r \x01(\fR\x06detail\"n\n" +
	"\bFollowed\x128\n" +
	"\x05entry\x18\x01 \x01(\v2 .yoke.administrative.v1.LogEntryH\x00R\x05entry\x12\x1d\n" +
	"\tbehind_at\x18\x02 \x01(\x04H\x00R\bbehindAtB\t\n" +
	"\acarries\"\xce\x01\n" +
	"\n" +
	"Subscribed\x12>\n" +
	"\bsnapshot\x18\x01 \x01(\v2 .yoke.administrative.v1.SnapshotH\x00R\bsnapshot\x125\n" +
	"\x05event\x18\x02 \x01(\v2\x1d.yoke.administrative.v1.EventH\x00R\x05event\x12>\n" +
	"\boverflow\x18\x03 \x01(\v2 .yoke.administrative.v1.SnapshotH\x00R\boverflowB\t\n" +
	"\acarriesBLZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3"

var (
	file_yoke_administrative_v1_operations_proto_rawDescOnce sync.Once
	file_yoke_administrative_v1_operations_proto_rawDescData []byte
)

func file_yoke_administrative_v1_operations_proto_rawDescGZIP() []byte {
	file_yoke_administrative_v1_operations_proto_rawDescOnce.Do(func() {
		file_yoke_administrative_v1_operations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_operations_proto_rawDesc), len(file_yoke_administrative_v1_operations_proto_rawDesc)))
	})
	return file_yoke_administrative_v1_operations_proto_rawDescData
}

var file_yoke_administrative_v1_operations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_administrative_v1_operations_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_yoke_administrative_v1_operations_proto_goTypes = []any{
	(Changed_Effective)(0),        // 0: yoke.administrative.v1.Changed.Effective
	(*Request)(nil),               // 1: yoke.administrative.v1.Request
	(*PluginPolicy)(nil),          // 2: yoke.administrative.v1.PluginPolicy
	(*PluginGrant)(nil),           // 3: yoke.administrative.v1.PluginGrant
	(*UnitAct)(nil),               // 4: yoke.administrative.v1.UnitAct
	(*UnitStream)(nil),            // 5: yoke.administrative.v1.UnitStream
	(*UnitRetention)(nil),         // 6: yoke.administrative.v1.UnitRetention
	(*UnitAsk)(nil),               // 7: yoke.administrative.v1.UnitAsk
	(*Read)(nil),                  // 8: yoke.administrative.v1.Read
	(*LogQuery)(nil),              // 9: yoke.administrative.v1.LogQuery
	(*LogFollow)(nil),             // 10: yoke.administrative.v1.LogFollow
	(*Subscribe)(nil),             // 11: yoke.administrative.v1.Subscribe
	(*Response)(nil),              // 12: yoke.administrative.v1.Response
	(*Changed)(nil),               // 13: yoke.administrative.v1.Changed
	(*Previously)(nil),            // 14: yoke.administrative.v1.Previously
	(*Retention)(nil),             // 15: yoke.administrative.v1.Retention
	(*Consequence)(nil),           // 16: yoke.administrative.v1.Consequence
	(*Asked)(nil),                 // 17: yoke.administrative.v1.Asked
	(*LogPage)(nil),               // 18: yoke.administrative.v1.LogPage
	(*LogEntry)(nil),              // 19: yoke.administrative.v1.LogEntry
	(*Followed)(nil),              // 20: yoke.administrative.v1.Followed
	(*Subscribed)(nil),            // 21: yoke.administrative.v1.Subscribed
	(*durationpb.Duration)(nil),   // 22: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
	(*Filter)(nil),                // 24: yoke.administrative.v1.Filter
	(*Records)(nil),               // 25: yoke.administrative.v1.Records
	(*Snapshot)(nil),              // 26: yoke.administrative.v1.Snapshot
	(*Event)(nil),                 // 27: yoke.administrative.v1.Event
}
var file_yoke_administrative_v1_operations_proto_depIdxs = []int32{
	2,  // 0: yoke.administrative.v1.Request.plugin_enable:type_name -> yoke.administrative.v1.PluginPolicy
	2,  // 1: yoke.administrative.v1.Request.plugin_disable:type_name -> yoke.administrative.v1.PluginPolicy
	3,  // 2: yoke.administrative.v1.Request.plugin_grant:type_name -> yoke.administrative.v1.PluginGrant
	3,  // 3: yoke.administrative.v1.Request.plugin_withdraw:type_name -> yoke.administrative.v1.PluginGrant
	4,  // 4: yoke.administrative.v1.Request.unit_start:type_name -> yoke.administrative.v1.UnitAct
	4,  // 5: yoke.administrative.v1.Request.unit_stop:type_name -> yoke.administrative.v1.UnitAct
	4,  // 6: yoke.administrative.v1.Request.unit_restart:type_name -> yoke.administrative.v1.UnitAct
	5,  // 7: yoke.administrative.v1.Request.unit_stream_start:type_name -> yoke.administrative.v1.UnitStream
	5,  // 8: yoke.administrative.v1.Request.unit_stream_stop:type_name -> yoke.administrative.v1.UnitStream
	6,  // 9: yoke.administrative.v1.Request.unit_retention_set:type_name -> yoke.administrative.v1.UnitRetention
	4,  // 10: yoke.administrative.v1.Request.unit_retention_clear:type_name -> yoke.administrative.v1.UnitAct
	7,  // 11: yoke.administrative.v1.Request.unit_ask:type_name -> yoke.administrative.v1.UnitAsk
	8,  // 12: yoke.administrative.v1.Request.read:type_name -> yoke.administrative.v1.Read
	9,  // 13: yoke.administrative.v1.Request.log_query:type_name -> yoke.administrative.v1.LogQuery
	10, // 14: yoke.administrative.v1.Request.log_follow:type_name -> yoke.administrative.v1.LogFollow
	11, // 15: yoke.administrative.v1.Request.subscribe:type_name -> yoke.administrative.v1.Subscribe
	22, // 16: yoke.administrative.v1.UnitRetention.age:type_name -> google.protobuf.Duration
	23, // 17: yoke.administrative.v1.LogQuery.from:type_name -> google.protobuf.Timestamp
	23, // 18: yoke.administrative.v1.LogQuery.until:type_name -> google.protobuf.Timestamp
	24, // 19: yoke.administrative.v1.Subscribe.filter:type_name -> yoke.administrative.v1.Filter
	13, // 20: yoke.administrative.v1.Response.plugin_enable:type_name -> yoke.administrative.v1.Changed
	13, // 21: yoke.administrative.v1.Response.plugin_disable:type_name -> yoke.administrative.v1.Changed
	13, // 22: yoke.administrative.v1.Response.plugin_grant:type_name -> yoke.administrative.v1.Changed
	13, // 23: yoke.administrative.v1.Response.plugin_withdraw:type_name -> yoke.administrative.v1.Changed
	13, // 24: yoke.administrative.v1.Response.unit_start:type_name -> yoke.administrative.v1.Changed
	13, // 25: yoke.administrative.v1.Response.unit_stop:type_name -> yoke.administrative.v1.Changed
	13, // 26: yoke.administrative.v1.Response.unit_restart:type_name -> yoke.administrative.v1.Changed
	13, // 27: yoke.administrative.v1.Response.unit_stream_start:type_name -> yoke.administrative.v1.Changed
	13, // 28: yoke.administrative.v1.Response.unit_stream_stop:type_name -> yoke.administrative.v1.Changed
	13, // 29: yoke.administrative.v1.Response.unit_retention_set:type_name -> yoke.administrative.v1.Changed
	13, // 30: yoke.administrative.v1.Response.unit_retention_clear:type_name -> yoke.administrative.v1.Changed
	17, // 31: yoke.administrative.v1.Response.unit_ask:type_name -> yoke.administrative.v1.Asked
	25, // 32: yoke.administrative.v1.Response.read:type_name -> yoke.administrative.v1.Records
	18, // 33: yoke.administrative.v1.Response.log_query:type_name -> yoke.administrative.v1.LogPage
	20, // 34: yoke.administrative.v1.Response.log_follow:type_name -> yoke.administrative.v1.Followed
	21, // 35: yoke.administrative.v1.Response.subscribe:type_name -> yoke.administrative.v1.Subscribed
	14, // 36: yoke.administrative.v1.Changed.previously:type_name -> yoke.administrative.v1.Previously
	0,  // 37: yoke.administrative.v1.Changed.effective:type_name -> yoke.administrative.v1.Changed.Effective
	16, // 38: yoke.administrative.v1.Changed.consequences:type_name -> yoke.administrative.v1.Consequence
	15, // 39: yoke.administrative.v1.Previously.retention:type_name -> yoke.administrative.v1.Retention
	22, // 40: yoke.administrative.v1.Retention.age:type_name -> google.protobuf.Duration
	19, // 41: yoke.administrative.v1.LogPage.entries:type_name -> yoke.administrative.v1.LogEntry
	23, // 42: yoke.administrative.v1.LogEntry.at:type_name -> google.protobuf.Timestamp
	19, // 43: yoke.administrative.v1.Followed.entry:type_name -> yoke.administrative.v1.LogEntry
	26, // 44: yoke.administrative.v1.Subscribed.snapshot:type_name -> yoke.administrative.v1.Snapshot
	27, // 45: yoke.administrative.v1.Subscribed.event:type_name -> yoke.administrative.v1.Event
	26, // 46: yoke.administrative.v1.Subscribed.overflow:type_name -> yoke.administrative.v1.Snapshot
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_yoke_administrative_v1_operations_proto_init() }
func file_yoke_administrative_v1_operations_proto_init() {
	if File_yoke_administrative_v1_operations_proto != nil {
		return
	}
	file_yoke_administrative_v1_events_proto_init()
	file_yoke_administrative_v1_records_proto_init()
	file_yoke_administrative_v1_operations_proto_msgTypes[0].OneofWrappers = []any{
		(*Request_PluginEnable)(nil),
		(*Request_PluginDisable)(nil),
		(*Request_PluginGrant)(nil),
		(*Request_PluginWithdraw)(nil),
		(*Request_UnitStart)(nil),
		(*Request_UnitStop)(nil),
		(*Request_UnitRestart)(nil),
		(*Request_UnitStreamStart)(nil),
		(*Request_UnitStreamStop)(nil),
		(*Request_UnitRetentionSet)(nil),
		(*Request_UnitRetentionClear)(nil),
		(*Request_UnitAsk)(nil),
		(*Request_Read)(nil),
		(*Request_LogQuery)(nil),
		(*Request_LogFollow)(nil),
		(*Request_Subscribe)(nil),
	}
	file_yoke_administrative_v1_operations_proto_msgTypes[5].OneofWrappers = []any{}
	file_yoke_administrative_v1_operations_proto_msgTypes[11].OneofWrappers = []any{
		(*Response_PluginEnable)(nil),
		(*Response_PluginDisable)(nil),
		(*Response_PluginGrant)(nil),
		(*Response_PluginWithdraw)(nil),
		(*Response_UnitStart)(nil),
		(*Response_UnitStop)(nil),
		(*Response_UnitRestart)(nil),
		(*Response_UnitStreamStart)(nil),
		(*Response_UnitStreamStop)(nil),
		(*Response_UnitRetentionSet)(nil),
		(*Response_UnitRetentionClear)(nil),
		(*Response_UnitAsk)(nil),
		(*Response_Read)(nil),
		(*Response_LogQuery)(nil),
		(*Response_LogFollow)(nil),
		(*Response_Subscribe)(nil),
	}
	file_yoke_administrative_v1_operations_proto_msgTypes[13].OneofWrappers = []any{
		(*Previously_Enabled)(nil),
		(*Previously_Granted)(nil),
		(*Previously_State)(nil),
		(*Previously_Retention)(nil),
	}
	file_yoke_administrative_v1_operations_proto_msgTypes[14].OneofWrappers = []any{}
	file_yoke_administrative_v1_operations_proto_msgTypes[19].OneofWrappers = []any{
		(*Followed_Entry)(nil),
		(*Followed_BehindAt)(nil),
	}
	file_yoke_administrative_v1_operations_proto_msgTypes[20].OneofWrappers = []any{
		(*Subscribed_Snapshot)(nil),
		(*Subscribed_Event)(nil),
		(*Subscribed_Overflow)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_operations_proto_rawDesc), len(file_yoke_administrative_v1_operations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_administrative_v1_operations_proto_goTypes,
		DependencyIndexes: file_yoke_administrative_v1_operations_proto_depIdxs,
		EnumInfos:         file_yoke_administrative_v1_operations_proto_enumTypes,
		MessageInfos:      file_yoke_administrative_v1_operations_proto_msgTypes,
	}.Build()
	File_yoke_administrative_v1_operations_proto = out.File
	file_yoke_administrative_v1_operations_proto_goTypes = nil
	file_yoke_administrative_v1_operations_proto_depIdxs = nil
}
