// The operator projection, on operator.sock: a call and its answer, or one call answered by a stream.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/administrative/v1/operator.proto

package administrativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_yoke_administrative_v1_operator_proto protoreflect.FileDescriptor

const file_yoke_administrative_v1_operator_proto_rawDesc = "" +
	"\n" +
	"%yoke/administrative/v1/operator.proto\x12\x16yoke.administrative.v1\x1a'yoke/administrative/v1/operations.proto2\xa3\x01\n" +
	"\bOperator\x12I\n" +
	"\x04Call\x12\x1f.yoke.administrative.v1.Request\x1a .yoke.administrative.v1.Response\x12L\n" +
	"\x05Watch\x12\x1f.yoke.administrative.v1.Request\x1a .yoke.administrative.v1.Response0\x01BLZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3"

var file_yoke_administrative_v1_operator_proto_goTypes = []any{
	(*Request)(nil),  // 0: yoke.administrative.v1.Request
	(*Response)(nil), // 1: yoke.administrative.v1.Response
}
var file_yoke_administrative_v1_operator_proto_depIdxs = []int32{
	0, // 0: yoke.administrative.v1.Operator.Call:input_type -> yoke.administrative.v1.Request
	0, // 1: yoke.administrative.v1.Operator.Watch:input_type -> yoke.administrative.v1.Request
	1, // 2: yoke.administrative.v1.Operator.Call:output_type -> yoke.administrative.v1.Response
	1, // 3: yoke.administrative.v1.Operator.Watch:output_type -> yoke.administrative.v1.Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yoke_administrative_v1_operator_proto_init() }
func file_yoke_administrative_v1_operator_proto_init() {
	if File_yoke_administrative_v1_operator_proto != nil {
		return
	}
	file_yoke_administrative_v1_operations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_operator_proto_rawDesc), len(file_yoke_administrative_v1_operator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yoke_administrative_v1_operator_proto_goTypes,
		DependencyIndexes: file_yoke_administrative_v1_operator_proto_depIdxs,
	}.Build()
	File_yoke_administrative_v1_operator_proto = out.File
	file_yoke_administrative_v1_operator_proto_goTypes = nil
	file_yoke_administrative_v1_operator_proto_depIdxs = nil
}
