// The shell projection, on shell.sock: one connection held open, carrying many calls, each correlated by
// an identity the caller chose, and each ending with exactly one completion.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: yoke/administrative/v1/shell.proto

package administrativev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Shell_Connect_FullMethodName = "/yoke.administrative.v1.Shell/Connect"
)

// ShellClient is the client API for Shell service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShellClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, CoreFrame], error)
}

type shellClient struct {
	cc grpc.ClientConnInterface
}

func NewShellClient(cc grpc.ClientConnInterface) ShellClient {
	return &shellClient{cc}
}

func (c *shellClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, CoreFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Shell_ServiceDesc.Streams[0], Shell_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, CoreFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shell_ConnectClient = grpc.BidiStreamingClient[ClientFrame, CoreFrame]

// ShellServer is the server API for Shell service.
// All implementations must embed UnimplementedShellServer
// for forward compatibility.
type ShellServer interface {
	Connect(grpc.BidiStreamingServer[ClientFrame, CoreFrame]) error
	mustEmbedUnimplementedShellServer()
}

// UnimplementedShellServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShellServer struct{}

func (UnimplementedShellServer) Connect(grpc.BidiStreamingServer[ClientFrame, CoreFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedShellServer) mustEmbedUnimplementedShellServer() {}
func (UnimplementedShellServer) testEmbeddedByValue()               {}

// UnsafeShellServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShellServer will
// result in compilation errors.
type UnsafeShellServer interface {
	mustEmbedUnimplementedShellServer()
}

func RegisterShellServer(s grpc.ServiceRegistrar, srv ShellServer) {
	// If the following call panics, it indicates UnimplementedShellServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Shell_ServiceDesc, srv)
}

func _Shell_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShellServer).Connect(&grpc.GenericServerStream[ClientFrame, CoreFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Shell_ConnectServer = grpc.BidiStreamingServer[ClientFrame, CoreFrame]

// Shell_ServiceDesc is the grpc.ServiceDesc for Shell service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shell_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yoke.administrative.v1.Shell",
	HandlerType: (*ShellServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Shell_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "yoke/administrative/v1/shell.proto",
}
