// The shell projection, on shell.sock: one connection held open, carrying many calls, each correlated by
// an identity the caller chose, and each ending with exactly one completion.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/administrative/v1/shell.proto

package administrativev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chosen by the caller, unique within this connection.
	Call string `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	// Types that are valid to be assigned to Carries:
	//
	//	*ClientFrame_Request
	//	*ClientFrame_Cancel
	Carries       isClientFrame_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_shell_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetCall() string {
	if x != nil {
		return x.Call
	}
	return ""
}

func (x *ClientFrame) GetCarries() isClientFrame_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *ClientFrame) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Carries.(*ClientFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *ClientFrame) GetCancel() *Cancel {
	if x != nil {
		if x, ok := x.Carries.(*ClientFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isClientFrame_Carries interface {
	isClientFrame_Carries()
}

type ClientFrame_Request struct {
	Request *Request `protobuf:"bytes,2,opt,name=request,proto3,oneof"`
}

type ClientFrame_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,3,opt,name=cancel,proto3,oneof"`
}

func (*ClientFrame_Request) isClientFrame_Carries() {}

func (*ClientFrame_Cancel) isClientFrame_Carries() {}

// Ends a call in flight.
type Cancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_shell_proto_rawDescGZIP(), []int{1}
}

type CoreFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call this frame belongs to; empty on the opening.
	Call string `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	// Types that are valid to be assigned to Carries:
	//
	//	*CoreFrame_Opening
	//	*CoreFrame_Answer
	//	*CoreFrame_Event
	//	*CoreFrame_Refusal
	//	*CoreFrame_Completion
	Carries       isCoreFrame_Carries `protobuf_oneof:"carries"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreFrame) Reset() {
	*x = CoreFrame{}
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreFrame) ProtoMessage() {}

func (x *CoreFrame) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreFrame.ProtoReflect.Descriptor instead.
func (*CoreFrame) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_shell_proto_rawDescGZIP(), []int{2}
}

func (x *CoreFrame) GetCall() string {
	if x != nil {
		return x.Call
	}
	return ""
}

func (x *CoreFrame) GetCarries() isCoreFrame_Carries {
	if x != nil {
		return x.Carries
	}
	return nil
}

func (x *CoreFrame) GetOpening() *Opening {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Opening); ok {
			return x.Opening
		}
	}
	return nil
}

func (x *CoreFrame) GetAnswer() *Response {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *CoreFrame) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *CoreFrame) GetRefusal() *Refusal {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Refusal); ok {
			return x.Refusal
		}
	}
	return nil
}

func (x *CoreFrame) GetCompletion() *Completion {
	if x != nil {
		if x, ok := x.Carries.(*CoreFrame_Completion); ok {
			return x.Completion
		}
	}
	return nil
}

type isCoreFrame_Carries interface {
	isCoreFrame_Carries()
}

type CoreFrame_Opening struct {
	Opening *Opening `protobuf:"bytes,2,opt,name=opening,proto3,oneof"`
}

type CoreFrame_Answer struct {
	Answer *Response `protobuf:"bytes,3,opt,name=answer,proto3,oneof"`
}

type CoreFrame_Event struct {
	Event *Event `protobuf:"bytes,4,opt,name=event,proto3,oneof"`
}

type CoreFrame_Refusal struct {
	// A refusal belongs to one call and does not end the connection.
	Refusal *Refusal `protobuf:"bytes,5,opt,name=refusal,proto3,oneof"`
}

type CoreFrame_Completion struct {
	Completion *Completion `protobuf:"bytes,6,opt,name=completion,proto3,oneof"`
}

func (*CoreFrame_Opening) isCoreFrame_Carries() {}

func (*CoreFrame_Answer) isCoreFrame_Carries() {}

func (*CoreFrame_Event) isCoreFrame_Carries() {}

func (*CoreFrame_Refusal) isCoreFrame_Carries() {}

func (*CoreFrame_Completion) isCoreFrame_Carries() {}

// The Core's first frame, before anything the client asked for.
type Opening struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Connection string                 `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	Actor      *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	// The call identity of the standing subscription, which the client may replace or cancel.
	Subscription string `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// The contract version this Core speaks.
	Version       uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Opening) Reset() {
	*x = Opening{}
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Opening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Opening) ProtoMessage() {}

func (x *Opening) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Opening.ProtoReflect.Descriptor instead.
func (*Opening) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_shell_proto_rawDescGZIP(), []int{3}
}

func (x *Opening) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *Opening) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *Opening) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Opening) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// The end of a call; never inferred from silence.
type Completion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_administrative_v1_shell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_yoke_administrative_v1_shell_proto_rawDescGZIP(), []int{4}
}

var File_yoke_administrative_v1_shell_proto protoreflect.FileDescriptor

const file_yoke_administrative_v1_shell_proto_rawDesc = "" +
	"\n" +
	"\"yoke/administrative/v1/shell.proto\x12\x16yoke.administrative.v1\x1a\"yoke/administrative/v1/codes.proto\x1a#yoke/administrative/v1/events.proto\x1a'yoke/administrative/v1/operations.proto\"\xa3\x01\n" +
	"\vClientFrame\x12\x12\n" +
	"\x04call\x18\x01 \x01(\tR\x04call\x12;\n" +
	"\arequest\x18\x02 \x01(\v2\x1f.yoke.administrative.v1.RequestH\x00R\arequest\x128\n" +
	"\x06cancel\x18\x03 \x01(\v2\x1e.yoke.administrative.v1.CancelH\x00R\x06cancelB\t\n" +
	"\acarries\"\b\n" +
	"\x06Cancel\"\xdd\x02\n" +
	"\tCoreFrame\x12\x12\n" +
	"\x04call\x18\x01 \x01(\tR\x04call\x12;\n" +
	"\aopening\x18\x02 \x01(\v2\x1f.yoke.administrative.v1.OpeningH\x00R\aopening\x12:\n" +
	"\x06answer\x18\x03 \x01(\v2 .yoke.administrative.v1.ResponseH\x00R\x06answer\x125\n" +
	"\x05event\x18\x04 \x01(\v2\x1d.yoke.administrative.v1.EventH\x00R\x05event\x12;\n" +
	"\arefusal\x18\x05 \x01(\v2\x1f.yoke.administrative.v1.RefusalH\x00R\arefusal\x12D\n" +
	"\n" +
	"completion\x18\x06 \x01(\v2\".yoke.administrative.v1.CompletionH\x00R\n" +
	"completionB\t\n" +
	"\acarries\"\x9c\x01\n" +
	"\aOpening\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x123\n" +
	"\x05actor\x18\x02 \x01(\v2\x1d.yoke.administrative.v1.ActorR\x05actor\x12\"\n" +
	"\fsubscription\x18\x03 \x01(\tR\fsubscription\x12\x18\n" +
	"\aversion\x18\x04 \x01(\rR\aversion\"\f\n" +
	"\n" +
	"Completion2^\n" +
	"\x05Shell\x12U\n" +
	"\aConnect\x12#.yoke.administrative.v1.ClientFrame\x1a!.yoke.administrative.v1.CoreFrame(\x010\x01BLZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3"

var (
	file_yoke_administrative_v1_shell_proto_rawDescOnce sync.Once
	file_yoke_administrative_v1_shell_proto_rawDescData []byte
)

func file_yoke_administrative_v1_shell_proto_rawDescGZIP() []byte {
	file_yoke_administrative_v1_shell_proto_rawDescOnce.Do(func() {
		file_yoke_administrative_v1_shell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_shell_proto_rawDesc), len(file_yoke_administrative_v1_shell_proto_rawDesc)))
	})
	return file_yoke_administrative_v1_shell_proto_rawDescData
}

var file_yoke_administrative_v1_shell_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yoke_administrative_v1_shell_proto_goTypes = []any{
	(*ClientFrame)(nil), // 0: yoke.administrative.v1.ClientFrame
	(*Cancel)(nil),      // 1: yoke.administrative.v1.Cancel
	(*CoreFrame)(nil),   // 2: yoke.administrative.v1.CoreFrame
	(*Opening)(nil),     // 3: yoke.administrative.v1.Opening
	(*Completion)(nil),  // 4: yoke.administrative.v1.Completion
	(*Request)(nil),     // 5: yoke.administrative.v1.Request
	(*Response)(nil),    // 6: yoke.administrative.v1.Response
	(*Event)(nil),       // 7: yoke.administrative.v1.Event
	(*Refusal)(nil),     // 8: yoke.administrative.v1.Refusal
	(*Actor)(nil),       // 9: yoke.administrative.v1.Actor
}
var file_yoke_administrative_v1_shell_proto_depIdxs = []int32{
	5, // 0: yoke.administrative.v1.ClientFrame.request:type_name -> yoke.administrative.v1.Request
	1, // 1: yoke.administrative.v1.ClientFrame.cancel:type_name -> yoke.administrative.v1.Cancel
	3, // 2: yoke.administrative.v1.CoreFrame.opening:type_name -> yoke.administrative.v1.Opening
	6, // 3: yoke.administrative.v1.CoreFrame.answer:type_name -> yoke.administrative.v1.Response
	7, // 4: yoke.administrative.v1.CoreFrame.event:type_name -> yoke.administrative.v1.Event
	8, // 5: yoke.administrative.v1.CoreFrame.refusal:type_name -> yoke.administrative.v1.Refusal
	4, // 6: yoke.administrative.v1.CoreFrame.completion:type_name -> yoke.administrative.v1.Completion
	9, // 7: yoke.administrative.v1.Opening.actor:type_name -> yoke.administrative.v1.Actor
	0, // 8: yoke.administrative.v1.Shell.Connect:input_type -> yoke.administrative.v1.ClientFrame
	2, // 9: yoke.administrative.v1.Shell.Connect:output_type -> yoke.administrative.v1.CoreFrame
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_yoke_administrative_v1_shell_proto_init() }
func file_yoke_administrative_v1_shell_proto_init() {
	if File_yoke_administrative_v1_shell_proto != nil {
		return
	}
	file_yoke_administrative_v1_codes_proto_init()
	file_yoke_administrative_v1_events_proto_init()
	file_yoke_administrative_v1_operations_proto_init()
	file_yoke_administrative_v1_shell_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Request)(nil),
		(*ClientFrame_Cancel)(nil),
	}
	file_yoke_administrative_v1_shell_proto_msgTypes[2].OneofWrappers = []any{
		(*CoreFrame_Opening)(nil),
		(*CoreFrame_Answer)(nil),
		(*CoreFrame_Event)(nil),
		(*CoreFrame_Refusal)(nil),
		(*CoreFrame_Completion)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_administrative_v1_shell_proto_rawDesc), len(file_yoke_administrative_v1_shell_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yoke_administrative_v1_shell_proto_goTypes,
		DependencyIndexes: file_yoke_administrative_v1_shell_proto_depIdxs,
		MessageInfos:      file_yoke_administrative_v1_shell_proto_msgTypes,
	}.Build()
	File_yoke_administrative_v1_shell_proto = out.File
	file_yoke_administrative_v1_shell_proto_goTypes = nil
	file_yoke_administrative_v1_shell_proto_depIdxs = nil
}
