from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class Code(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    CODE_UNSPECIFIED: _ClassVar[Code]
    CODE_ADMISSION_STRUCTURAL_MALFORMED: _ClassVar[Code]
    CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN: _ClassVar[Code]
    CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT: _ClassVar[Code]
    CODE_ADMISSION_STATE_DISABLED: _ClassVar[Code]
    CODE_ADMISSION_AUTH_INVALID: _ClassVar[Code]
    CODE_ADMISSION_AUTH_EXPIRED: _ClassVar[Code]
    CODE_ADMISSION_AUTH_CONSUMED: _ClassVar[Code]
    CODE_ADMISSION_COMPAT_UNSUPPORTED: _ClassVar[Code]
    CODE_ADMISSION_CONSISTENCY_DIVERGENT: _ClassVar[Code]
    CODE_ADMISSION_CONFLICT_UNIT_LIVE: _ClassVar[Code]
    CODE_ADMISSION_SESSION_UNAVAILABLE: _ClassVar[Code]
    CODE_SESSION_UNKNOWN: _ClassVar[Code]
    CODE_SESSION_REVOKED: _ClassVar[Code]
    CODE_SESSION_MESSAGE_MALFORMED: _ClassVar[Code]
    CODE_SESSION_MESSAGE_DUPLICATE: _ClassVar[Code]
    CODE_SESSION_DIRECTION: _ClassVar[Code]
    CODE_SESSION_CORRELATION_MISSING: _ClassVar[Code]
    CODE_SESSION_CORRELATION_UNKNOWN: _ClassVar[Code]
    CODE_SCOPE_WITHHELD: _ClassVar[Code]
    CODE_SCOPE_UNDECLARED: _ClassVar[Code]
    CODE_STREAM_INACTIVE: _ClassVar[Code]
    CODE_COMMAND_UNKNOWN: _ClassVar[Code]
    CODE_QUERY_UNKNOWN: _ClassVar[Code]
CODE_UNSPECIFIED: Code
CODE_ADMISSION_STRUCTURAL_MALFORMED: Code
CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN: Code
CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT: Code
CODE_ADMISSION_STATE_DISABLED: Code
CODE_ADMISSION_AUTH_INVALID: Code
CODE_ADMISSION_AUTH_EXPIRED: Code
CODE_ADMISSION_AUTH_CONSUMED: Code
CODE_ADMISSION_COMPAT_UNSUPPORTED: Code
CODE_ADMISSION_CONSISTENCY_DIVERGENT: Code
CODE_ADMISSION_CONFLICT_UNIT_LIVE: Code
CODE_ADMISSION_SESSION_UNAVAILABLE: Code
CODE_SESSION_UNKNOWN: Code
CODE_SESSION_REVOKED: Code
CODE_SESSION_MESSAGE_MALFORMED: Code
CODE_SESSION_MESSAGE_DUPLICATE: Code
CODE_SESSION_DIRECTION: Code
CODE_SESSION_CORRELATION_MISSING: Code
CODE_SESSION_CORRELATION_UNKNOWN: Code
CODE_SCOPE_WITHHELD: Code
CODE_SCOPE_UNDECLARED: Code
CODE_STREAM_INACTIVE: Code
CODE_COMMAND_UNKNOWN: Code
CODE_QUERY_UNKNOWN: Code
CODE_FIELD_NUMBER: _ClassVar[int]
code: _descriptor.FieldDescriptor
