# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/plugin/v1/session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/plugin/v1/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yoke.plugin.v1 import families_pb2 as yoke_dot_plugin_dot_v1_dot_families__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cyoke/plugin/v1/session.proto\x12\x0eyoke.plugin.v1\x1a\x1dyoke/plugin/v1/families.proto\"\xbb\x03\n\x08\x45nvelope\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x19\n\x11sent_at_unix_nano\x18\x03 \x01(\x03\x12\x16\n\x0e\x63orrelation_id\x18\x04 \x01(\t\x12\x31\n\x07session\x18\x05 \x01(\x0b\x32\x1e.yoke.plugin.v1.SessionMessageH\x00\x12*\n\x07\x63ontrol\x18\x06 \x01(\x0b\x32\x17.yoke.plugin.v1.ControlH\x00\x12\"\n\x03\x61\x63k\x18\x07 \x01(\x0b\x32\x13.yoke.plugin.v1.AckH\x00\x12&\n\x05query\x18\x08 \x01(\x0b\x32\x15.yoke.plugin.v1.QueryH\x00\x12$\n\x04\x64\x61ta\x18\t \x01(\x0b\x32\x14.yoke.plugin.v1.DataH\x00\x12(\n\x06health\x18\n \x01(\x0b\x32\x16.yoke.plugin.v1.HealthH\x00\x12&\n\x05\x65vent\x18\x0b \x01(\x0b\x32\x15.yoke.plugin.v1.EventH\x00\x12&\n\x05\x65rror\x18\x0c \x01(\x0b\x32\x15.yoke.plugin.v1.ErrorH\x00\x42\t\n\x07payload2I\n\x07Session\x12>\n\x04Open\x12\x18.yoke.plugin.v1.Envelope\x1a\x18.yoke.plugin.v1.Envelope(\x01\x30\x01\x42<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.plugin.v1.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1'
  _globals['_ENVELOPE']._serialized_start=80
  _globals['_ENVELOPE']._serialized_end=523
  _globals['_SESSION']._serialized_start=525
  _globals['_SESSION']._serialized_end=598
# @@protoc_insertion_point(module_scope)
