# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/administrative/v1/contract.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/administrative/v1/contract.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%yoke/administrative/v1/contract.proto\x12\x16yoke.administrative.v1*:\n\x08\x43ontract\x12\x18\n\x14\x43ONTRACT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43ONTRACT_VERSION\x10\x01\x42LZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.administrative.v1.contract_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1'
  _globals['_CONTRACT']._serialized_start=65
  _globals['_CONTRACT']._serialized_end=123
# @@protoc_insertion_point(module_scope)
