# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/administrative/v1/events.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/administrative/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from yoke.administrative.v1 import codes_pb2 as yoke_dot_administrative_dot_v1_dot_codes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#yoke/administrative/v1/events.proto\x12\x16yoke.administrative.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"yoke/administrative/v1/codes.proto\"\xf1\x01\n\x05\x45vent\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x30\n\x07subject\x18\x03 \x01(\x0b\x32\x1f.yoke.administrative.v1.Subject\x12(\n\x04time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x05\x61\x63tor\x18\x05 \x01(\x0b\x32\x1d.yoke.administrative.v1.Actor\x12\x10\n\x08severity\x18\x06 \x01(\r\x12\x12\n\noccurrence\x18\x07 \x01(\t\x12\r\n\x05\x63\x61use\x18\x08 \x01(\x04\x12\x0e\n\x06\x64\x65tail\x18\t \x01(\x0c\"&\n\x05\x41\x63tor\x12\r\n\x05\x63lass\x18\x01 \x01(\t\x12\x0e\n\x06person\x18\x02 \x01(\t\"\x99\x01\n\x06\x46ilter\x12\x14\n\x0csubject_kind\x18\x01 \x01(\t\x12\x18\n\x10subject_identity\x18\x02 \x01(\t\x12\r\n\x05\x66loor\x18\x03 \x01(\r\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x13\n\x0btype_prefix\x18\x05 \x01(\x08\x12\x12\n\noccurrence\x18\x06 \x01(\t\x12\x19\n\x11occurrence_prefix\x18\x07 \x01(\x08\x42LZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.administrative.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1'
  _globals['_EVENT']._serialized_start=133
  _globals['_EVENT']._serialized_end=374
  _globals['_ACTOR']._serialized_start=376
  _globals['_ACTOR']._serialized_end=414
  _globals['_FILTER']._serialized_start=417
  _globals['_FILTER']._serialized_end=570
# @@protoc_insertion_point(module_scope)
