# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from yoke.administrative.v1 import operations_pb2 as yoke_dot_administrative_dot_v1_dot_operations__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in yoke/administrative/v1/operator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperatorStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/yoke.administrative.v1.Operator/Call',
                request_serializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.SerializeToString,
                response_deserializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/yoke.administrative.v1.Operator/Watch',
                request_serializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.SerializeToString,
                response_deserializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.FromString,
                _registered_method=True)


class OperatorServicer:
    """Missing associated documentation comment in .proto file."""

    def Call(self, request, context):
        """One operation, one answer. A refusal travels in the status, carrying the structured Refusal.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """One operation whose answer is a stream: subscribe, and log.follow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.FromString,
                    response_serializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.FromString,
                    response_serializer=yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yoke.administrative.v1.Operator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yoke.administrative.v1.Operator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Operator:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/yoke.administrative.v1.Operator/Call',
            yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.SerializeToString,
            yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/yoke.administrative.v1.Operator/Watch',
            yoke_dot_administrative_dot_v1_dot_operations__pb2.Request.SerializeToString,
            yoke_dot_administrative_dot_v1_dot_operations__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
