# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/administrative/v1/operator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/administrative/v1/operator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yoke.administrative.v1 import operations_pb2 as yoke_dot_administrative_dot_v1_dot_operations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%yoke/administrative/v1/operator.proto\x12\x16yoke.administrative.v1\x1a\'yoke/administrative/v1/operations.proto2\xa3\x01\n\x08Operator\x12I\n\x04\x43\x61ll\x12\x1f.yoke.administrative.v1.Request\x1a .yoke.administrative.v1.Response\x12L\n\x05Watch\x12\x1f.yoke.administrative.v1.Request\x1a .yoke.administrative.v1.Response0\x01\x42LZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.administrative.v1.operator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1'
  _globals['_OPERATOR']._serialized_start=107
  _globals['_OPERATOR']._serialized_end=270
# @@protoc_insertion_point(module_scope)
