# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yoke/administrative/v1/shell.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'yoke/administrative/v1/shell.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yoke.administrative.v1 import codes_pb2 as yoke_dot_administrative_dot_v1_dot_codes__pb2
from yoke.administrative.v1 import events_pb2 as yoke_dot_administrative_dot_v1_dot_events__pb2
from yoke.administrative.v1 import operations_pb2 as yoke_dot_administrative_dot_v1_dot_operations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"yoke/administrative/v1/shell.proto\x12\x16yoke.administrative.v1\x1a\"yoke/administrative/v1/codes.proto\x1a#yoke/administrative/v1/events.proto\x1a\'yoke/administrative/v1/operations.proto\"\x8c\x01\n\x0b\x43lientFrame\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12\x32\n\x07request\x18\x02 \x01(\x0b\x32\x1f.yoke.administrative.v1.RequestH\x00\x12\x30\n\x06\x63\x61ncel\x18\x03 \x01(\x0b\x32\x1e.yoke.administrative.v1.CancelH\x00\x42\t\n\x07\x63\x61rries\"\x08\n\x06\x43\x61ncel\"\xaa\x02\n\tCoreFrame\x12\x0c\n\x04\x63\x61ll\x18\x01 \x01(\t\x12\x32\n\x07opening\x18\x02 \x01(\x0b\x32\x1f.yoke.administrative.v1.OpeningH\x00\x12\x32\n\x06\x61nswer\x18\x03 \x01(\x0b\x32 .yoke.administrative.v1.ResponseH\x00\x12.\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x1d.yoke.administrative.v1.EventH\x00\x12\x32\n\x07refusal\x18\x05 \x01(\x0b\x32\x1f.yoke.administrative.v1.RefusalH\x00\x12\x38\n\ncompletion\x18\x06 \x01(\x0b\x32\".yoke.administrative.v1.CompletionH\x00\x42\t\n\x07\x63\x61rries\"r\n\x07Opening\x12\x12\n\nconnection\x18\x01 \x01(\t\x12,\n\x05\x61\x63tor\x18\x02 \x01(\x0b\x32\x1d.yoke.administrative.v1.Actor\x12\x14\n\x0csubscription\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\r\"\x0c\n\nCompletion2^\n\x05Shell\x12U\n\x07\x43onnect\x12#.yoke.administrative.v1.ClientFrame\x1a!.yoke.administrative.v1.CoreFrame(\x01\x30\x01\x42LZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoke.administrative.v1.shell_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/yoke-project/yoke/proto/yoke/administrative/v1;administrativev1'
  _globals['_CLIENTFRAME']._serialized_start=177
  _globals['_CLIENTFRAME']._serialized_end=317
  _globals['_CANCEL']._serialized_start=319
  _globals['_CANCEL']._serialized_end=327
  _globals['_COREFRAME']._serialized_start=330
  _globals['_COREFRAME']._serialized_end=628
  _globals['_OPENING']._serialized_start=630
  _globals['_OPENING']._serialized_end=744
  _globals['_COMPLETION']._serialized_start=746
  _globals['_COMPLETION']._serialized_end=758
  _globals['_SHELL']._serialized_start=760
  _globals['_SHELL']._serialized_end=854
# @@protoc_insertion_point(module_scope)
