// This surface's error codes. On the wire a code is
// its dotted name, which grows under a grammar across every surface; this enum is where every party reads
// the names from, each stated in its `code` option, and a code's meaning never changes under its name.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/plugin/v1/codes.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_CODE_UNSPECIFIED Code = 0
	// The request does not decode, or a required field is absent.
	Code_CODE_ADMISSION_STRUCTURAL_MALFORMED Code = 1
	// The Registry has no such plugin.
	Code_CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN Code = 2
	// No document composes this unit.
	Code_CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT Code = 3
	// An operator disabled the plugin.
	Code_CODE_ADMISSION_STATE_DISABLED Code = 4
	// The token is not this Core's, or not for this pair.
	Code_CODE_ADMISSION_AUTH_INVALID Code = 5
	// The startup window has passed.
	Code_CODE_ADMISSION_AUTH_EXPIRED Code = 6
	// The token has already been spent.
	Code_CODE_ADMISSION_AUTH_CONSUMED Code = 7
	// The protocol version is absent, or this Core does not support it.
	Code_CODE_ADMISSION_COMPAT_UNSUPPORTED Code = 8
	// The process describes itself differently from its Manifest.
	Code_CODE_ADMISSION_CONSISTENCY_DIVERGENT Code = 9
	// This unit is already live.
	Code_CODE_ADMISSION_CONFLICT_UNIT_LIVE Code = 10
	// The acceptance could not be turned into an enforceable Session.
	Code_CODE_ADMISSION_SESSION_UNAVAILABLE Code = 11
	// The identity in a first envelope was never issued, is already used, or has ended.
	Code_CODE_SESSION_UNKNOWN Code = 12
	// The Session ended before this message arrived.
	Code_CODE_SESSION_REVOKED Code = 13
	// An envelope carries no payload, or a field exceeds its bound.
	Code_CODE_SESSION_MESSAGE_MALFORMED Code = 14
	// A message identity repeated within one Session.
	Code_CODE_SESSION_MESSAGE_DUPLICATE Code = 15
	// A family arrived from the side that may not originate it.
	Code_CODE_SESSION_DIRECTION Code = 16
	// A family that must correlate did not.
	Code_CODE_SESSION_CORRELATION_MISSING Code = 17
	// A correlation names no message in this Session.
	Code_CODE_SESSION_CORRELATION_UNKNOWN Code = 18
	// The operation names something declared but not authorised.
	Code_CODE_SCOPE_WITHHELD Code = 19
	// It names something the process never declared.
	Code_CODE_SCOPE_UNDECLARED Code = 20
	// Data arrived for a stream that is not activated.
	Code_CODE_STREAM_INACTIVE Code = 21
	// An acknowledgement names a command that was never issued.
	Code_CODE_COMMAND_UNKNOWN Code = 22
	// A response names a question that was never asked.
	Code_CODE_QUERY_UNKNOWN Code = 23
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "CODE_UNSPECIFIED",
		1:  "CODE_ADMISSION_STRUCTURAL_MALFORMED",
		2:  "CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN",
		3:  "CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT",
		4:  "CODE_ADMISSION_STATE_DISABLED",
		5:  "CODE_ADMISSION_AUTH_INVALID",
		6:  "CODE_ADMISSION_AUTH_EXPIRED",
		7:  "CODE_ADMISSION_AUTH_CONSUMED",
		8:  "CODE_ADMISSION_COMPAT_UNSUPPORTED",
		9:  "CODE_ADMISSION_CONSISTENCY_DIVERGENT",
		10: "CODE_ADMISSION_CONFLICT_UNIT_LIVE",
		11: "CODE_ADMISSION_SESSION_UNAVAILABLE",
		12: "CODE_SESSION_UNKNOWN",
		13: "CODE_SESSION_REVOKED",
		14: "CODE_SESSION_MESSAGE_MALFORMED",
		15: "CODE_SESSION_MESSAGE_DUPLICATE",
		16: "CODE_SESSION_DIRECTION",
		17: "CODE_SESSION_CORRELATION_MISSING",
		18: "CODE_SESSION_CORRELATION_UNKNOWN",
		19: "CODE_SCOPE_WITHHELD",
		20: "CODE_SCOPE_UNDECLARED",
		21: "CODE_STREAM_INACTIVE",
		22: "CODE_COMMAND_UNKNOWN",
		23: "CODE_QUERY_UNKNOWN",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED":                       0,
		"CODE_ADMISSION_STRUCTURAL_MALFORMED":    1,
		"CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN": 2,
		"CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT":   3,
		"CODE_ADMISSION_STATE_DISABLED":          4,
		"CODE_ADMISSION_AUTH_INVALID":            5,
		"CODE_ADMISSION_AUTH_EXPIRED":            6,
		"CODE_ADMISSION_AUTH_CONSUMED":           7,
		"CODE_ADMISSION_COMPAT_UNSUPPORTED":      8,
		"CODE_ADMISSION_CONSISTENCY_DIVERGENT":   9,
		"CODE_ADMISSION_CONFLICT_UNIT_LIVE":      10,
		"CODE_ADMISSION_SESSION_UNAVAILABLE":     11,
		"CODE_SESSION_UNKNOWN":                   12,
		"CODE_SESSION_REVOKED":                   13,
		"CODE_SESSION_MESSAGE_MALFORMED":         14,
		"CODE_SESSION_MESSAGE_DUPLICATE":         15,
		"CODE_SESSION_DIRECTION":                 16,
		"CODE_SESSION_CORRELATION_MISSING":       17,
		"CODE_SESSION_CORRELATION_UNKNOWN":       18,
		"CODE_SCOPE_WITHHELD":                    19,
		"CODE_SCOPE_UNDECLARED":                  20,
		"CODE_STREAM_INACTIVE":                   21,
		"CODE_COMMAND_UNKNOWN":                   22,
		"CODE_QUERY_UNKNOWN":                     23,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_codes_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_codes_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_codes_proto_rawDescGZIP(), []int{0}
}

var file_yoke_plugin_v1_codes_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "yoke.plugin.v1.code",
		Tag:           "bytes,50000,opt,name=code",
		Filename:      "yoke/plugin/v1/codes.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// The code's dotted name, as it travels.
	//
	// optional string code = 50000;
	E_Code = &file_yoke_plugin_v1_codes_proto_extTypes[0]
)

var File_yoke_plugin_v1_codes_proto protoreflect.FileDescriptor

const file_yoke_plugin_v1_codes_proto_rawDesc = "" +
	"\n" +
	"\x1ayoke/plugin/v1/codes.proto\x12\x0eyoke.plugin.v1\x1a google/protobuf/descriptor.proto*\xbd\v\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12K\n" +
	"#CODE_ADMISSION_STRUCTURAL_MALFORMED\x10\x01\x1a\"\x82\xb5\x18\x1eadmission.structural.malformed\x12Q\n" +
	"&CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN\x10\x02\x1a%\x82\xb5\x18!admission.identity.unknown_plugin\x12M\n" +
	"$CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT\x10\x03\x1a#\x82\xb5\x18\x1fadmission.identity.unknown_unit\x12?\n" +
	"\x1dCODE_ADMISSION_STATE_DISABLED\x10\x04\x1a\x1c\x82\xb5\x18\x18admission.state.disabled\x12;\n" +
	"\x1bCODE_ADMISSION_AUTH_INVALID\x10\x05\x1a\x1a\x82\xb5\x18\x16admission.auth.invalid\x12;\n" +
	"\x1bCODE_ADMISSION_AUTH_EXPIRED\x10\x06\x1a\x1a\x82\xb5\x18\x16admission.auth.expired\x12=\n" +
	"\x1cCODE_ADMISSION_AUTH_CONSUMED\x10\a\x1a\x1b\x82\xb5\x18\x17admission.auth.consumed\x12G\n" +
	"!CODE_ADMISSION_COMPAT_UNSUPPORTED\x10\b\x1a \x82\xb5\x18\x1cadmission.compat.unsupported\x12M\n" +
	"$CODE_ADMISSION_CONSISTENCY_DIVERGENT\x10\t\x1a#\x82\xb5\x18\x1fadmission.consistency.divergent\x12G\n" +
	"!CODE_ADMISSION_CONFLICT_UNIT_LIVE\x10\n" +
	"\x1a \x82\xb5\x18\x1cadmission.conflict.unit_live\x12I\n" +
	"\"CODE_ADMISSION_SESSION_UNAVAILABLE\x10\v\x1a!\x82\xb5\x18\x1dadmission.session.unavailable\x12-\n" +
	"\x14CODE_SESSION_UNKNOWN\x10\f\x1a\x13\x82\xb5\x18\x0fsession.unknown\x12-\n" +
	"\x14CODE_SESSION_REVOKED\x10\r\x1a\x13\x82\xb5\x18\x0fsession.revoked\x12A\n" +
	"\x1eCODE_SESSION_MESSAGE_MALFORMED\x10\x0e\x1a\x1d\x82\xb5\x18\x19session.message.malformed\x12A\n" +
	"\x1eCODE_SESSION_MESSAGE_DUPLICATE\x10\x0f\x1a\x1d\x82\xb5\x18\x19session.message.duplicate\x121\n" +
	"\x16CODE_SESSION_DIRECTION\x10\x10\x1a\x15\x82\xb5\x18\x11session.direction\x12E\n" +
	" CODE_SESSION_CORRELATION_MISSING\x10\x11\x1a\x1f\x82\xb5\x18\x1bsession.correlation.missing\x12E\n" +
	" CODE_SESSION_CORRELATION_UNKNOWN\x10\x12\x1a\x1f\x82\xb5\x18\x1bsession.correlation.unknown\x12+\n" +
	"\x13CODE_SCOPE_WITHHELD\x10\x13\x1a\x12\x82\xb5\x18\x0escope.withheld\x12/\n" +
	"\x15CODE_SCOPE_UNDECLARED\x10\x14\x1a\x14\x82\xb5\x18\x10scope.undeclared\x12-\n" +
	"\x14CODE_STREAM_INACTIVE\x10\x15\x1a\x13\x82\xb5\x18\x0fstream.inactive\x12-\n" +
	"\x14CODE_COMMAND_UNKNOWN\x10\x16\x1a\x13\x82\xb5\x18\x0fcommand.unknown\x12)\n" +
	"\x12CODE_QUERY_UNKNOWN\x10\x17\x1a\x11\x82\xb5\x18\rquery.unknown:7\n" +
	"\x04code\x12!.google.protobuf.EnumValueOptions\x18І\x03 \x01(\tR\x04codeB<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3"

var (
	file_yoke_plugin_v1_codes_proto_rawDescOnce sync.Once
	file_yoke_plugin_v1_codes_proto_rawDescData []byte
)

func file_yoke_plugin_v1_codes_proto_rawDescGZIP() []byte {
	file_yoke_plugin_v1_codes_proto_rawDescOnce.Do(func() {
		file_yoke_plugin_v1_codes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_codes_proto_rawDesc), len(file_yoke_plugin_v1_codes_proto_rawDesc)))
	})
	return file_yoke_plugin_v1_codes_proto_rawDescData
}

var file_yoke_plugin_v1_codes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_plugin_v1_codes_proto_goTypes = []any{
	(Code)(0),                             // 0: yoke.plugin.v1.Code
	(*descriptorpb.EnumValueOptions)(nil), // 1: google.protobuf.EnumValueOptions
}
var file_yoke_plugin_v1_codes_proto_depIdxs = []int32{
	1, // 0: yoke.plugin.v1.code:extendee -> google.protobuf.EnumValueOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yoke_plugin_v1_codes_proto_init() }
func file_yoke_plugin_v1_codes_proto_init() {
	if File_yoke_plugin_v1_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_codes_proto_rawDesc), len(file_yoke_plugin_v1_codes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_yoke_plugin_v1_codes_proto_goTypes,
		DependencyIndexes: file_yoke_plugin_v1_codes_proto_depIdxs,
		EnumInfos:         file_yoke_plugin_v1_codes_proto_enumTypes,
		ExtensionInfos:    file_yoke_plugin_v1_codes_proto_extTypes,
	}.Build()
	File_yoke_plugin_v1_codes_proto = out.File
	file_yoke_plugin_v1_codes_proto_goTypes = nil
	file_yoke_plugin_v1_codes_proto_depIdxs = nil
}
