// The plugin contract's version, stated inside the contract. It is the integer a unit sends at
// registration, and it is the `v1` of this path: a contract whose two differ is rejected where the
// definitions are built.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/plugin/v1/contract.proto

// The plugin contract, v1: what each message carries and why is described at
// https://docs.yoke-project.dev/reference/plugin-surface/the-wire/.

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contract int32

const (
	Contract_CONTRACT_UNSPECIFIED Contract = 0
	Contract_CONTRACT_VERSION     Contract = 1
)

// Enum value maps for Contract.
var (
	Contract_name = map[int32]string{
		0: "CONTRACT_UNSPECIFIED",
		1: "CONTRACT_VERSION",
	}
	Contract_value = map[string]int32{
		"CONTRACT_UNSPECIFIED": 0,
		"CONTRACT_VERSION":     1,
	}
)

func (x Contract) Enum() *Contract {
	p := new(Contract)
	*p = x
	return p
}

func (x Contract) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Contract) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_contract_proto_enumTypes[0].Descriptor()
}

func (Contract) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_contract_proto_enumTypes[0]
}

func (x Contract) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Contract.Descriptor instead.
func (Contract) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_contract_proto_rawDescGZIP(), []int{0}
}

var File_yoke_plugin_v1_contract_proto protoreflect.FileDescriptor

const file_yoke_plugin_v1_contract_proto_rawDesc = "" +
	"\n" +
	"\x1dyoke/plugin/v1/contract.proto\x12\x0eyoke.plugin.v1*:\n" +
	"\bContract\x12\x18\n" +
	"\x14CONTRACT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CONTRACT_VERSION\x10\x01B<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3"

var (
	file_yoke_plugin_v1_contract_proto_rawDescOnce sync.Once
	file_yoke_plugin_v1_contract_proto_rawDescData []byte
)

func file_yoke_plugin_v1_contract_proto_rawDescGZIP() []byte {
	file_yoke_plugin_v1_contract_proto_rawDescOnce.Do(func() {
		file_yoke_plugin_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_contract_proto_rawDesc), len(file_yoke_plugin_v1_contract_proto_rawDesc)))
	})
	return file_yoke_plugin_v1_contract_proto_rawDescData
}

var file_yoke_plugin_v1_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_yoke_plugin_v1_contract_proto_goTypes = []any{
	(Contract)(0), // 0: yoke.plugin.v1.Contract
}
var file_yoke_plugin_v1_contract_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_yoke_plugin_v1_contract_proto_init() }
func file_yoke_plugin_v1_contract_proto_init() {
	if File_yoke_plugin_v1_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_contract_proto_rawDesc), len(file_yoke_plugin_v1_contract_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_plugin_v1_contract_proto_goTypes,
		DependencyIndexes: file_yoke_plugin_v1_contract_proto_depIdxs,
		EnumInfos:         file_yoke_plugin_v1_contract_proto_enumTypes,
	}.Build()
	File_yoke_plugin_v1_contract_proto = out.File
	file_yoke_plugin_v1_contract_proto_goTypes = nil
	file_yoke_plugin_v1_contract_proto_depIdxs = nil
}
