// The eight payloads, one per family. An opaque payload is carried and
// never decoded, bounded at 1 MiB; a line is for a person, bounded at 1 KiB.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/plugin/v1/families.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionMessage_Revoked_Cause int32

const (
	SessionMessage_Revoked_CAUSE_UNSPECIFIED      SessionMessage_Revoked_Cause = 0
	SessionMessage_Revoked_CAUSE_LIVENESS_LOST    SessionMessage_Revoked_Cause = 1
	SessionMessage_Revoked_CAUSE_PLUGIN_DISABLED  SessionMessage_Revoked_Cause = 2
	SessionMessage_Revoked_CAUSE_SCOPE_EXCEEDED   SessionMessage_Revoked_Cause = 3
	SessionMessage_Revoked_CAUSE_PROTOCOL_FAILURE SessionMessage_Revoked_Cause = 4
)

// Enum value maps for SessionMessage_Revoked_Cause.
var (
	SessionMessage_Revoked_Cause_name = map[int32]string{
		0: "CAUSE_UNSPECIFIED",
		1: "CAUSE_LIVENESS_LOST",
		2: "CAUSE_PLUGIN_DISABLED",
		3: "CAUSE_SCOPE_EXCEEDED",
		4: "CAUSE_PROTOCOL_FAILURE",
	}
	SessionMessage_Revoked_Cause_value = map[string]int32{
		"CAUSE_UNSPECIFIED":      0,
		"CAUSE_LIVENESS_LOST":    1,
		"CAUSE_PLUGIN_DISABLED":  2,
		"CAUSE_SCOPE_EXCEEDED":   3,
		"CAUSE_PROTOCOL_FAILURE": 4,
	}
)

func (x SessionMessage_Revoked_Cause) Enum() *SessionMessage_Revoked_Cause {
	p := new(SessionMessage_Revoked_Cause)
	*p = x
	return p
}

func (x SessionMessage_Revoked_Cause) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionMessage_Revoked_Cause) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_families_proto_enumTypes[0].Descriptor()
}

func (SessionMessage_Revoked_Cause) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_families_proto_enumTypes[0]
}

func (x SessionMessage_Revoked_Cause) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionMessage_Revoked_Cause.Descriptor instead.
func (SessionMessage_Revoked_Cause) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{0, 2, 0}
}

type Control_Activate_Transport int32

const (
	Control_Activate_TRANSPORT_UNSPECIFIED   Control_Activate_Transport = 0
	Control_Activate_TRANSPORT_ORDERED       Control_Activate_Transport = 1
	Control_Activate_TRANSPORT_FRAMED        Control_Activate_Transport = 2
	Control_Activate_TRANSPORT_SHARED_OBJECT Control_Activate_Transport = 3
)

// Enum value maps for Control_Activate_Transport.
var (
	Control_Activate_Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_ORDERED",
		2: "TRANSPORT_FRAMED",
		3: "TRANSPORT_SHARED_OBJECT",
	}
	Control_Activate_Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED":   0,
		"TRANSPORT_ORDERED":       1,
		"TRANSPORT_FRAMED":        2,
		"TRANSPORT_SHARED_OBJECT": 3,
	}
)

func (x Control_Activate_Transport) Enum() *Control_Activate_Transport {
	p := new(Control_Activate_Transport)
	*p = x
	return p
}

func (x Control_Activate_Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Control_Activate_Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_families_proto_enumTypes[1].Descriptor()
}

func (Control_Activate_Transport) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_families_proto_enumTypes[1]
}

func (x Control_Activate_Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Control_Activate_Transport.Descriptor instead.
func (Control_Activate_Transport) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{1, 1, 0}
}

type Ack_Outcome int32

const (
	Ack_OUTCOME_UNSPECIFIED Ack_Outcome = 0
	Ack_OUTCOME_ACCEPTED    Ack_Outcome = 1
	Ack_OUTCOME_DONE        Ack_Outcome = 2
	Ack_OUTCOME_FAILED      Ack_Outcome = 3
)

// Enum value maps for Ack_Outcome.
var (
	Ack_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_DONE",
		3: "OUTCOME_FAILED",
	}
	Ack_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_ACCEPTED":    1,
		"OUTCOME_DONE":        2,
		"OUTCOME_FAILED":      3,
	}
)

func (x Ack_Outcome) Enum() *Ack_Outcome {
	p := new(Ack_Outcome)
	*p = x
	return p
}

func (x Ack_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_families_proto_enumTypes[2].Descriptor()
}

func (Ack_Outcome) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_families_proto_enumTypes[2]
}

func (x Ack_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack_Outcome.Descriptor instead.
func (Ack_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{2, 0}
}

type SessionMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*SessionMessage_Open_
	//	*SessionMessage_Close_
	//	*SessionMessage_Revoked_
	Kind          isSessionMessage_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{0}
}

func (x *SessionMessage) GetKind() isSessionMessage_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *SessionMessage) GetOpen() *SessionMessage_Open {
	if x != nil {
		if x, ok := x.Kind.(*SessionMessage_Open_); ok {
			return x.Open
		}
	}
	return nil
}

func (x *SessionMessage) GetClose() *SessionMessage_Close {
	if x != nil {
		if x, ok := x.Kind.(*SessionMessage_Close_); ok {
			return x.Close
		}
	}
	return nil
}

func (x *SessionMessage) GetRevoked() *SessionMessage_Revoked {
	if x != nil {
		if x, ok := x.Kind.(*SessionMessage_Revoked_); ok {
			return x.Revoked
		}
	}
	return nil
}

type isSessionMessage_Kind interface {
	isSessionMessage_Kind()
}

type SessionMessage_Open_ struct {
	Open *SessionMessage_Open `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type SessionMessage_Close_ struct {
	Close *SessionMessage_Close `protobuf:"bytes,2,opt,name=close,proto3,oneof"`
}

type SessionMessage_Revoked_ struct {
	Revoked *SessionMessage_Revoked `protobuf:"bytes,3,opt,name=revoked,proto3,oneof"`
}

func (*SessionMessage_Open_) isSessionMessage_Kind() {}

func (*SessionMessage_Close_) isSessionMessage_Kind() {}

func (*SessionMessage_Revoked_) isSessionMessage_Kind() {}

// From the Core: what this unit should do.
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Control_Command_
	//	*Control_Activate_
	//	*Control_Stop_
	Kind          isControl_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{1}
}

func (x *Control) GetKind() isControl_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Control) GetCommand() *Control_Command {
	if x != nil {
		if x, ok := x.Kind.(*Control_Command_); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Control) GetActivate() *Control_Activate {
	if x != nil {
		if x, ok := x.Kind.(*Control_Activate_); ok {
			return x.Activate
		}
	}
	return nil
}

func (x *Control) GetStop() *Control_Stop {
	if x != nil {
		if x, ok := x.Kind.(*Control_Stop_); ok {
			return x.Stop
		}
	}
	return nil
}

type isControl_Kind interface {
	isControl_Kind()
}

type Control_Command_ struct {
	Command *Control_Command `protobuf:"bytes,1,opt,name=command,proto3,oneof"`
}

type Control_Activate_ struct {
	Activate *Control_Activate `protobuf:"bytes,2,opt,name=activate,proto3,oneof"`
}

type Control_Stop_ struct {
	Stop *Control_Stop `protobuf:"bytes,3,opt,name=stop,proto3,oneof"`
}

func (*Control_Command_) isControl_Kind() {}

func (*Control_Activate_) isControl_Kind() {}

func (*Control_Stop_) isControl_Kind() {}

// From the unit, correlated: what became of that instruction. An acceptance is followed by at most one
// final answer, and no acknowledgement carries a domain result.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       Ack_Outcome            `protobuf:"varint,1,opt,name=outcome,proto3,enum=yoke.plugin.v1.Ack_Outcome" json:"outcome,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOutcome() Ack_Outcome {
	if x != nil {
		return x.Outcome
	}
	return Ack_OUTCOME_UNSPECIFIED
}

func (x *Ack) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// A question from the Core, and the unit's answer, correlated to it.
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Query_Question_
	//	*Query_Answer_
	Kind          isQuery_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{3}
}

func (x *Query) GetKind() isQuery_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Query) GetQuestion() *Query_Question {
	if x != nil {
		if x, ok := x.Kind.(*Query_Question_); ok {
			return x.Question
		}
	}
	return nil
}

func (x *Query) GetAnswer() *Query_Answer {
	if x != nil {
		if x, ok := x.Kind.(*Query_Answer_); ok {
			return x.Answer
		}
	}
	return nil
}

type isQuery_Kind interface {
	isQuery_Kind()
}

type Query_Question_ struct {
	Question *Query_Question `protobuf:"bytes,1,opt,name=question,proto3,oneof"`
}

type Query_Answer_ struct {
	Answer *Query_Answer `protobuf:"bytes,2,opt,name=answer,proto3,oneof"`
}

func (*Query_Question_) isQuery_Kind() {}

func (*Query_Answer_) isQuery_Kind() {}

// What a stream produces. Never on the Session: only on its own ordered transport, which names the
// stream. The sequence is per stream, from 1, never reused within an activation.
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Alive, and how well: a grade from 0 to 99, and a line.
type Health struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grade         uint32                 `protobuf:"varint,1,opt,name=grade,proto3" json:"grade,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Health) Reset() {
	*x = Health{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Health) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Health) ProtoMessage() {}

func (x *Health) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Health.ProtoReflect.Descriptor instead.
func (*Health) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{5}
}

func (x *Health) GetGrade() uint32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Health) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// What just happened: a class the unit declared and was granted, a severity from 0 to 99 the unit
// declares, a line, and a detail the Core carries into the event unchanged.
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Occurrence    string                 `protobuf:"bytes,1,opt,name=occurrence,proto3" json:"occurrence,omitempty"`
	Severity      uint32                 `protobuf:"varint,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	Detail        []byte                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{6}
}

func (x *Event) GetOccurrence() string {
	if x != nil {
		return x.Occurrence
	}
	return ""
}

func (x *Event) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *Event) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Event) GetDetail() []byte {
	if x != nil {
		return x.Detail
	}
	return nil
}

// What went wrong: a code, one of Code's names; a message for a person; a detail typed per code.
type Error struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Detail:
	//
	//	*Error_Divergent
	//	*Error_Withheld_
	Detail        isError_Detail `protobuf_oneof:"detail"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{7}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetail() isError_Detail {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *Error) GetDivergent() *Error_Divergence {
	if x != nil {
		if x, ok := x.Detail.(*Error_Divergent); ok {
			return x.Divergent
		}
	}
	return nil
}

func (x *Error) GetWithheld() *Error_Withheld {
	if x != nil {
		if x, ok := x.Detail.(*Error_Withheld_); ok {
			return x.Withheld
		}
	}
	return nil
}

type isError_Detail interface {
	isError_Detail()
}

type Error_Divergent struct {
	Divergent *Error_Divergence `protobuf:"bytes,3,opt,name=divergent,proto3,oneof"`
}

type Error_Withheld_ struct {
	Withheld *Error_Withheld `protobuf:"bytes,4,opt,name=withheld,proto3,oneof"`
}

func (*Error_Divergent) isError_Detail() {}

func (*Error_Withheld_) isError_Detail() {}

// The first envelope on the stream, from the unit.
type SessionMessage_Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage_Open) Reset() {
	*x = SessionMessage_Open{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage_Open) ProtoMessage() {}

func (x *SessionMessage_Open) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage_Open.ProtoReflect.Descriptor instead.
func (*SessionMessage_Open) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{0, 0}
}

// The unit's orderly departure.
type SessionMessage_Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage_Close) Reset() {
	*x = SessionMessage_Close{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage_Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage_Close) ProtoMessage() {}

func (x *SessionMessage_Close) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage_Close.ProtoReflect.Descriptor instead.
func (*SessionMessage_Close) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{0, 1}
}

// The Core ending the Session, and why.
type SessionMessage_Revoked struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Cause         SessionMessage_Revoked_Cause `protobuf:"varint,1,opt,name=cause,proto3,enum=yoke.plugin.v1.SessionMessage_Revoked_Cause" json:"cause,omitempty"`
	Line          string                       `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage_Revoked) Reset() {
	*x = SessionMessage_Revoked{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage_Revoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage_Revoked) ProtoMessage() {}

func (x *SessionMessage_Revoked) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage_Revoked.ProtoReflect.Descriptor instead.
func (*SessionMessage_Revoked) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SessionMessage_Revoked) GetCause() SessionMessage_Revoked_Cause {
	if x != nil {
		return x.Cause
	}
	return SessionMessage_Revoked_CAUSE_UNSPECIFIED
}

func (x *SessionMessage_Revoked) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

// A command type the unit declared, and its payload.
type Control_Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control_Command) Reset() {
	*x = Control_Command{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control_Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control_Command) ProtoMessage() {}

func (x *Control_Command) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control_Command.ProtoReflect.Descriptor instead.
func (*Control_Command) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Control_Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Control_Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// A stream's activation: what the unit connects to, and how it frames what it sends.
type Control_Activate struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Stream        string                     `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Transport     Control_Activate_Transport `protobuf:"varint,2,opt,name=transport,proto3,enum=yoke.plugin.v1.Control_Activate_Transport" json:"transport,omitempty"`
	Address       string                     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control_Activate) Reset() {
	*x = Control_Activate{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control_Activate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control_Activate) ProtoMessage() {}

func (x *Control_Activate) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control_Activate.ProtoReflect.Descriptor instead.
func (*Control_Activate) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Control_Activate) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *Control_Activate) GetTransport() Control_Activate_Transport {
	if x != nil {
		return x.Transport
	}
	return Control_Activate_TRANSPORT_UNSPECIFIED
}

func (x *Control_Activate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The instruction that stops a stream.
type Control_Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control_Stop) Reset() {
	*x = Control_Stop{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control_Stop) ProtoMessage() {}

func (x *Control_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control_Stop.ProtoReflect.Descriptor instead.
func (*Control_Stop) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{1, 2}
}

func (x *Control_Stop) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

type Query_Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query_Question) Reset() {
	*x = Query_Question{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Question) ProtoMessage() {}

func (x *Query_Question) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Question.ProtoReflect.Descriptor instead.
func (*Query_Question) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Query_Question) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Query_Question) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Query_Answer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query_Answer) Reset() {
	*x = Query_Answer{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query_Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query_Answer) ProtoMessage() {}

func (x *Query_Answer) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query_Answer.ProtoReflect.Descriptor instead.
func (*Query_Answer) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Query_Answer) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// Each item that differs between a process and its Manifest.
type Error_Divergence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []string               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error_Divergence) Reset() {
	*x = Error_Divergence{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error_Divergence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error_Divergence) ProtoMessage() {}

func (x *Error_Divergence) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error_Divergence.ProtoReflect.Descriptor instead.
func (*Error_Divergence) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Error_Divergence) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// The item declared and not authorised.
type Error_Withheld struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          string                 `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error_Withheld) Reset() {
	*x = Error_Withheld{}
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error_Withheld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error_Withheld) ProtoMessage() {}

func (x *Error_Withheld) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_families_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error_Withheld.ProtoReflect.Descriptor instead.
func (*Error_Withheld) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_families_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Error_Withheld) GetItem() string {
	if x != nil {
		return x.Item
	}
	return ""
}

var File_yoke_plugin_v1_families_proto protoreflect.FileDescriptor

const file_yoke_plugin_v1_families_proto_rawDesc = "" +
	"\n" +
	"\x1dyoke/plugin/v1/families.proto\x12\x0eyoke.plugin.v1\"\xd5\x03\n" +
	"\x0eSessionMessage\x129\n" +
	"\x04open\x18\x01 \x01(\v2#.yoke.plugin.v1.SessionMessage.OpenH\x00R\x04open\x12<\n" +
	"\x05close\x18\x02 \x01(\v2$.yoke.plugin.v1.SessionMessage.CloseH\x00R\x05close\x12B\n" +
	"\arevoked\x18\x03 \x01(\v2&.yoke.plugin.v1.SessionMessage.RevokedH\x00R\arevoked\x1a\x06\n" +
	"\x04Open\x1a\a\n" +
	"\x05Close\x1a\xec\x01\n" +
	"\aRevoked\x12B\n" +
	"\x05cause\x18\x01 \x01(\x0e2,.yoke.plugin.v1.SessionMessage.Revoked.CauseR\x05cause\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"\x88\x01\n" +
	"\x05Cause\x12\x15\n" +
	"\x11CAUSE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CAUSE_LIVENESS_LOST\x10\x01\x12\x19\n" +
	"\x15CAUSE_PLUGIN_DISABLED\x10\x02\x12\x18\n" +
	"\x14CAUSE_SCOPE_EXCEEDED\x10\x03\x12\x1a\n" +
	"\x16CAUSE_PROTOCOL_FAILURE\x10\x04B\x06\n" +
	"\x04kind\"\x96\x04\n" +
	"\aControl\x12;\n" +
	"\acommand\x18\x01 \x01(\v2\x1f.yoke.plugin.v1.Control.CommandH\x00R\acommand\x12>\n" +
	"\bactivate\x18\x02 \x01(\v2 .yoke.plugin.v1.Control.ActivateH\x00R\bactivate\x122\n" +
	"\x04stop\x18\x03 \x01(\v2\x1c.yoke.plugin.v1.Control.StopH\x00R\x04stop\x1a7\n" +
	"\aCommand\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x1a\xf8\x01\n" +
	"\bActivate\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12H\n" +
	"\ttransport\x18\x02 \x01(\x0e2*.yoke.plugin.v1.Control.Activate.TransportR\ttransport\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"p\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TRANSPORT_ORDERED\x10\x01\x12\x14\n" +
	"\x10TRANSPORT_FRAMED\x10\x02\x12\x1b\n" +
	"\x17TRANSPORT_SHARED_OBJECT\x10\x03\x1a\x1e\n" +
	"\x04Stop\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06streamB\x06\n" +
	"\x04kind\"\xb0\x01\n" +
	"\x03Ack\x125\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x1b.yoke.plugin.v1.Ack.OutcomeR\aoutcome\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"^\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12\x10\n" +
	"\fOUTCOME_DONE\x10\x02\x12\x12\n" +
	"\x0eOUTCOME_FAILED\x10\x03\"\xe3\x01\n" +
	"\x05Query\x12<\n" +
	"\bquestion\x18\x01 \x01(\v2\x1e.yoke.plugin.v1.Query.QuestionH\x00R\bquestion\x126\n" +
	"\x06answer\x18\x02 \x01(\v2\x1c.yoke.plugin.v1.Query.AnswerH\x00R\x06answer\x1a8\n" +
	"\bQuestion\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x1a\"\n" +
	"\x06Answer\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayloadB\x06\n" +
	"\x04kind\"<\n" +
	"\x04Data\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"2\n" +
	"\x06Health\x12\x14\n" +
	"\x05grade\x18\x01 \x01(\rR\x05grade\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\"o\n" +
	"\x05Event\x12\x1e\n" +
	"\n" +
	"occurrence\x18\x01 \x01(\tR\n" +
	"occurrence\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\rR\bseverity\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\fR\x06detail\"\x83\x02\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\tdivergent\x18\x03 \x01(\v2 .yoke.plugin.v1.Error.DivergenceH\x00R\tdivergent\x12<\n" +
	"\bwithheld\x18\x04 \x01(\v2\x1e.yoke.plugin.v1.Error.WithheldH\x00R\bwithheld\x1a\"\n" +
	"\n" +
	"Divergence\x12\x14\n" +
	"\x05items\x18\x01 \x03(\tR\x05items\x1a\x1e\n" +
	"\bWithheld\x12\x12\n" +
	"\x04item\x18\x01 \x01(\tR\x04itemB\b\n" +
	"\x06detailB<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3"

var (
	file_yoke_plugin_v1_families_proto_rawDescOnce sync.Once
	file_yoke_plugin_v1_families_proto_rawDescData []byte
)

func file_yoke_plugin_v1_families_proto_rawDescGZIP() []byte {
	file_yoke_plugin_v1_families_proto_rawDescOnce.Do(func() {
		file_yoke_plugin_v1_families_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_families_proto_rawDesc), len(file_yoke_plugin_v1_families_proto_rawDesc)))
	})
	return file_yoke_plugin_v1_families_proto_rawDescData
}

var file_yoke_plugin_v1_families_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_yoke_plugin_v1_families_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_yoke_plugin_v1_families_proto_goTypes = []any{
	(SessionMessage_Revoked_Cause)(0), // 0: yoke.plugin.v1.SessionMessage.Revoked.Cause
	(Control_Activate_Transport)(0),   // 1: yoke.plugin.v1.Control.Activate.Transport
	(Ack_Outcome)(0),                  // 2: yoke.plugin.v1.Ack.Outcome
	(*SessionMessage)(nil),            // 3: yoke.plugin.v1.SessionMessage
	(*Control)(nil),                   // 4: yoke.plugin.v1.Control
	(*Ack)(nil),                       // 5: yoke.plugin.v1.Ack
	(*Query)(nil),                     // 6: yoke.plugin.v1.Query
	(*Data)(nil),                      // 7: yoke.plugin.v1.Data
	(*Health)(nil),                    // 8: yoke.plugin.v1.Health
	(*Event)(nil),                     // 9: yoke.plugin.v1.Event
	(*Error)(nil),                     // 10: yoke.plugin.v1.Error
	(*SessionMessage_Open)(nil),       // 11: yoke.plugin.v1.SessionMessage.Open
	(*SessionMessage_Close)(nil),      // 12: yoke.plugin.v1.SessionMessage.Close
	(*SessionMessage_Revoked)(nil),    // 13: yoke.plugin.v1.SessionMessage.Revoked
	(*Control_Command)(nil),           // 14: yoke.plugin.v1.Control.Command
	(*Control_Activate)(nil),          // 15: yoke.plugin.v1.Control.Activate
	(*Control_Stop)(nil),              // 16: yoke.plugin.v1.Control.Stop
	(*Query_Question)(nil),            // 17: yoke.plugin.v1.Query.Question
	(*Query_Answer)(nil),              // 18: yoke.plugin.v1.Query.Answer
	(*Error_Divergence)(nil),          // 19: yoke.plugin.v1.Error.Divergence
	(*Error_Withheld)(nil),            // 20: yoke.plugin.v1.Error.Withheld
}
var file_yoke_plugin_v1_families_proto_depIdxs = []int32{
	11, // 0: yoke.plugin.v1.SessionMessage.open:type_name -> yoke.plugin.v1.SessionMessage.Open
	12, // 1: yoke.plugin.v1.SessionMessage.close:type_name -> yoke.plugin.v1.SessionMessage.Close
	13, // 2: yoke.plugin.v1.SessionMessage.revoked:type_name -> yoke.plugin.v1.SessionMessage.Revoked
	14, // 3: yoke.plugin.v1.Control.command:type_name -> yoke.plugin.v1.Control.Command
	15, // 4: yoke.plugin.v1.Control.activate:type_name -> yoke.plugin.v1.Control.Activate
	16, // 5: yoke.plugin.v1.Control.stop:type_name -> yoke.plugin.v1.Control.Stop
	2,  // 6: yoke.plugin.v1.Ack.outcome:type_name -> yoke.plugin.v1.Ack.Outcome
	17, // 7: yoke.plugin.v1.Query.question:type_name -> yoke.plugin.v1.Query.Question
	18, // 8: yoke.plugin.v1.Query.answer:type_name -> yoke.plugin.v1.Query.Answer
	19, // 9: yoke.plugin.v1.Error.divergent:type_name -> yoke.plugin.v1.Error.Divergence
	20, // 10: yoke.plugin.v1.Error.withheld:type_name -> yoke.plugin.v1.Error.Withheld
	0,  // 11: yoke.plugin.v1.SessionMessage.Revoked.cause:type_name -> yoke.plugin.v1.SessionMessage.Revoked.Cause
	1,  // 12: yoke.plugin.v1.Control.Activate.transport:type_name -> yoke.plugin.v1.Control.Activate.Transport
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_yoke_plugin_v1_families_proto_init() }
func file_yoke_plugin_v1_families_proto_init() {
	if File_yoke_plugin_v1_families_proto != nil {
		return
	}
	file_yoke_plugin_v1_families_proto_msgTypes[0].OneofWrappers = []any{
		(*SessionMessage_Open_)(nil),
		(*SessionMessage_Close_)(nil),
		(*SessionMessage_Revoked_)(nil),
	}
	file_yoke_plugin_v1_families_proto_msgTypes[1].OneofWrappers = []any{
		(*Control_Command_)(nil),
		(*Control_Activate_)(nil),
		(*Control_Stop_)(nil),
	}
	file_yoke_plugin_v1_families_proto_msgTypes[3].OneofWrappers = []any{
		(*Query_Question_)(nil),
		(*Query_Answer_)(nil),
	}
	file_yoke_plugin_v1_families_proto_msgTypes[7].OneofWrappers = []any{
		(*Error_Divergent)(nil),
		(*Error_Withheld_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_families_proto_rawDesc), len(file_yoke_plugin_v1_families_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yoke_plugin_v1_families_proto_goTypes,
		DependencyIndexes: file_yoke_plugin_v1_families_proto_depIdxs,
		EnumInfos:         file_yoke_plugin_v1_families_proto_enumTypes,
		MessageInfos:      file_yoke_plugin_v1_families_proto_msgTypes,
	}.Build()
	File_yoke_plugin_v1_families_proto = out.File
	file_yoke_plugin_v1_families_proto_goTypes = nil
	file_yoke_plugin_v1_families_proto_depIdxs = nil
}
