// Registration: one question with one answer.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/plugin/v1/register.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The nine stages of admission, in the order they are evaluated.
type Stage int32

const (
	Stage_STAGE_UNSPECIFIED             Stage = 0
	Stage_STAGE_STRUCTURAL              Stage = 1
	Stage_STAGE_IDENTITY                Stage = 2
	Stage_STAGE_ADMINISTRATIVE_STATE    Stage = 3
	Stage_STAGE_AUTHENTICATION          Stage = 4
	Stage_STAGE_COMPATIBILITY           Stage = 5
	Stage_STAGE_DECLARATION_CONSISTENCY Stage = 6
	Stage_STAGE_AUTHORISATION           Stage = 7
	Stage_STAGE_UNIT_CONFLICT           Stage = 8
	Stage_STAGE_SESSION_PREPARATION     Stage = 9
)

// Enum value maps for Stage.
var (
	Stage_name = map[int32]string{
		0: "STAGE_UNSPECIFIED",
		1: "STAGE_STRUCTURAL",
		2: "STAGE_IDENTITY",
		3: "STAGE_ADMINISTRATIVE_STATE",
		4: "STAGE_AUTHENTICATION",
		5: "STAGE_COMPATIBILITY",
		6: "STAGE_DECLARATION_CONSISTENCY",
		7: "STAGE_AUTHORISATION",
		8: "STAGE_UNIT_CONFLICT",
		9: "STAGE_SESSION_PREPARATION",
	}
	Stage_value = map[string]int32{
		"STAGE_UNSPECIFIED":             0,
		"STAGE_STRUCTURAL":              1,
		"STAGE_IDENTITY":                2,
		"STAGE_ADMINISTRATIVE_STATE":    3,
		"STAGE_AUTHENTICATION":          4,
		"STAGE_COMPATIBILITY":           5,
		"STAGE_DECLARATION_CONSISTENCY": 6,
		"STAGE_AUTHORISATION":           7,
		"STAGE_UNIT_CONFLICT":           8,
		"STAGE_SESSION_PREPARATION":     9,
	}
)

func (x Stage) Enum() *Stage {
	p := new(Stage)
	*p = x
	return p
}

func (x Stage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stage) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_register_proto_enumTypes[0].Descriptor()
}

func (Stage) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_register_proto_enumTypes[0]
}

func (x Stage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stage.Descriptor instead.
func (Stage) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{0}
}

type RegisterResponse_Outcome int32

const (
	RegisterResponse_OUTCOME_UNSPECIFIED                RegisterResponse_Outcome = 0
	RegisterResponse_OUTCOME_ACCEPTED                   RegisterResponse_Outcome = 1
	RegisterResponse_OUTCOME_ACCEPTED_WITH_RESTRICTIONS RegisterResponse_Outcome = 2
	RegisterResponse_OUTCOME_REFUSED                    RegisterResponse_Outcome = 3
)

// Enum value maps for RegisterResponse_Outcome.
var (
	RegisterResponse_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ACCEPTED",
		2: "OUTCOME_ACCEPTED_WITH_RESTRICTIONS",
		3: "OUTCOME_REFUSED",
	}
	RegisterResponse_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":                0,
		"OUTCOME_ACCEPTED":                   1,
		"OUTCOME_ACCEPTED_WITH_RESTRICTIONS": 2,
		"OUTCOME_REFUSED":                    3,
	}
)

func (x RegisterResponse_Outcome) Enum() *RegisterResponse_Outcome {
	p := new(RegisterResponse_Outcome)
	*p = x
	return p
}

func (x RegisterResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_yoke_plugin_v1_register_proto_enumTypes[1].Descriptor()
}

func (RegisterResponse_Outcome) Type() protoreflect.EnumType {
	return &file_yoke_plugin_v1_register_proto_enumTypes[1]
}

func (x RegisterResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterResponse_Outcome.Descriptor instead.
func (RegisterResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{2, 0}
}

// What a unit claims. No address, no Session identity and no state.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plugin and unit identities, exactly as the environment supplied them.
	Plugin string `protobuf:"bytes,1,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Unit   string `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	// The bootstrap token: opaque, never logged and never stored.
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// The protocol version: the Contract this unit was built against.
	Protocol uint32 `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Recorded and reported, and never weighed.
	ArtifactVersion string `protobuf:"bytes,5,opt,name=artifact_version,json=artifactVersion,proto3" json:"artifact_version,omitempty"`
	Language        string `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	SdkLine         string `protobuf:"bytes,7,opt,name=sdk_line,json=sdkLine,proto3" json:"sdk_line,omitempty"`
	// The declared surface.
	Declared      *Surface `protobuf:"bytes,8,opt,name=declared,proto3" json:"declared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *RegisterRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *RegisterRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RegisterRequest) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *RegisterRequest) GetArtifactVersion() string {
	if x != nil {
		return x.ArtifactVersion
	}
	return ""
}

func (x *RegisterRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RegisterRequest) GetSdkLine() string {
	if x != nil {
		return x.SdkLine
	}
	return ""
}

func (x *RegisterRequest) GetDeclared() *Surface {
	if x != nil {
		return x.Declared
	}
	return nil
}

// Four lists of identifiers: a declared surface, a granted scope, or what was withheld from one.
type Surface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Streams       []string               `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	Commands      []string               `protobuf:"bytes,3,rep,name=commands,proto3" json:"commands,omitempty"`
	Queries       []string               `protobuf:"bytes,4,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Surface) Reset() {
	*x = Surface{}
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Surface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Surface) ProtoMessage() {}

func (x *Surface) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Surface.ProtoReflect.Descriptor instead.
func (*Surface) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{1}
}

func (x *Surface) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Surface) GetStreams() []string {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *Surface) GetCommands() []string {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Surface) GetQueries() []string {
	if x != nil {
		return x.Queries
	}
	return nil
}

type RegisterResponse struct {
	state   protoimpl.MessageState   `protogen:"open.v1"`
	Outcome RegisterResponse_Outcome `protobuf:"varint,1,opt,name=outcome,proto3,enum=yoke.plugin.v1.RegisterResponse_Outcome" json:"outcome,omitempty"`
	// On a refusal: how far the request got, which decides whether the token was spent.
	Stage Stage `protobuf:"varint,2,opt,name=stage,proto3,enum=yoke.plugin.v1.Stage" json:"stage,omitempty"`
	// On a refusal: the machine's answer, one of Code's names, and the person's.
	Code    string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// On an acceptance: opaque, assigned by the Core, and not guessable.
	SessionId string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// On an acceptance: the four lists after the intersection.
	Granted *Surface `protobuf:"bytes,6,opt,name=granted,proto3" json:"granted,omitempty"`
	// On a restricted acceptance: item by item, never a count.
	Withheld *Surface `protobuf:"bytes,7,opt,name=withheld,proto3" json:"withheld,omitempty"`
	// The terms the Core assigned.
	Heartbeat     *HeartbeatTerms `protobuf:"bytes,8,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetOutcome() RegisterResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return RegisterResponse_OUTCOME_UNSPECIFIED
}

func (x *RegisterResponse) GetStage() Stage {
	if x != nil {
		return x.Stage
	}
	return Stage_STAGE_UNSPECIFIED
}

func (x *RegisterResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetGranted() *Surface {
	if x != nil {
		return x.Granted
	}
	return nil
}

func (x *RegisterResponse) GetWithheld() *Surface {
	if x != nil {
		return x.Withheld
	}
	return nil
}

func (x *RegisterResponse) GetHeartbeat() *HeartbeatTerms {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

type HeartbeatTerms struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Interval *durationpb.Duration   `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// How many consecutive misses the Core tolerates.
	Tolerance     uint32 `protobuf:"varint,2,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatTerms) Reset() {
	*x = HeartbeatTerms{}
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatTerms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatTerms) ProtoMessage() {}

func (x *HeartbeatTerms) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatTerms.ProtoReflect.Descriptor instead.
func (*HeartbeatTerms) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_register_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatTerms) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *HeartbeatTerms) GetTolerance() uint32 {
	if x != nil {
		return x.Tolerance
	}
	return 0
}

var File_yoke_plugin_v1_register_proto protoreflect.FileDescriptor

const file_yoke_plugin_v1_register_proto_rawDesc = "" +
	"\n" +
	"\x1dyoke/plugin/v1/register.proto\x12\x0eyoke.plugin.v1\x1a\x1egoogle/protobuf/duration.proto\"\x86\x02\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06plugin\x18\x01 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unit\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\rR\bprotocol\x12)\n" +
	"\x10artifact_version\x18\x05 \x01(\tR\x0fartifactVersion\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x19\n" +
	"\bsdk_line\x18\a \x01(\tR\asdkLine\x123\n" +
	"\bdeclared\x18\b \x01(\v2\x17.yoke.plugin.v1.SurfaceR\bdeclared\"}\n" +
	"\aSurface\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\x12\x18\n" +
	"\astreams\x18\x02 \x03(\tR\astreams\x12\x1a\n" +
	"\bcommands\x18\x03 \x03(\tR\bcommands\x12\x18\n" +
	"\aqueries\x18\x04 \x03(\tR\aqueries\"\xed\x03\n" +
	"\x10RegisterResponse\x12B\n" +
	"\aoutcome\x18\x01 \x01(\x0e2(.yoke.plugin.v1.RegisterResponse.OutcomeR\aoutcome\x12+\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x15.yoke.plugin.v1.StageR\x05stage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x121\n" +
	"\agranted\x18\x06 \x01(\v2\x17.yoke.plugin.v1.SurfaceR\agranted\x123\n" +
	"\bwithheld\x18\a \x01(\v2\x17.yoke.plugin.v1.SurfaceR\bwithheld\x12<\n" +
	"\theartbeat\x18\b \x01(\v2\x1e.yoke.plugin.v1.HeartbeatTermsR\theartbeat\"u\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_ACCEPTED\x10\x01\x12&\n" +
	"\"OUTCOME_ACCEPTED_WITH_RESTRICTIONS\x10\x02\x12\x13\n" +
	"\x0fOUTCOME_REFUSED\x10\x03\"e\n" +
	"\x0eHeartbeatTerms\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12\x1c\n" +
	"\ttolerance\x18\x02 \x01(\rR\ttolerance*\x8f\x02\n" +
	"\x05Stage\x12\x15\n" +
	"\x11STAGE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STAGE_STRUCTURAL\x10\x01\x12\x12\n" +
	"\x0eSTAGE_IDENTITY\x10\x02\x12\x1e\n" +
	"\x1aSTAGE_ADMINISTRATIVE_STATE\x10\x03\x12\x18\n" +
	"\x14STAGE_AUTHENTICATION\x10\x04\x12\x17\n" +
	"\x13STAGE_COMPATIBILITY\x10\x05\x12!\n" +
	"\x1dSTAGE_DECLARATION_CONSISTENCY\x10\x06\x12\x17\n" +
	"\x13STAGE_AUTHORISATION\x10\a\x12\x17\n" +
	"\x13STAGE_UNIT_CONFLICT\x10\b\x12\x1d\n" +
	"\x19STAGE_SESSION_PREPARATION\x10\t2Y\n" +
	"\bRegister\x12M\n" +
	"\bRegister\x12\x1f.yoke.plugin.v1.RegisterRequest\x1a .yoke.plugin.v1.RegisterResponseB<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3"

var (
	file_yoke_plugin_v1_register_proto_rawDescOnce sync.Once
	file_yoke_plugin_v1_register_proto_rawDescData []byte
)

func file_yoke_plugin_v1_register_proto_rawDescGZIP() []byte {
	file_yoke_plugin_v1_register_proto_rawDescOnce.Do(func() {
		file_yoke_plugin_v1_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_register_proto_rawDesc), len(file_yoke_plugin_v1_register_proto_rawDesc)))
	})
	return file_yoke_plugin_v1_register_proto_rawDescData
}

var file_yoke_plugin_v1_register_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_yoke_plugin_v1_register_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_yoke_plugin_v1_register_proto_goTypes = []any{
	(Stage)(0),                    // 0: yoke.plugin.v1.Stage
	(RegisterResponse_Outcome)(0), // 1: yoke.plugin.v1.RegisterResponse.Outcome
	(*RegisterRequest)(nil),       // 2: yoke.plugin.v1.RegisterRequest
	(*Surface)(nil),               // 3: yoke.plugin.v1.Surface
	(*RegisterResponse)(nil),      // 4: yoke.plugin.v1.RegisterResponse
	(*HeartbeatTerms)(nil),        // 5: yoke.plugin.v1.HeartbeatTerms
	(*durationpb.Duration)(nil),   // 6: google.protobuf.Duration
}
var file_yoke_plugin_v1_register_proto_depIdxs = []int32{
	3, // 0: yoke.plugin.v1.RegisterRequest.declared:type_name -> yoke.plugin.v1.Surface
	1, // 1: yoke.plugin.v1.RegisterResponse.outcome:type_name -> yoke.plugin.v1.RegisterResponse.Outcome
	0, // 2: yoke.plugin.v1.RegisterResponse.stage:type_name -> yoke.plugin.v1.Stage
	3, // 3: yoke.plugin.v1.RegisterResponse.granted:type_name -> yoke.plugin.v1.Surface
	3, // 4: yoke.plugin.v1.RegisterResponse.withheld:type_name -> yoke.plugin.v1.Surface
	5, // 5: yoke.plugin.v1.RegisterResponse.heartbeat:type_name -> yoke.plugin.v1.HeartbeatTerms
	6, // 6: yoke.plugin.v1.HeartbeatTerms.interval:type_name -> google.protobuf.Duration
	2, // 7: yoke.plugin.v1.Register.Register:input_type -> yoke.plugin.v1.RegisterRequest
	4, // 8: yoke.plugin.v1.Register.Register:output_type -> yoke.plugin.v1.RegisterResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_yoke_plugin_v1_register_proto_init() }
func file_yoke_plugin_v1_register_proto_init() {
	if File_yoke_plugin_v1_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_register_proto_rawDesc), len(file_yoke_plugin_v1_register_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yoke_plugin_v1_register_proto_goTypes,
		DependencyIndexes: file_yoke_plugin_v1_register_proto_depIdxs,
		EnumInfos:         file_yoke_plugin_v1_register_proto_enumTypes,
		MessageInfos:      file_yoke_plugin_v1_register_proto_msgTypes,
	}.Build()
	File_yoke_plugin_v1_register_proto = out.File
	file_yoke_plugin_v1_register_proto_goTypes = nil
	file_yoke_plugin_v1_register_proto_depIdxs = nil
}
