// The Session: one bidirectional stream, which is the Session.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: yoke/plugin/v1/session.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Four header fields and exactly one payload. The payload that is set is the family.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique within the Session.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The identity admission issued.
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The sender's clock at emission, in nanoseconds since the epoch.
	SentAtUnixNano int64 `protobuf:"varint,3,opt,name=sent_at_unix_nano,json=sentAtUnixNano,proto3" json:"sent_at_unix_nano,omitempty"`
	// The message identity of what this answers; empty where the family never correlates.
	CorrelationId string `protobuf:"bytes,4,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Session
	//	*Envelope_Control
	//	*Envelope_Ack
	//	*Envelope_Query
	//	*Envelope_Data
	//	*Envelope_Health
	//	*Envelope_Event
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_yoke_plugin_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_yoke_plugin_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_yoke_plugin_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetSentAtUnixNano() int64 {
	if x != nil {
		return x.SentAtUnixNano
	}
	return 0
}

func (x *Envelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSession() *SessionMessage {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Session); ok {
			return x.Session
		}
	}
	return nil
}

func (x *Envelope) GetControl() *Control {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Control); ok {
			return x.Control
		}
	}
	return nil
}

func (x *Envelope) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Envelope) GetQuery() *Query {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Query); ok {
			return x.Query
		}
	}
	return nil
}

func (x *Envelope) GetData() *Data {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *Envelope) GetHealth() *Health {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Envelope) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Session struct {
	Session *SessionMessage `protobuf:"bytes,5,opt,name=session,proto3,oneof"`
}

type Envelope_Control struct {
	Control *Control `protobuf:"bytes,6,opt,name=control,proto3,oneof"`
}

type Envelope_Ack struct {
	Ack *Ack `protobuf:"bytes,7,opt,name=ack,proto3,oneof"`
}

type Envelope_Query struct {
	Query *Query `protobuf:"bytes,8,opt,name=query,proto3,oneof"`
}

type Envelope_Data struct {
	Data *Data `protobuf:"bytes,9,opt,name=data,proto3,oneof"`
}

type Envelope_Health struct {
	Health *Health `protobuf:"bytes,10,opt,name=health,proto3,oneof"`
}

type Envelope_Event struct {
	Event *Event `protobuf:"bytes,11,opt,name=event,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,12,opt,name=error,proto3,oneof"`
}

func (*Envelope_Session) isEnvelope_Payload() {}

func (*Envelope_Control) isEnvelope_Payload() {}

func (*Envelope_Ack) isEnvelope_Payload() {}

func (*Envelope_Query) isEnvelope_Payload() {}

func (*Envelope_Data) isEnvelope_Payload() {}

func (*Envelope_Health) isEnvelope_Payload() {}

func (*Envelope_Event) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

var File_yoke_plugin_v1_session_proto protoreflect.FileDescriptor

const file_yoke_plugin_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1cyoke/plugin/v1/session.proto\x12\x0eyoke.plugin.v1\x1a\x1dyoke/plugin/v1/families.proto\"\xaa\x04\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12)\n" +
	"\x11sent_at_unix_nano\x18\x03 \x01(\x03R\x0esentAtUnixNano\x12%\n" +
	"\x0ecorrelation_id\x18\x04 \x01(\tR\rcorrelationId\x12:\n" +
	"\asession\x18\x05 \x01(\v2\x1e.yoke.plugin.v1.SessionMessageH\x00R\asession\x123\n" +
	"\acontrol\x18\x06 \x01(\v2\x17.yoke.plugin.v1.ControlH\x00R\acontrol\x12'\n" +
	"\x03ack\x18\a \x01(\v2\x13.yoke.plugin.v1.AckH\x00R\x03ack\x12-\n" +
	"\x05query\x18\b \x01(\v2\x15.yoke.plugin.v1.QueryH\x00R\x05query\x12*\n" +
	"\x04data\x18\t \x01(\v2\x14.yoke.plugin.v1.DataH\x00R\x04data\x120\n" +
	"\x06health\x18\n" +
	" \x01(\v2\x16.yoke.plugin.v1.HealthH\x00R\x06health\x12-\n" +
	"\x05event\x18\v \x01(\v2\x15.yoke.plugin.v1.EventH\x00R\x05event\x12-\n" +
	"\x05error\x18\f \x01(\v2\x15.yoke.plugin.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload2I\n" +
	"\aSession\x12>\n" +
	"\x04Open\x12\x18.yoke.plugin.v1.Envelope\x1a\x18.yoke.plugin.v1.Envelope(\x010\x01B<Z:github.com/yoke-project/yoke/proto/yoke/plugin/v1;pluginv1b\x06proto3"

var (
	file_yoke_plugin_v1_session_proto_rawDescOnce sync.Once
	file_yoke_plugin_v1_session_proto_rawDescData []byte
)

func file_yoke_plugin_v1_session_proto_rawDescGZIP() []byte {
	file_yoke_plugin_v1_session_proto_rawDescOnce.Do(func() {
		file_yoke_plugin_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_session_proto_rawDesc), len(file_yoke_plugin_v1_session_proto_rawDesc)))
	})
	return file_yoke_plugin_v1_session_proto_rawDescData
}

var file_yoke_plugin_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_yoke_plugin_v1_session_proto_goTypes = []any{
	(*Envelope)(nil),       // 0: yoke.plugin.v1.Envelope
	(*SessionMessage)(nil), // 1: yoke.plugin.v1.SessionMessage
	(*Control)(nil),        // 2: yoke.plugin.v1.Control
	(*Ack)(nil),            // 3: yoke.plugin.v1.Ack
	(*Query)(nil),          // 4: yoke.plugin.v1.Query
	(*Data)(nil),           // 5: yoke.plugin.v1.Data
	(*Health)(nil),         // 6: yoke.plugin.v1.Health
	(*Event)(nil),          // 7: yoke.plugin.v1.Event
	(*Error)(nil),          // 8: yoke.plugin.v1.Error
}
var file_yoke_plugin_v1_session_proto_depIdxs = []int32{
	1, // 0: yoke.plugin.v1.Envelope.session:type_name -> yoke.plugin.v1.SessionMessage
	2, // 1: yoke.plugin.v1.Envelope.control:type_name -> yoke.plugin.v1.Control
	3, // 2: yoke.plugin.v1.Envelope.ack:type_name -> yoke.plugin.v1.Ack
	4, // 3: yoke.plugin.v1.Envelope.query:type_name -> yoke.plugin.v1.Query
	5, // 4: yoke.plugin.v1.Envelope.data:type_name -> yoke.plugin.v1.Data
	6, // 5: yoke.plugin.v1.Envelope.health:type_name -> yoke.plugin.v1.Health
	7, // 6: yoke.plugin.v1.Envelope.event:type_name -> yoke.plugin.v1.Event
	8, // 7: yoke.plugin.v1.Envelope.error:type_name -> yoke.plugin.v1.Error
	0, // 8: yoke.plugin.v1.Session.Open:input_type -> yoke.plugin.v1.Envelope
	0, // 9: yoke.plugin.v1.Session.Open:output_type -> yoke.plugin.v1.Envelope
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_yoke_plugin_v1_session_proto_init() }
func file_yoke_plugin_v1_session_proto_init() {
	if File_yoke_plugin_v1_session_proto != nil {
		return
	}
	file_yoke_plugin_v1_families_proto_init()
	file_yoke_plugin_v1_session_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Session)(nil),
		(*Envelope_Control)(nil),
		(*Envelope_Ack)(nil),
		(*Envelope_Query)(nil),
		(*Envelope_Data)(nil),
		(*Envelope_Health)(nil),
		(*Envelope_Event)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yoke_plugin_v1_session_proto_rawDesc), len(file_yoke_plugin_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yoke_plugin_v1_session_proto_goTypes,
		DependencyIndexes: file_yoke_plugin_v1_session_proto_depIdxs,
		MessageInfos:      file_yoke_plugin_v1_session_proto_msgTypes,
	}.Build()
	File_yoke_plugin_v1_session_proto = out.File
	file_yoke_plugin_v1_session_proto_goTypes = nil
	file_yoke_plugin_v1_session_proto_depIdxs = nil
}
